import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import {createRequire} from "node:module";
const require=createRequire(import.meta.resolve("wrangler"));const {Miniflare}=require("miniflare");
// The real Sites dispatch supplies verified headers. Here the isolated Worker
// receives explicitly simulated identities; there are no production writes.
const origin="https://quizedu-emanuel.emanuelb5.chatgpt.site";
async function walk(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else if(/\.m?js$/.test(e.name))out.push(p);}return out;}
const entry=path.resolve("dist/server/index.js");const modules=[entry,...(await walk(path.resolve("dist/server"))).filter(p=>p!==entry)].map(p=>({type:"ESModule",path:p}));
const mf=new Miniflare({modules,modulesRoot:path.resolve("dist/server"),compatibilityDate:"2026-05-15",compatibilityFlags:["nodejs_compat"],d1Databases:{DB:"quizedu-features"},r2Buckets:["BUCKET"]});let checks=0;
const eq=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);checks++;};const ok=(condition,message)=>{assert.ok(condition,message);checks++;};
class Client{
  cookies=new Map();identity=null;
  async raw(route,body,method="GET",extra={}){return mf.dispatchFetch(origin+route,{method,headers:{cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join("; "),...(this.identity?{"oai-authenticated-user-id":this.identity.id,"oai-authenticated-user-email":this.identity.email,"oai-authenticated-user-full-name":encodeURIComponent(this.identity.name),"oai-authenticated-user-full-name-encoding":"percent-encoded-utf-8"}:{}),...extra},body});}
  async request(route,body,expected=200,method){const response=await this.raw(route,body===undefined?undefined:JSON.stringify(body),method||(body===undefined?"GET":"POST"),body===undefined?{}:{"content-type":"application/json",Origin:origin});for(const c of response.headers.getSetCookie()){const pair=c.split(";")[0],at=pair.indexOf("=");this.cookies.set(pair.slice(0,at),pair.slice(at+1));}const text=await response.text();let data;try{data=JSON.parse(text);}catch{data=text;}eq(response.status,expected,`${route}: ${text.slice(0,240)}`);return data;}
}
const question=(text="Qual prática protege o solo?")=>({id:crypto.randomUUID(),text,options:["Manter a cobertura","Queimar o terreno"],correct:0,seconds:10,explanation:"A cobertura protege o solo da chuva."});
const makeQuiz=(title="Aula de Agroecologia")=>({id:crypto.randomUUID(),title,subject:"Agroecologia",topic:"Solo",mode:"speed",untimed:false,questions:[question()]});
try{
 const database=await mf.getD1Database("DB");for(const file of (await fs.readdir("drizzle")).filter(f=>f.endsWith(".sql")).sort()){for(const statement of (await fs.readFile(`drizzle/${file}`,"utf8")).split("--> statement-breakpoint").map(s=>s.trim()).filter(Boolean))await database.prepare(statement).run();}
 const anonymous=new Client(),host=new Client(),other=new Client();
 const initial=(await host.request("/api/profile",{name:"Professor Emanuel"},201)).profile;eq(initial.permanent,false);ok(initial.id);
 await other.request("/api/profile",{name:"Outro educador"},201);
 let quiz=makeQuiz();let saved=(await host.request("/api/quizzes",quiz)).quiz;eq(saved.subject,"Agroecologia");eq(saved.mode,"speed");
 await host.request("/api/quizzes",{...quiz,mode:"speed",untimed:true},400);await host.request("/api/quizzes",{...quiz,questions:[{...quiz.questions[0],image:"https://external.test/a.svg"}]},400);
 const draftQuiz={...makeQuiz("Meu rascunho"),questions:[{...question(),text:"",options:["",""]}]};const writeId=crypto.randomUUID();const draft1=(await host.request("/api/drafts",{quiz:draftQuiz,revision:0,writeId})).draft;eq(draft1.revision,1);
 const retry=(await host.request("/api/drafts",{quiz:draftQuiz,revision:0,writeId})).draft;eq(retry.revision,1,"Retrying an acknowledged write does not add a revision.");
 let dashboard=await host.request("/api/dashboard");eq(dashboard.drafts[0].quiz.questions[0].text,"");eq((await other.request("/api/dashboard")).drafts.length,0);
 await host.request("/api/drafts",{quiz:draftQuiz,revision:0,writeId:crypto.randomUUID()},409);
 const racing=await Promise.all(["A","B"].map(label=>host.raw("/api/drafts",JSON.stringify({quiz:{...draftQuiz,title:label},revision:1,writeId:crypto.randomUUID()}),"POST",{"content-type":"application/json",Origin:origin})));eq(racing.map(r=>r.status).sort(),[200,409],"Concurrent edits protect the earlier saved draft.");for(const r of racing)await r.arrayBuffer();
 const concurrent=makeQuiz("Reenvio simultâneo");const operation={quiz:concurrent,revision:0,writeId:crypto.randomUUID()};const duplicateWrites=await Promise.all([host.raw("/api/drafts",JSON.stringify(operation),"POST",{"content-type":"application/json",Origin:origin}),host.raw("/api/drafts",JSON.stringify(operation),"POST",{"content-type":"application/json",Origin:origin})]);eq(duplicateWrites.map(r=>r.status),[200,200]);for(const r of duplicateWrites)await r.arrayBuffer();
 await host.request(`/api/drafts/${draftQuiz.id}`,{revision:1},409,"DELETE");await host.request(`/api/drafts/${draftQuiz.id}`,{revision:2},200,"DELETE");
 const finalDraft=(await host.request("/api/drafts",{quiz,revision:0,writeId:crypto.randomUUID()})).draft;
 saved=(await host.request("/api/quizzes",{...quiz,draftRevision:finalDraft.revision,baseUpdatedAt:saved.updatedAt})).quiz;ok(!(await host.request("/api/dashboard")).drafts.some(d=>d.id===quiz.id),"Publishing removes only the matching draft revision.");
 await host.request("/api/quizzes",{...quiz,baseUpdatedAt:saved.updatedAt-1},409);
 const simultaneousSaves=await Promise.all(["Uma versão","Outra versão"].map(title=>host.raw("/api/quizzes",JSON.stringify({...quiz,title,baseUpdatedAt:saved.updatedAt}),"POST",{"content-type":"application/json",Origin:origin})));eq(simultaneousSaves.map(r=>r.status).sort(),[200,409],"Published quizzes also reject concurrent overwrites.");for(const r of simultaneousSaves)await r.arrayBuffer();
 saved=(await host.request("/api/dashboard")).quizzes.find(q=>q.id===quiz.id);quiz={...saved};
 const bank=(await host.request("/api/questions",{id:quiz.questions[0].id,question:quiz.questions[0],subject:"Agroecologia",topic:"Solo"})).question;eq(bank.subject,"Agroecologia");eq((await host.request("/api/questions")).questions.length,1);eq((await other.request("/api/questions")).questions.length,0);await other.request("/api/questions",{id:bank.id,question:question()},403);await other.request(`/api/questions/${bank.id}`,{},404,"DELETE");
 const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6zjQAAAAASUVORK5CYII=","base64");
 let upload=await anonymous.raw("/api/media",png,"POST",{"Content-Type":"image/png",Origin:origin});eq(upload.status,401);await upload.arrayBuffer();
 upload=await host.raw("/api/media",png,"POST",{"Content-Type":"image/png",Origin:origin});eq(upload.status,201);const image=await upload.json();ok(image.url.startsWith("/api/media/"));
 const imageResponse=await anonymous.raw(image.url);eq(imageResponse.status,200);eq(imageResponse.headers.get("content-type"),"image/png");eq(imageResponse.headers.get("x-content-type-options"),"nosniff");eq(Buffer.from(await imageResponse.arrayBuffer()),png);
 const badUpload=await host.raw("/api/media","<svg onload='alert(1)'></svg>","POST",{"Content-Type":"image/jpeg",Origin:origin});eq(badUpload.status,400);await badUpload.arrayBuffer();
 const wrongMime=await host.raw("/api/media",png,"POST",{"Content-Type":"image/jpeg",Origin:origin});eq(wrongMime.status,400);await wrongMime.arrayBuffer();
 const oversize=await host.raw("/api/media",Buffer.alloc(1048577),"POST",{"Content-Type":"image/jpeg",Origin:origin});eq(oversize.status,413);await oversize.arrayBuffer();
 const foreignUpload=await host.raw("/api/media",png,"POST",{"Content-Type":"image/png",Origin:"https://other.test"});eq(foreignUpload.status,403);await foreignUpload.arrayBuffer();
 quiz={...quiz,questions:[{...quiz.questions[0],image:image.url,imageAlt:"Cobertura do solo",optionImages:[image.url,""]}]};saved=(await host.request("/api/quizzes",quiz)).quiz;eq(saved.questions[0].image,image.url);
 const {code}=await host.request("/api/rooms",{quizId:quiz.id},201);
 const alice=new Client(),bob=new Client(),silent=new Client();await alice.request(`/api/rooms/${code}/join`,{name:"=2+2",avatar:"🦊"},201);await bob.request(`/api/rooms/${code}/join`,{name:"Maria",avatar:"🐼"},201);await silent.request(`/api/rooms/${code}/join`,{name:"Sem resposta",avatar:"🐸"},201);
 let state=await host.request(`/api/rooms/${code}`);ok(state.presence&&Object.keys(state.presence).length===3);const participant=await alice.request(`/api/rooms/${code}`);ok(!participant.presence,"Presence diagnostics are limited to the teacher.");
 await database.prepare("UPDATE players SET last_seen = 1 WHERE room = ?").bind(code).run();await alice.request(`/api/rooms/${code}/heartbeat`,{});state=await host.request(`/api/rooms/${code}?since=${encodeURIComponent(state.version)}&presence=1`);ok(state.pulse);ok(Object.values(state.presence).some(t=>t>1));const privatePulse=await anonymous.request(`/api/rooms/${code}?since=${encodeURIComponent(state.version)}&presence=1`);ok(!privatePulse.presence);await anonymous.request(`/api/rooms/${code}/heartbeat`,{},401);
 state=await host.request(`/api/rooms/${code}/control`,{action:"start",status:"lobby",index:-1});eq(state.question.image,image.url);eq(state.question.imageAlt,"Cobertura do solo");ok(!("correct" in state.question));eq(state.correct,null);eq((await host.request(`/api/reports/${code}`)).completed,0,"A live round cannot enter the completed report early.");
 await database.prepare("UPDATE rooms SET starts_at = ?, ends_at = ? WHERE code = ?").bind(Date.now()-1000,Date.now()+9000,code).run();await alice.request(`/api/rooms/${code}/answer`,{index:0,option:0});await bob.request(`/api/rooms/${code}/answer`,{index:0,option:1});await host.request(`/api/rooms/${code}/control`,{action:"end_round",status:"question",index:0});await host.request(`/api/rooms/${code}/control`,{action:"next",status:"results",index:0});
 const report=await host.request(`/api/reports/${code}`);eq(report.completed,1);eq(report.players.length,3);eq(report.accuracy,33);eq(report.questions[0].choices,[1,1]);eq(report.players.find(p=>p.name==="Sem resposta").answeredCount,0);eq(report.players.find(p=>p.name==="Sem resposta").answers,[null]);await anonymous.request(`/api/reports/${code}`,undefined,401);await other.request(`/api/reports/${code}`,undefined,404);
 const csv=await host.raw(`/api/reports/${code}/csv`);eq(csv.status,200);ok(csv.headers.get("content-type").includes("text/csv"));ok((await csv.text()).includes("'=2+2"),"Spreadsheet formulas in participant aliases are neutralized.");await anonymous.request(`/api/reports/${code}/csv`,undefined,401);
 await database.prepare("UPDATE rooms SET expires_at = ? WHERE code = ?").bind(Date.now()-1,code).run();eq((await host.request(`/api/reports/${code}`)).completed,1,"Reports survive room expiry.");
 const share=await host.request(`/api/quizzes/${quiz.id}/share`,{});ok(/^[a-f0-9]{64}$/.test(share.token));const publicCopy=(await anonymous.request(`/api/shares/${share.token}`)).quiz;eq(publicCopy.title,quiz.title);ok(!("owner" in publicCopy));const ownCopy=(await other.request(`/api/shares/${share.token}/copy`,{},201)).quiz;ok(ownCopy.id!==quiz.id);ok(ownCopy.questions[0].id!==quiz.questions[0].id);eq(ownCopy.questions[0].image,image.url);
 await host.request("/api/quizzes",{...quiz,title:"Título novo"});eq((await anonymous.request(`/api/shares/${share.token}`)).quiz.title,quiz.title,"Shared quizzes are explicit snapshots.");await other.request(`/api/quizzes/${quiz.id}/share`,{},404);await other.request(`/api/quizzes/${quiz.id}/share`,{},200,"DELETE");await anonymous.request(`/api/shares/${share.token}`);await host.request(`/api/quizzes/${quiz.id}/share`,{},200,"DELETE");await anonymous.request(`/api/shares/${share.token}`,undefined,404);
 // A permanent identity can preserve the existing cookie-owned work.
 host.identity={id:"verified-teacher-a",email:"emanuel@example.test",name:"Emanuel Bonfim"};const oldCookie=host.cookies.get("qe_host");const linked=(await host.request("/api/account/link",{})).profile;eq(linked.id,initial.id);eq(linked.permanent,true);dashboard=await host.request("/api/dashboard");ok(dashboard.quizzes.some(q=>q.id===quiz.id));ok(dashboard.drafts.some(d=>d.id===concurrent.id));
 const secondDevice=new Client();secondDevice.identity={...host.identity,email:"changed@example.test"};eq((await secondDevice.request("/api/dashboard")).profile.id,initial.id);eq((await secondDevice.request("/api/questions")).questions[0].id,bank.id);eq((await secondDevice.request(`/api/reports/${code}`)).code,code);
 const oldDevice=new Client();oldDevice.cookies.set("qe_host",oldCookie);eq((await oldDevice.request("/api/dashboard")).profile,null,"The old temporary secret cannot authenticate a permanent account.");
 const forged=await mf.dispatchFetch("https://independent.workers.dev/api/dashboard",{headers:{"oai-authenticated-user-id":host.identity.id,"oai-authenticated-user-email":"attacker@example.test"}});eq((await forged.json()).profile,null,"Independent hosting cannot trust arbitrary Sites identity headers.");
 const anotherAccount=new Client();anotherAccount.identity={id:"verified-teacher-b",email:"other@example.test",name:"Outro professor"};await anotherAccount.request("/api/account/link",{});eq((await anotherAccount.request("/api/dashboard")).quizzes.length,0);await anotherAccount.request(`/api/reports/${code}`,undefined,404);
 const migrating=new Client();const temp=(await migrating.request("/api/profile",{name:"Temporário com tarefas"},201)).profile;const migratingQuiz=makeQuiz("Atividade no aparelho antigo");await migrating.request("/api/quizzes",migratingQuiz);await migrating.request("/api/drafts",{quiz:makeQuiz("Rascunho para migrar"),revision:0,writeId:crypto.randomUUID()});migrating.identity=anotherAccount.identity;ok((await migrating.request("/api/dashboard")).importAvailable);await migrating.request("/api/account/link",{});ok((await anotherAccount.request("/api/dashboard")).quizzes.some(q=>q.id===migratingQuiz.id));eq((await anotherAccount.request("/api/dashboard")).drafts.length,1);ok(temp.id!==(await migrating.request("/api/dashboard")).profile.id);
 // Learning mode gives equal points for correct answers, even much later.
 const learning={...makeQuiz("Aprender no próprio ritmo"),mode:"accuracy",untimed:true,questions:[question(),question("Qual organismo é polinizador?")]};await host.request("/api/quizzes",learning);const learnRoom=await host.request("/api/rooms",{quizId:learning.id},201);const first=new Client(),fast=new Client();await first.request(`/api/rooms/${learnRoom.code}/join`,{name:"Primeiro a entrar",avatar:"🦊"},201);await fast.request(`/api/rooms/${learnRoom.code}/join`,{name:"Respondeu primeiro",avatar:"🐝"},201);let learn=await host.request(`/api/rooms/${learnRoom.code}/control`,{action:"start",status:"lobby",index:-1});eq(learn.endsAt,null);eq(learn.untimed,true);await database.prepare("UPDATE rooms SET starts_at = ? WHERE code = ?").bind(Date.now()-65000,learnRoom.code).run();await fast.request(`/api/rooms/${learnRoom.code}/answer`,{index:0,option:0});await first.request(`/api/rooms/${learnRoom.code}/answer`,{index:0,option:0});learn=await host.request(`/api/rooms/${learnRoom.code}`);eq(learn.status,"results");eq(learn.players.map(p=>p.score),[1000,1000]);eq(learn.players[0].name,"Primeiro a entrar","Accuracy ties do not use response speed.");
 learn=await host.request(`/api/rooms/${learnRoom.code}/control`,{action:"next",status:"results",index:0});await database.prepare("UPDATE rooms SET starts_at = ? WHERE code = ?").bind(Date.now()-1000,learnRoom.code).run();await first.request(`/api/rooms/${learnRoom.code}/answer`,{index:1,option:0});await host.request(`/api/rooms/${learnRoom.code}/control`,{action:"end_round",status:"question",index:1});await host.request(`/api/rooms/${learnRoom.code}/control`,{action:"next",status:"results",index:1});const learningReport=await host.request(`/api/reports/${learnRoom.code}`);eq(learningReport.players.map(p=>p.score),[2000,1000]);eq(learningReport.accuracy,75);eq(learningReport.players[1].answers[1],null);eq(learningReport.mode,"accuracy");
 const timed={...makeQuiz("Aprendizagem com relógio"),mode:"accuracy",untimed:false};await host.request("/api/quizzes",timed);const timedRoom=await host.request("/api/rooms",{quizId:timed.id},201);await first.request(`/api/rooms/${timedRoom.code}/join`,{name:"Estudante",avatar:"🦊"},201);await host.request(`/api/rooms/${timedRoom.code}/control`,{action:"start",status:"lobby",index:-1});await database.prepare("UPDATE rooms SET starts_at = ?, ends_at = ? WHERE code = ?").bind(Date.now()-20000,Date.now()-1,timedRoom.code).run();await first.request(`/api/rooms/${timedRoom.code}/answer`,{index:0,option:0},409);eq((await host.request(`/api/rooms/${timedRoom.code}`)).status,"results");
 await host.request(`/api/quizzes/${quiz.id}`,{},200,"DELETE");eq((await secondDevice.request(`/api/reports/${code}`)).questions[0].question.image,image.url,"Deleting the source quiz preserves the report and its images.");await host.request(`/api/questions/${bank.id}`,{},200,"DELETE");eq((await host.request("/api/questions")).questions.length,0);
 const csrf=await host.raw("/api/account/link","{}","POST",{"content-type":"application/json",Origin:"https://other.test"});eq(csrf.status,403);await csrf.arrayBuffer();await anonymous.request("/api/account/link",{},401);
 const reportPage=await host.request(`/relatorio/${code}`);ok(reportPage.includes("QuizEdu"));const share2=await host.request(`/api/quizzes/${learning.id}/share`,{});const sharePage=await anonymous.request(`/compartilhar/${share2.token}`);ok(sharePage.includes("QuizEdu"));
 console.log(`✓ QuizEdu 2: permanent accounts, migration, draft concurrency, images, question bank, sharing, private reports, CSV, presence and both game modes. ${checks} checks passed.`);
}finally{await mf.dispose();}
