import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {pathToFileURL} from "node:url";
import ts from "typescript";
import JSZip from "jszip";
import pptxgen from "pptxgenjs";
import * as CFB from "cfb";
const dir=await fs.mkdtemp(path.join(os.tmpdir(),"quizedu-import-"));let checks=0;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++;},ok=a=>{assert.ok(a);checks++;};
try{
 await fs.writeFile(path.join(dir,"package.json"),'{"type":"module"}');
 for(const name of ["quiz","presentation","presentation-editor","presentation-import"]){let source=ts.transpileModule(await fs.readFile(`lib/${name}.ts`,"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from "\.\/(quiz|presentation|presentation-editor)"/g,'from "./$1.js"');for(const dep of ["jszip","cfb","fast-xml-parser"])source=source.replace(`"${dep}"`,JSON.stringify(import.meta.resolve(dep)));await fs.writeFile(path.join(dir,name+".js"),source);}
 const {importPresentation,parseLegacyPowerPoint,MAX_IMPORT_BYTES}=await import(pathToFileURL(path.join(dir,"presentation-import.js")));const p=await import(pathToFileURL(path.join(dir,"presentation.js"))),editor=await import(pathToFileURL(path.join(dir,"presentation-editor.js")));
 const png="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4nQAAAAASUVORK5CYII=";
 const office=new pptxgen();office.layout="LAYOUT_WIDE";let slide=office.addSlide();slide.background={color:"15345E"};slide.addText([{text:"Solo vivo",options:{bold:true,color:"FFFFFF"}},{text:" e água",options:{italic:true,color:"E4F2FF"}}],{x:1,y:1,w:10,h:1,fontFace:"Arial",fontSize:36,align:"center"});slide.addImage({data:"image/png;base64,"+png,x:1,y:2,w:3,h:2});slide.addTable([["Planta","Produção"],["Milho","32"]],{x:5,y:2,w:5,h:2,fontSize:20});slide.addNotes("Nota privada para Emanuel");slide=office.addSlide();slide.addText("Segundo slide",{x:1,y:1,w:10,h:1,fontSize:30});slide.addChart(office.ChartType.bar,[{name:"Turma",labels:["A","B"],values:[10,20]}],{x:1,y:2,w:8,h:3});
 const bytes=new Uint8Array(await office.write({outputType:"uint8array"}));const result=await importPresentation(bytes,"Aula de solo.pptx");eq(result.deck.slides.length,2);eq(result.deck.title,"Aula de solo");eq(result.deck.slides[0].background.color.toLowerCase(),"#15345e");ok(result.deck.slides[0].notes.includes("Nota privada"));eq(result.assets.length,1);const text=result.deck.slides[0].elements.find(e=>e.type==="text");eq(p.richTextPlain(text.doc),"Solo vivo e água");ok(JSON.stringify(text.doc).includes('"bold"'));ok(JSON.stringify(text.doc).includes('"italic"'));ok(text.fontSize>30);eq(text.align,"center");eq(result.deck.slides[0].elements.find(e=>e.type==="table").cells,[["Planta","Produção"],["Milho","32"]]);eq(result.deck.slides[1].elements.find(e=>e.type==="chart").values,[10,20]);p.validateDeck(result.deck);checks++;
 for(const extension of ["ppsx","potx"]){eq((await importPresentation(bytes,"Modelo."+extension)).deck.slides.length,2);}
 const zip=await JSZip.loadAsync(bytes);let manifest=await zip.file("ppt/presentation.xml").async("string");const ids=[...manifest.matchAll(/<p:sldId\b[^>]+\/>/g)].map(m=>m[0]);manifest=manifest.replace(ids[0],"SWAP").replace(ids[1],ids[0]).replace("SWAP",ids[1]);zip.file("ppt/presentation.xml",manifest);const reordered=await importPresentation(await zip.generateAsync({type:"uint8array"}),"reordenada.pptx");eq(reordered.deck.slides[0].title,"Segundo slide");
 const odf=new JSZip();odf.file("content.xml",`<office:document-content xmlns:office="urn:o" xmlns:draw="urn:d" xmlns:text="urn:t" xmlns:svg="urn:s" xmlns:xlink="urn:x"><office:body><office:presentation><draw:page draw:name="Irrigação"><draw:frame svg:x="2cm" svg:y="3cm" svg:width="18cm" svg:height="4cm"><draw:text-box><text:p>Água no campo</text:p><text:p>Gotejamento eficiente</text:p></draw:text-box></draw:frame><draw:frame svg:x="2cm" svg:y="7cm" svg:width="5cm" svg:height="4cm"><draw:image xlink:href="Pictures/a.png"/></draw:frame><presentation:notes xmlns:presentation="urn:p"><text:p>Explicar a pressão</text:p></presentation:notes></draw:page></office:presentation></office:body></office:document-content>`);odf.file("Pictures/a.png",Buffer.from(png,"base64"));for(const extension of ["odp","otp"]){const imported=await importPresentation(await odf.generateAsync({type:"uint8array"}),"Aula."+extension);eq(imported.deck.slides[0].title,"Irrigação");eq(p.richTextPlain(imported.deck.slides[0].elements[0].doc),"Água no campo\nGotejamento eficiente");eq(imported.assets.length,1);eq(imported.deck.slides[0].notes,"Explicar a pressão");}
 const record=(type,payload=Buffer.alloc(0),version=0,instance=0)=>{const b=Buffer.alloc(8);b.writeUInt16LE((instance<<4)|version);b.writeUInt16LE(type,2);b.writeUInt32LE(payload.length,4);return Buffer.concat([b,payload]);};const persistSlide=id=>{const b=Buffer.alloc(20);b.writeUInt32LE(id);return record(1011,b);};const document=record(1000,record(4080,Buffer.concat([persistSlide(2),record(4000,Buffer.from("Primeiro antigo","utf16le")),persistSlide(3),record(4008,Buffer.from("Segundo antigo","latin1"))]),15),15);const one=record(1006,record(4000,Buffer.from("Texto da primeira página","utf16le")),15),two=record(1006,record(4008,Buffer.from("Texto da segunda página","latin1")),15);const offsets=[0,document.length,document.length+one.length];const db=Buffer.alloc(16);db.writeUInt32LE((3<<20)|1);offsets.forEach((offset,i)=>db.writeUInt32LE(offset,4+i*4));const directory=record(6002,db);const editData=Buffer.alloc(28);editData.writeUInt32LE(document.length+one.length+two.length,12);editData.writeUInt32LE(1,16);const edit=record(4085,editData);const stream=Buffer.concat([document,one,two,directory,edit]);const current=Buffer.alloc(28);current.writeUInt32LE(0xE391C05F,12);current.writeUInt32LE(stream.length-edit.length,16);const legacySlides=parseLegacyPowerPoint(stream,current);eq(legacySlides.length,2);eq(legacySlides[0].title,"Primeiro antigo");ok(p.richTextPlain(legacySlides[1].elements[0].doc).includes("Texto da segunda página"));const cfb=CFB.utils.cfb_new();CFB.utils.cfb_add(cfb,"PowerPoint Document",stream);CFB.utils.cfb_add(cfb,"Current User",current);const binary=new Uint8Array(CFB.write(cfb,{type:"buffer"}));for(const extension of ["ppt","pps","pot"]){const imported=await importPresentation(binary,"Antigo."+extension);eq(imported.deck.slides.length,2);ok(imported.warnings.some(w=>w.includes("não são preservados")));}
 const own=p.newDeck();eq((await importPresentation(new TextEncoder().encode(JSON.stringify(own)),"QuizEdu.json")).deck,own);
 for(const [format,name] of [["QuizEdu","aula.quizedu.json"],["Prativerso","aula.prativerso.json"]]){eq((await importPresentation(new TextEncoder().encode(JSON.stringify({format,version:1,deck:own})),name)).deck,own,"Both previous and current brand exports remain editable.");}
 await assert.rejects(()=>importPresentation(bytes,"a.key"),/Escolha PowerPoint/);checks++;await assert.rejects(()=>importPresentation(new Uint8Array(MAX_IMPORT_BYTES+1),"a.pptx"),/15 MB/);checks++;const bad=new JSZip();bad.file("ppt/presentation.xml",'<!DOCTYPE x [<!ENTITY x "bad">]><p:presentation/>');await assert.rejects(async()=>importPresentation(await bad.generateAsync({type:"uint8array"}),"a.pptx"));
 const item={...p.baseElement("image"),x:100,y:100,w:400,h:200};const resized=editor.resizeElement(item,"se",100,5,false,true);eq(resized.w/resized.h,2);ok(resized.x+resized.w<=1000);const locked={...text,locked:true};eq(editor.applyElementStyle(locked,{fontSize:60},"text"),locked);const styled=editor.applyElementStyle(text,{color:"#ff0000",fontSize:42},"text");ok(JSON.stringify(styled.doc).includes("#ff0000"));eq(p.richTextPlain(styled.doc),p.richTextPlain(text.doc));
 console.log(`✓ ${checks} import checks: editable PPTX/PPSX/POTX, order, images, charts, tables, notes, ODP/OTP, legacy PPT/PPS/POT, JSON, bounds and formatting.`);
}finally{await fs.rm(dir,{recursive:true,force:true});}
async function awaitBytes(zip){return await zip.generateAsync({type:"uint8array"});}
