import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {pathToFileURL} from "node:url";
import {createRequire} from "node:module";
import ts from "typescript";
import JSZip from "jszip";
import {renderToStaticMarkup} from "react-dom/server";
import React from "react";
const temp=await fs.mkdtemp(path.join(os.tmpdir(),"quizedu-presentations-"));let checks=0,mf;
const eq=(a,b,message)=>{assert.deepEqual(a,b,message);checks++;},ok=(v,message)=>{assert.ok(v,message);checks++;},rejects=(op,pattern)=>{assert.throws(op,pattern);checks++;};
try{
 await fs.writeFile(path.join(temp,"package.json"),'{"type":"module"}');
 for(const name of ["quiz","presentation","presentation-flow","presentation-editor","presentation-export"]){let source=await fs.readFile(`lib/${name}.ts`,"utf8");let output=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from "\.\/(quiz|presentation)"/g,'from "./$1.js"').replace('import("pptxgenjs")',`import(${JSON.stringify(import.meta.resolve("pptxgenjs"))})`);await fs.writeFile(path.join(temp,name+".js"),output);}
 const p=await import(pathToFileURL(path.join(temp,"presentation.js"))),geometry=await import(pathToFileURL(path.join(temp,"presentation-editor.js"))),flow=await import(pathToFileURL(path.join(temp,"presentation-flow.js"))),exports=await import(pathToFileURL(path.join(temp,"presentation-export.js"))),quiz=await import(pathToFileURL(path.join(temp,"quiz.js")));
 const {newDeck,newSlide,baseElement,richText,validateDeck,validateRichText,sampleDeck,duplicateDeck,duplicateSlide,SLIDE_LAYOUTS,SLIDE_THEMES,deckQuestions,questionSlide,questionIndexAt,allowedSlide,slideSteps}=p;
 for(const theme of SLIDE_THEMES){for(const layout of SLIDE_LAYOUTS){const deck={...newDeck(),theme:theme.id,slides:[newSlide(layout.id,theme.id)]};eq(validateDeck(deck).slides[0].id,deck.slides[0].id);}}
 const demo=sampleDeck();eq(demo.slides.length,14);eq(deckQuestions(demo).length,6);eq(validateDeck(demo,true).slides.length,14);eq(quiz.quizError(quiz.sampleQuiz()),null);
 eq([...new Set(deckQuestions(demo).map(q=>q.kind))].sort(),["image","multiple","scenario","true_false"]);
 ok(deckQuestions(demo).some(q=>q.options.join("|")==="Sim|Não"));ok(deckQuestions(demo).some(q=>q.optionImages?.every(Boolean)));
 ok(demo.slides.filter(s=>s.kind==="content").every(s=>s.background.image||s.elements.some(e=>e.type==="image"&&e.src)));
 for(const image of quiz.EXAMPLE_IMAGES){ok(quiz.mediaPath(image));ok((await fs.stat("public"+image)).size>1000);}
 for(const image of ["/examples/../../secret.jpg","https://evil.test/examples/solo.jpg","/examples/anything.jpg","/examples/solo.jpg?redirect=1"]){eq(quiz.mediaPath(image),false);}
 // A stable two-round fixture isolates sequencing/scoring tests from demo edits.
 const cover=newSlide("cover","campo");cover.elements[1].doc=richText(demo.title);
 const sample={...newDeck(),title:demo.title,theme:"campo",slides:[cover,newSlide("title","campo"),newSlide("title","campo"),questionSlide(deckQuestions(demo)[0],"campo"),newSlide("title","campo"),newSlide("title","campo"),questionSlide(deckQuestions(demo)[1],"campo"),newSlide("closing","campo")]};
 const cloned=duplicateDeck(sample);ok(cloned.id!==sample.id);ok(cloned.slides.every((s,i)=>s.id!==sample.slides[i].id));eq(cloned.slides.map(s=>s.kind),sample.slides.map(s=>s.kind));ok(deckQuestions(cloned).every((q,i)=>q.id!==deckQuestions(sample)[i].id));validateDeck(cloned,true);checks++;
 const all=newSlide("blank");all.elements=["text","image","shape","table","chart","video"].map(type=>baseElement(type));const complete={...newDeck(),slides:[all]};eq(validateDeck(complete).slides[0].elements.length,6);
 const bad=(change,pattern)=>{const d=structuredClone(complete);change(d);rejects(()=>validateDeck(d),pattern);};
 bad(d=>d.slides[0].elements[0].x=-1,/posição/);bad(d=>d.slides[0].elements[0].w=1001,/posição/);bad(d=>d.slides[0].elements[0].rotation=Infinity,/posição/);bad(d=>d.slides[0].elements[0].opacity=NaN,/posição/);bad(d=>d.slides[0].elements[1].src="javascript:alert(1)",/Imagem/);bad(d=>d.slides[0].elements[1].src="https://images.test/a.jpg",/Imagem/);bad(d=>d.slides[0].elements[4].values=[-1],/gráfico/);bad(d=>d.slides[0].elements[3].cells=[["A","B"],["C"]],/tabela/);bad(d=>d.slides[0].elements[5].videoId='\" onload=\"alert(1)',/YouTube/);bad(d=>d.slides[0].elements[0].id=d.slides[0].id,/única/);bad(d=>d.slides[0].background.color="red;position:absolute",/conteúdo/);bad(d=>d.slides[0].elements[0].build=1.5,/posição/);bad(d=>d.slides[0].elements[0].doc={type:"doc",content:[{type:"script",text:"alert(1)"}]},/formatação/);
 const unsafeLink=richText("link");unsafeLink.content[0].content[0].marks=[{type:"link",attrs:{href:"javascript:alert(1)"}}];rejects(()=>validateRichText(unsafeLink),/links/);rejects(()=>validateRichText(richText("a".repeat(16001))),/16.000/);
 eq(p.safeLink("data:text/html,test"),null);eq(p.safeLink("https://user:password@example.test"),null);eq(p.youtubeId("https://youtu.be/dQw4w9WgXcQ"),"dQw4w9WgXcQ");eq(p.youtubeId("https://youtube.com.evil.test/watch?v=dQw4w9WgXcQ"),null);
 const draft={...newDeck(),slides:[questionSlide(quiz.newQuestion())]};eq(validateDeck(draft).slides[0].question.correct,-1);rejects(()=>validateDeck(draft,true),/enunciado/);rejects(()=>validateDeck({...newDeck(),slides:Array.from({length:151},()=>newSlide())}),/150/);rejects(()=>validateDeck({...sample,slides:Array.from({length:51},()=>duplicateSlide(sample.slides[3]))}),/50 perguntas/);
 const item=baseElement("shape"),secondElement={...baseElement("shape"),x:400,y:200};let moved=geometry.moveElements([item,secondElement],[item.id,secondElement.id],10000,10000);eq(moved[1].x+moved[1].w,1000);eq(moved[1].y+moved[1].h,562.5);eq(moved[1].x-moved[0].x,secondElement.x-item.x);eq(geometry.moveElements([{...item,locked:true}],[item.id],50,50)[0].x,item.x);
 const resized=geometry.resizeElement(item,"nw",10000,10000);eq(resized.w,12);eq(resized.h,8);ok(resized.x>=0&&resized.x+resized.w<=1000);const aligned=geometry.alignElements([item,secondElement],[item.id,secondElement.id],"center");eq(aligned[0].x+aligned[0].w/2,aligned[1].x+aligned[1].w/2);eq(geometry.alignElements([item],[item.id],"middle")[0].y,562.5/2-item.h/2);
 const copies=geometry.cloneElements([{...item,group:item.id},{...secondElement,group:item.id}]);eq(copies[0].group,copies[1].group);ok(copies[0].group!==item.id);ok(copies[0].id!==item.id);
 // Direct editing preserves concurrent slide changes and never alters a locked or unrelated object.
 const editingDeck=newDeck(),editingSlide=editingDeck.slides[0],editingText=editingSlide.elements.find(e=>e.type==="text");
 const beforeText=structuredClone(editingDeck),replacement=richText("Nova explicação\nSegundo parágrafo");
 const edited=geometry.applyTextChange(editingDeck,editingSlide.id,editingText.id,replacement);
 eq(p.richTextPlain(edited.slides[0].elements.find(e=>e.id===editingText.id).doc),"Nova explicação\nSegundo parágrafo");eq(editingDeck,beforeText,"Direct edits do not mutate undo snapshots.");eq(edited.slides[0].elements.filter(e=>e.id!==editingText.id),editingSlide.elements.filter(e=>e.id!==editingText.id));
 const withNotes={...edited,slides:edited.slides.map(s=>({...s,notes:"Notas atualizadas em outro controle"}))};
 eq(geometry.applyTextChange(withNotes,editingSlide.id,editingText.id,richText("Terceiro texto")).slides[0].notes,"Notas atualizadas em outro controle");
 eq(geometry.applyTextChange(edited,crypto.randomUUID(),editingText.id,replacement),edited);eq(geometry.applyTextChange(edited,editingSlide.id,crypto.randomUUID(),replacement),edited);
 const lockedEdit={...edited,slides:edited.slides.map(s=>({...s,elements:s.elements.map(e=>({...e,locked:true}))}))};eq(geometry.applyTextChange(lockedEdit,editingSlide.id,editingText.id,replacement),lockedEdit);
 rejects(()=>geometry.applyTextChange(edited,editingSlide.id,editingText.id,unsafeLink),/links/);
 // Search keeps original slide positions, handles accents and finds nested text, tables and question options.
 const searchDeck={...newDeck(),slides:[newSlide("blank"),questionSlide({...quiz.newQuestion(),text:"Qual a ação?",options:["Água limpa","Solo seco"]}),newSlide("blank")]};
 searchDeck.slides[0].title="Ação e conservação";searchDeck.slides[0].elements=[{...baseElement("text"),doc:{type:"doc",content:[{type:"bulletList",content:[{type:"listItem",content:[{type:"paragraph",content:[{type:"text",text:"Fotossíntese vegetal"}]}]}]}]}}];
 searchDeck.slides[2].title="Dados";searchDeck.slides[2].elements=[{...baseElement("table"),cells:[["Plantio","Safra"],["Feijão","2026"]]}];
 eq(geometry.matchingSlides(searchDeck,""),[0,1,2]);eq(geometry.matchingSlides(searchDeck,"acao conservacao"),[0]);eq(geometry.matchingSlides(searchDeck,"FOTOSSINTESE"),[0]);eq(geometry.matchingSlides(searchDeck,"agua limpa"),[1]);eq(geometry.matchingSlides(searchDeck,"feijao"),[2]);eq(geometry.matchingSlides(searchDeck,"",true),[1]);eq(geometry.matchingSlides(searchDeck,"feijao",true),[]);eq(geometry.matchingSlides(searchDeck,"inexistente"),[]);eq(geometry.matchingSlides(searchDeck,"3"),[2]);
 let progress={status:"lobby",questionIndex:-1,slideIndex:-1,step:0,blackout:false};const advance=()=>progress=flow.movePresentation(sample,progress,progress.status==="lobby"?"start":"next");advance();eq(progress.status,"slide");eq(progress.slideIndex,0);rejects(()=>flow.movePresentation(sample,progress,"goto",4),/próxima pergunta/);advance();advance();advance();eq(progress.status,"question");eq(progress.questionIndex,0);eq(progress.newRound,true);rejects(()=>flow.movePresentation(sample,progress,"next"),/Conclua/);progress=flow.movePresentation(sample,progress,"end_round");advance();eq(progress.slideIndex,4);eq(progress.questionIndex,0);progress=flow.movePresentation(sample,progress,"previous");eq(progress.status,"slide");eq(progress.newRound,false);eq(progress.slideIndex,3);advance();advance();advance();eq(progress.status,"question");eq(progress.questionIndex,1);progress=flow.movePresentation(sample,progress,"end_round");advance();advance();eq(progress.status,"finished");
 const staged=newDeck();staged.slides[0].elements[1].build=2;eq(slideSteps(staged.slides[0]),2);let stagedState=flow.movePresentation(staged,{status:"lobby",questionIndex:-1,slideIndex:-1,step:0,blackout:false},"start");stagedState=flow.movePresentation(staged,stagedState,"next");eq(stagedState.step,1);eq(stagedState.slideIndex,0);stagedState=flow.movePresentation(staged,stagedState,"blackout",undefined,true);eq(stagedState.blackout,true);stagedState=flow.movePresentation(staged,stagedState,"next");eq(stagedState.blackout,false);eq(stagedState.step,2);eq(flow.movePresentation(staged,stagedState,"next").status,"finished");
 // Render the actual canvas without a browser: safe rich text and readable SVG.
 let output=ts.transpileModule(await fs.readFile("app/ui/slide-canvas.tsx","utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace('"@/lib/presentation"','"./presentation.js"');for(const dep of ["react","react/jsx-runtime","lucide-react"])output=output.replaceAll(`"${dep}"`,JSON.stringify(import.meta.resolve(dep)));await fs.writeFile(path.join(temp,"canvas.js"),output);const {SlideCanvas}=await import(pathToFileURL(path.join(temp,"canvas.js")));
 const markup=renderToStaticMarkup(React.createElement(SlideCanvas,{slide:all,theme:"azul",editor:true,selected:[all.elements[0].id]}));ok(markup.includes("aspect-ratio")||markup.includes("slide-frame"));ok(markup.includes("slide-resize-handle"));ok(markup.includes('role="img"'));ok(markup.includes("slide-table"));const hostile={...all,elements:[{...all.elements[0],doc:richText('<script>alert("x")</script>')}]};const safe=renderToStaticMarkup(React.createElement(SlideCanvas,{slide:hostile}));ok(safe.includes("&lt;script&gt;"));ok(!safe.includes("<script>"));
 // A real Office ZIP: native text, shapes, table and editable chart spreadsheet.
 const exportDeck={...sample,slides:[...sample.slides,newSlide("table"),newSlide("chart")]};exportDeck.slides[0].notes="Lembrete privado do professor";const pptx=await exports.buildPowerPoint(exportDeck),buffer=await pptx.write({outputType:"nodebuffer",compression:true}),zip=await JSZip.loadAsync(buffer);eq(Object.keys(zip.files).filter(f=>/^ppt\/slides\/slide\d+\.xml$/.test(f)).length,10);ok(await zip.file("ppt/slides/slide1.xml").async("string").then(s=>s.includes("Solo vivo, turma em ação")));ok(await zip.file("ppt/slides/slide9.xml").async("string").then(s=>s.includes("<a:tbl>")));ok(Object.keys(zip.files).some(f=>f.startsWith("ppt/charts/chart")&&f.endsWith(".xml")));ok(Object.keys(zip.files).some(f=>f.startsWith("ppt/embeddings/")&&f.endsWith(".xlsx")));ok(await zip.file("ppt/notesSlides/notesSlide1.xml").async("string").then(s=>s.includes("Lembrete privado do professor")));const dimensions=await zip.file("ppt/presentation.xml").async("string");ok(dimensions.includes('cx="9144000"')&&dimensions.includes('cy="5143500"'));eq(exports.deckFilename("Aula: conservação / solo"),"Aula-conservacao-solo");
 console.log(`✓ Themes/layouts, rich text safety, bounds, grouping, dragging, resizing, live sequence and real editable PowerPoint. ${checks} checks so far.`);

 // The illustrated demo exports actual embedded JPEGs, including question
 // and alternative images; it never depends on remote image URLs in Office.
 const previousFetch=globalThis.fetch;
 try {
   globalThis.fetch=async(input,init)=>typeof input==="string"&&quiz.EXAMPLE_IMAGES.includes(input)?new Response(await fs.readFile("public"+input),{headers:{"content-type":"image/jpeg"}}):previousFetch(input,init);
   const illustrated=await exports.buildPowerPoint(demo),illustratedZip=await JSZip.loadAsync(await illustrated.write({outputType:"nodebuffer",compression:true}));
   eq(Object.keys(illustratedZip.files).filter(f=>/^ppt\/slides\/slide\d+\.xml$/.test(f)).length,14);
   ok(Object.keys(illustratedZip.files).filter(f=>/^ppt\/media\/.*\.jpeg$/.test(f)||/^ppt\/media\/.*\.jpg$/.test(f)).length>=6);
 } finally {globalThis.fetch=previousFetch;}

 const require=createRequire(import.meta.resolve("wrangler")),{Miniflare}=require("miniflare");const origin="https://quizedu-emanuel.emanuelb5.chatgpt.site";async function walk(dir){const files=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())files.push(...await walk(f));else if(/\.m?js$/.test(f))files.push(f);}return files;}const entry=path.resolve("dist/server/index.js"),modules=[entry,...(await walk(path.resolve("dist/server"))).filter(f=>f!==entry)].map(f=>({type:"ESModule",path:f}));mf=new Miniflare({modules,modulesRoot:path.resolve("dist/server"),compatibilityDate:"2026-05-15",compatibilityFlags:["nodejs_compat"],d1Databases:{DB:"quizedu-presentations-test"},r2Buckets:["BUCKET"]});const database=await mf.getD1Database("DB");for(const name of (await fs.readdir("drizzle")).filter(f=>f.endsWith(".sql")).sort()){for(const statement of (await fs.readFile(`drizzle/${name}`,"utf8")).split("--> statement-breakpoint").map(s=>s.trim()).filter(Boolean))await database.prepare(statement).run();}
 class Client{cookies=new Map();identity=null;async raw(route,body,method,extra={}){return mf.dispatchFetch(origin+route,{method:method||(body===undefined?"GET":"POST"),headers:{cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join("; "),...(body===undefined?{}:{"content-type":"application/json",Origin:origin}),...(this.identity?{"oai-authenticated-user-id":this.identity.id,"oai-authenticated-user-email":this.identity.email,"oai-authenticated-user-full-name":encodeURIComponent(this.identity.name),"oai-authenticated-user-full-name-encoding":"percent-encoded-utf-8"}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body)});}async request(route,body,status=200,method){const r=await this.raw(route,body,method);for(const cookie of r.headers.getSetCookie()){const pair=cookie.split(";")[0],at=pair.indexOf("=");this.cookies.set(pair.slice(0,at),pair.slice(at+1));}const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}eq(r.status,status,`${route}: ${text.slice(0,300)}`);return data;}}
 const host=new Client(),other=new Client(),anonymous=new Client(),alice=new Client(),bob=new Client(),late=new Client();const examples=await anonymous.request("/api/examples");eq(examples.presentation.slides.length,14);eq(examples.quiz.questions.length,6);eq(quiz.quizError(examples.quiz),null);validateDeck(examples.presentation,true);checks++;const secondExamples=await anonymous.request("/api/examples");ok(examples.quiz.id!==secondExamples.quiz.id);ok(examples.presentation.id!==secondExamples.presentation.id);
 const owner=(await host.request("/api/profile",{name:"Professora Clara"},201)).profile;await other.request("/api/profile",{name:"Outro professor"},201);await anonymous.request("/api/presentations",undefined,401);const save=async(deck,revision=0,writeId=crypto.randomUUID())=>(await host.request("/api/presentations",{deck,revision,writeId})).presentation;
 const lesson=duplicateDeck(sample);const correctFirst=lesson.slides[3].question.correct,correctSecond=lesson.slides[6].question.correct;lesson.slides[0].notes="SEGREDO: observações do professor";lesson.slides[1].elements[1].build=1;const writeId=crypto.randomUUID();let record=await save(lesson,0,writeId);eq(record.revision,1);eq((await save(lesson,0,writeId)).revision,1);await host.request("/api/presentations",{deck:lesson,revision:0,writeId:crypto.randomUUID()},409);await other.request(`/api/presentations/${lesson.id}`,undefined,404);await other.request("/api/presentations",{deck:lesson,revision:1,writeId:crypto.randomUUID()},403);eq((await other.request("/api/presentations")).presentations,[]);
 const simultaneous=await Promise.all(["Versão A","Versão B"].map(title=>host.raw("/api/presentations",{deck:{...lesson,title},revision:1,writeId:crypto.randomUUID()})));eq(simultaneous.map(r=>r.status).sort(),[200,409]);for(const r of simultaneous)await r.arrayBuffer();record=(await host.request(`/api/presentations/${lesson.id}`)).presentation;eq(record.revision,2);const list=(await host.request("/api/presentations")).presentations;eq(list[0].slideCount,8);eq(list[0].questionCount,2);ok(!JSON.stringify(list).includes("SEGREDO"));ok(!JSON.stringify(list).includes(lesson.slides[3].question.explanation));
 const large=newDeck();large.slides=Array.from({length:6},()=>{const s=newSlide("blank");s.elements=[{...baseElement("text"),doc:richText("x".repeat(16000))}];return s;});ok(JSON.stringify(large).length>65536);eq((await save(large)).deck.slides.length,6,"Native lesson save accepts bounded documents above legacy quiz body size.");
 const tooBig={...large,id:crypto.randomUUID(),slides:Array.from({length:70},()=>duplicateSlide(large.slides[0]))};await host.request("/api/presentations",{deck:tooBig,revision:0,writeId:crypto.randomUUID()},413);const incomplete={...draft,id:crypto.randomUUID()};await save(incomplete);await host.request("/api/rooms",{presentationId:incomplete.id},400);await other.request("/api/rooms",{presentationId:lesson.id},404);
 const room=await host.request("/api/rooms",{presentationId:lesson.id},201);const route=`/api/rooms/${room.code}`;let state=await host.request(route);eq(state.presentation.index,-1);eq(state.presentation.slide,null);eq(state.status,"lobby");ok(!JSON.stringify(await anonymous.request(route)).includes("SEGREDO"));await alice.request(`${route}/join`,{name:"Alice",avatar:"🦊"},201);await bob.request(`${route}/join`,{name:"Bob",avatar:"🐼"},201);
 const control=(action,extra={},expected=200)=>host.request(`${route}/control`,{action,index:state.index,status:state.status,slideIndex:state.presentation.index,step:state.presentation.step,...extra},expected);
 await host.request(`${route}/control`,{action:"start",status:"lobby",index:-1},409);state=await control("start");eq(state.status,"slide");eq(state.presentation.index,0);eq(state.presentation.slide.notes,lesson.slides[0].notes);let mobile=await alice.request(route);ok(!("notes" in mobile.presentation.slide));ok(!("outline" in mobile.presentation));eq(mobile.question,null);ok(!JSON.stringify(mobile).includes(lesson.slides[3].question.text));await other.request(`${route}/control`,{action:"next",index:-1,status:"slide",slideIndex:0,step:0},403);
 // Opening a room freezes the teaching material, even while the editor changes.
 record=await save({...record.deck,title:"Título alterado depois",slides:record.deck.slides.map((s,i)=>i===0?{...s,title:"Uma capa diferente"}:s)},record.revision);eq((await host.request(route)).presentation.slide.title,lesson.slides[0].title);
 await control("goto",{targetSlide:4},409);await control("goto",{targetSlide:6},409);const old=state;state=await control("next");eq(state.presentation.index,1);eq(state.presentation.step,0);const pulse=await alice.request(`${route}?since=${encodeURIComponent(state.version)}`);eq(pulse.pulse,true);const oldVersion=state.version;state=await control("next");eq(state.presentation.step,1);eq(state.presentation.index,1);ok(state.version!==oldVersion);mobile=await alice.request(`${route}?since=${encodeURIComponent(oldVersion)}`);eq(mobile.presentation.step,1);ok(!mobile.pulse);state=await control("blackout",{blackout:true});eq(state.presentation.blackout,true);eq((await alice.request(route)).presentation.blackout,true);state=await control("blackout",{blackout:false});await late.request(`${route}/join`,{name:"Chegou depois",avatar:"🐝"},201);await late.request(`${route}/heartbeat`,{});eq((await host.request(route)).players.length,3);
 state=await control("next");eq(state.presentation.index,2);state=await control("next");eq(state.status,"question");eq(state.index,0);mobile=await alice.request(route);eq(mobile.correct,null);ok(!("correct" in mobile.question));ok(!("question" in mobile.presentation.slide));ok(!("notes" in mobile.presentation.slide));eq(mobile.question.text,lesson.slides[3].question.text);await control("previous",{},409);await control("blackout",{blackout:true},409);await anonymous.request(`${route}/join`,{name:"Durante a rodada",avatar:"🐸"},409);
 await database.prepare("UPDATE rooms SET starts_at = ?,ends_at = ? WHERE code = ?").bind(Date.now()-1200,Date.now()+28000,room.code).run();await alice.request(`${route}/answer`,{index:0,option:correctFirst});await bob.request(`${route}/answer`,{index:0,option:correctFirst});await late.request(`${route}/answer`,{index:0,option:1});state=await host.request(route);eq(state.status,"results");eq(state.players[0].score,1000);ok(state.players[1].score<=700);const scores=new Map(state.players.map(p=>[p.id,p.score]));state=await control("next");eq(state.status,"slide");eq(state.presentation.index,4);eq(state.question,null);state.players.forEach(p=>eq(p.score,scores.get(p.id),"Scores remain cumulative on instructional slides."));eq((await host.request(`/api/reports/${room.code}`)).completed,1);
 state=await control("previous");eq(state.status,"slide");eq(state.presentation.review,true);eq(state.correct,correctFirst);eq(state.index,0);await late.request(`${route}/answer`,{index:0,option:correctFirst},409);await alice.request(`${route}/answer`,{index:0,option:correctFirst});eq((await database.prepare("SELECT COUNT(*) n FROM answers WHERE room = ?").bind(room.code).first()).n,3);await host.request(`${route}/control`,{action:"next",index:old.index,status:old.status,slideIndex:old.presentation.index,step:old.presentation.step},409);
 state=await control("next");state=await control("next");state=await control("next");eq(state.status,"question");eq(state.index,1);eq(state.presentation.index,6);eq(state.answeredCount,0);await database.prepare("UPDATE rooms SET starts_at = ?,ends_at = ? WHERE code = ?").bind(Date.now()-1000,Date.now()+29000,room.code).run();await late.request(`${route}/answer`,{index:1,option:correctSecond});await alice.request(`${route}/answer`,{index:1,option:correctSecond});state=await host.request(route);state=await control("end_round");eq(state.status,"results");eq(state.players.find(p=>p.name==="Chegou depois").roundPoints,1000);state=await control("next");eq(state.status,"slide");eq(state.presentation.index,7);const finalScores=state.players.map(p=>p.score);state=await control("goto",{targetSlide:3});eq(state.presentation.review,true);eq(state.index,1,"Review never decreases the cumulative question index.");eq(state.players.map(p=>p.score),finalScores);state=await control("goto",{targetSlide:7});state=await control("next");eq(state.status,"finished");eq(state.players.map(p=>p.score),finalScores);const report=await host.request(`/api/reports/${room.code}`);eq(report.completed,2);eq(report.total,2);eq(report.players.map(p=>p.score),finalScores);await other.request(`/api/reports/${room.code}`,undefined,404);
 await host.request(`/api/presentations/${lesson.id}`,{revision:record.revision-1},409,"DELETE");await host.request(`/api/presentations/${lesson.id}`,{revision:record.revision},200,"DELETE");eq((await host.request(`/api/reports/${room.code}`)).completed,2);eq((await alice.request(route)).status,"finished");
 const plain=newDeck();plain.slides[0].elements[1].build=0;await save(plain);const plainRoom=await host.request("/api/rooms",{presentationId:plain.id},201);let plainState=await host.request(`/api/rooms/${plainRoom.code}/control`,{action:"start",status:"lobby",index:-1,slideIndex:-1,step:0});eq(plainState.status,"slide","A teacher may present content before students arrive.");const racePayload={action:"next",status:"slide",index:-1,slideIndex:0,step:0};const race=await Promise.all([host.raw(`/api/rooms/${plainRoom.code}/control`,racePayload),host.raw(`/api/rooms/${plainRoom.code}/control`,racePayload)]);eq(race.map(r=>r.status).sort(),[200,409]);for(const r of race)await r.arrayBuffer();eq((await host.request(`/api/rooms/${plainRoom.code}`)).status,"finished");
 // Permanent-account linking migrates lessons with the other educator assets.
 host.identity={id:"presentation-test-identity",email:"teacher@example.test",name:"Professora Clara"};const linked=await host.request("/api/account/link",{});ok(linked.profile.permanent);ok((await host.request("/api/presentations")).presentations.some(p=>p.id===large.id));eq((await database.prepare("SELECT owner FROM presentations WHERE id = ?").bind(large.id).first()).owner,linked.profile.id);const csrf=await host.raw("/api/presentations",{deck:newDeck(),revision:0,writeId:crypto.randomUUID()},"POST",{Origin:"https://other.test"});eq(csrf.status,403);await csrf.arrayBuffer();
 for(const route of ["/aulas","/aulas/nova",`/aulas/${large.id}`,`/aulas/${large.id}/imprimir`,`/sala/${room.code}/tela`]){const html=await host.request(route);ok(typeof html==="string"&&html.includes("Prativerso"),`${route} renders in the production Worker.`);}
 console.log(`✓ Durable lesson saves, idempotent revisions, ownership, snapshot privacy, staged slides, late joining, scored quiz rounds, safe review, cumulative reports, account migration and production routes. ${checks} total presentation checks passed.`);
}finally{if(mf)await mf.dispose();await fs.rm(temp,{recursive:true,force:true});}
