import type PptxGenJS from "pptxgenjs";
import {RichNode,SlideBackground,SlideDeck,SlideElement,themeFor,validateDeck} from "./presentation";
const inch=(px:number)=>px/100;
const hex=(value:string|undefined,fallback="15203d")=>(value||`#${fallback}`).replace("#","");
export function deckFilename(title:string){return title.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"aula-quizedu";}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function gradientData(background:SlideBackground){const w=1000,h=562.5,r=(background.angle??135)*Math.PI/180,dx=Math.sin(r),dy=-Math.cos(r),extent=Math.abs(w*dx)+Math.abs(h*dy),x1=w/2-dx*extent/2,y1=h/2-dy*extent/2,x2=w/2+dx*extent/2,y2=h/2+dy*extent/2;
  if(typeof document!=="undefined"){const canvas=document.createElement("canvas");canvas.width=w;canvas.height=Math.ceil(h);const context=canvas.getContext("2d");if(!context)throw new Error("Não foi possível preparar o fundo da apresentação.");const gradient=context.createLinearGradient(x1,y1,x2,y2);gradient.addColorStop(0,background.color);gradient.addColorStop(1,background.color2!);context.fillStyle=gradient;context.fillRect(0,0,w,h);return canvas.toDataURL("image/png");}
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="563" viewBox="0 0 1000 562.5"><defs><linearGradient id="g" gradientUnits="userSpaceOnUse" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"><stop stop-color="${background.color}"/><stop offset="1" stop-color="${background.color2}"/></linearGradient></defs><rect width="1000" height="562.5" fill="url(#g)"/></svg>`;return `data:image/svg+xml;base64,${btoa(svg)}`;
}
export function downloadDeck(deck:SlideDeck){const canonical=validateDeck(deck);downloadBlob(new Blob([JSON.stringify({format:"QuizEdu",version:1,deck:canonical},null,2)],{type:"application/json"}),`${deckFilename(deck.title)}.quizedu.json`);}
function textRuns(node:RichNode,e:SlideElement):PptxGenJS.TextProps[] {const runs:PptxGenJS.TextProps[]=[];function read(n:RichNode,parent:PptxGenJS.TextPropsOptions={},bullet=false){if(n.type==="text"){const options:PptxGenJS.TextPropsOptions={...parent};for(const m of n.marks||[]){if(m.type==="bold")options.bold=true;if(m.type==="italic")options.italic=true;if(m.type==="underline")options.underline={style:"sng"};if(m.type==="strike")options.strike=true;if(m.type==="link")options.hyperlink={url:String(m.attrs?.href||"")};if(m.type==="textStyle"){const a=m.attrs||{};if(a.color)options.color=hex(String(a.color));if(a.fontFamily)options.fontFace=String(a.fontFamily);if(a.fontSize)options.fontSize=parseFloat(String(a.fontSize))*.72;}}if(bullet)options.bullet={indent:(e.fontSize||30)*.72};runs.push({text:n.text||"",options});return;}if(n.type==="hardBreak"){runs.push({text:"\n"});return;}const opts={...parent};if(n.type==="heading"){opts.bold=true;opts.fontSize=(e.fontSize||30)*.72*(Number(n.attrs?.level)===1?1.7:1.3);}if(n.attrs?.textAlign)opts.align=n.attrs.textAlign as PptxGenJS.AlignH;const children=n.content||[];children.forEach(c=>read(c,opts,bullet||n.type==="listItem"));if(["paragraph","heading","listItem"].includes(n.type))runs.push({text:"\n"});}read(node);if(runs.at(-1)?.text==="\n")runs.pop();return runs;}
async function imageData(src:string):Promise<string>{const response=await fetch(src);if(!response.ok)throw new Error("Uma imagem não carregou. Confira sua conexão antes de exportar.");const type=response.headers.get("content-type")?.split(";")[0]||"image/jpeg";const data=new Uint8Array(await response.arrayBuffer());let binary="";for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));return `data:${type};base64,${btoa(binary)}`;}
export async function buildPowerPoint(raw:SlideDeck){const deck=validateDeck(raw),{default:Pptx}=await import("pptxgenjs"),pptx=new Pptx();pptx.defineLayout({name:"QUIZEDU",width:10,height:5.625});pptx.layout="QUIZEDU";pptx.author="QuizEdu";pptx.subject=deck.subject;pptx.title=deck.title;pptx.company="QuizEdu";const theme=themeFor(deck.theme);pptx.theme={headFontFace:theme.font,bodyFontFace:theme.font};const images=new Map<string,Promise<string>>();const media=(src:string)=>{if(!images.has(src))images.set(src,imageData(src));return images.get(src)!;};
  for(let i=0;i<deck.slides.length;i++){const source=deck.slides[i],slide=pptx.addSlide();slide.background={color:hex(source.background.color)};if(source.background.color2)slide.addImage({data:gradientData(source.background),x:0,y:0,w:10,h:5.625});if(source.background.image){const data=await media(source.background.image);slide.addImage({data,x:0,y:0,w:10,h:5.625,sizing:{type:"cover",w:10,h:5.625}});if(source.background.overlay)slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:10,h:5.625,line:{transparency:100},fill:{color:"000000",transparency:100-source.background.overlay}});}
    if(source.kind==="question"&&source.question){const q=source.question;slide.addText("PERGUNTA PARA A TURMA",{x:.6,y:.35,w:8.8,h:.3,fontSize:12,bold:true,color:hex(theme.accent)});let y=.9;if(q.image){const data=await media(q.image);slide.addImage({data,x:7.2,y:.8,w:2.2,h:1.5,sizing:{type:"contain",w:2.2,h:1.5}});}slide.addText(q.text||"Pergunta da turma",{x:.6,y,w:q.image?6.4:8.8,h:1.5,fontSize:q.text.length>140?24:32,fontFace:theme.font,bold:true,color:hex(theme.text),margin:0,fit:"shrink"});y=2.6;for(let j=0;j<q.options.length;j++){const x=.6+(j%2)*4.5,oy=y+Math.floor(j/2)*1;slide.addShape(pptx.ShapeType.roundRect,{x,y:oy,w:4.25,h:.83,rectRadius:.1,line:{color:hex(theme.accent),width:1},fill:{color:hex(theme.secondary)}});slide.addText(`${String.fromCharCode(65+j)}  ${q.options[j]}`,{x:x+.12,y:oy+.1,w:q.optionImages?.[j]?3.1:4.01,h:.6,fontFace:theme.font,fontSize:18,color:hex(theme.text),margin:0,fit:"shrink"});if(q.optionImages?.[j]){const data=await media(q.optionImages[j]);slide.addImage({data,x:x+3.35,y:oy+.08,w:.75,h:.66,sizing:{type:"contain",w:.75,h:.66}});}}slide.addText("Respostas e ranking ao vivo na sala QuizEdu",{x:.6,y:5.12,w:8.8,h:.22,fontSize:10,color:hex(theme.muted)});}
    for(const e of source.elements.filter(e=>!e.hidden)){const position={x:inch(e.x),y:inch(e.y),w:inch(e.w),h:inch(e.h),rotate:e.rotation,objectName:e.id};if(e.type==="text")slide.addText(e.doc?textRuns(e.doc,e):"",{...position,fontFace:e.font,fontSize:(e.fontSize||30)*.72,color:hex(e.color),align:e.align,margin:0,breakLine:false,transparency:100-e.opacity,paraSpaceAfter:8,valign:"top",fit:"shrink"});
      if(e.type==="image"&&e.src){const data=await media(e.src);slide.addImage({...position,data,sizing:{type:e.fit==="contain"?"contain":"cover",w:position.w,h:position.h},altText:e.alt,transparency:100-e.opacity});}
      if(e.type==="shape"){const shape=e.shape==="ellipse"?pptx.ShapeType.ellipse:e.shape==="triangle"?pptx.ShapeType.triangle:e.shape==="arrow"?pptx.ShapeType.rightArrow:e.shape==="line"?pptx.ShapeType.line:e.radius?pptx.ShapeType.roundRect:pptx.ShapeType.rect;slide.addShape(shape,{...position,fill:{color:hex(e.fill),transparency:100-e.opacity*(e.fillOpacity??100)/100},line:{color:hex(e.stroke),width:(e.strokeWidth||0)*.72,transparency:e.strokeWidth?100-e.opacity:100}});}
      if(e.type==="table"&&e.cells){const rows:PptxGenJS.TableRow[]=e.cells.map((row,ri)=>row.map(text=>({text,options:ri===0&&e.header?{bold:true,color:"ffffff",fill:{color:hex(e.fill)}}:{color:hex(e.color)}})));slide.addTable(rows,{x:position.x,y:position.y,w:position.w,h:position.h,colW:Array(e.cells[0].length).fill(position.w/e.cells[0].length),rowH:position.h/e.cells.length,fontFace:theme.font,fontSize:(e.fontSize||24)*.72,color:hex(e.color),border:{type:"solid",color:"d5ddeb",pt:1},margin:.05,autoPage:false});}
      if(e.type==="chart")slide.addChart(e.chart==="line"?pptx.ChartType.line:e.chart==="pie"?pptx.ChartType.pie:pptx.ChartType.bar,[{name:source.title,labels:e.labels||[],values:e.values||[]}],{...position,showLegend:e.chart==="pie",showValue:true,showTitle:false,showLabel:e.chart==="pie",chartColors:[hex(e.fill),"168653","d77b08","863de5","d33658","087eaa"],catAxisLabelFontFace:theme.font,catAxisLabelFontSize:12,valAxisLabelFontSize:10,barDir:"col"});
      if(e.type==="video"){slide.addShape(pptx.ShapeType.roundRect,{...position,line:{color:"20304b"},fill:{color:"111c35"}});slide.addText(e.videoId?"▶ Abrir vídeo do YouTube":"Vídeo da aula",{...position,align:"center",valign:"middle",color:"ffffff",fontSize:22,hyperlink:e.videoId?{url:`https://www.youtube.com/watch?v=${e.videoId}&t=${e.videoStart||0}s`}:undefined});}}
    if(deck.showSlideNumbers)slide.addText(String(i+1).padStart(2,"0"),{x:9.2,y:5.2,w:.5,h:.2,align:"right",fontSize:10,color:hex(theme.muted)});const q=source.question;slide.addNotes(`${source.notes}${q?`\n\nResposta correta: ${q.correct>=0?q.options[q.correct]:"Ainda não definida"}\n${q.explanation}`:""}\n\nA participação e a pontuação ao vivo funcionam na sala QuizEdu. Objetos com entrada progressiva são exportados juntos.`);
  }return pptx;
}
export async function downloadPowerPoint(deck:SlideDeck){const pptx=await buildPowerPoint(deck),blob=await pptx.write({outputType:"blob",compression:true});downloadBlob(blob as Blob,`${deckFilename(deck.title)}.pptx`);}
