import {SlideDeck,SlideElement,RichNode,richTextPlain,validateRichText,SLIDE_WIDTH,SLIDE_HEIGHT} from "./presentation";
export function applyTextChange(deck:SlideDeck,slideId:string,elementId:string,doc:RichNode):SlideDeck {
  const slide=deck.slides.find(s=>s.id===slideId),element=slide?.elements.find(e=>e.id===elementId);
  if(!element||element.type!=="text"||element.locked)return deck;
  const clean=validateRichText(doc);
  return {...deck,slides:deck.slides.map(s=>s.id===slideId?{...s,elements:s.elements.map(e=>e.id===elementId?{...e,doc:clean}:e)}:s)};
}
export function matchingSlides(deck:SlideDeck,query:string,questionsOnly=false):number[] {
  const normalize=(text:string)=>text.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR");
  const terms=normalize(query).trim().split(/\s+/).filter(Boolean);
  return deck.slides.flatMap((s,i)=>{
    if(questionsOnly&&s.kind!=="question")return [];
    const content=normalize([String(i+1),s.title,s.question?.text,...(s.question?.options||[]),...s.elements.map(e=>[richTextPlain(e.doc),e.alt,e.cells?.flat().join(" "),e.labels?.join(" ")].filter(Boolean).join(" "))].filter(Boolean).join(" "));
    return terms.every(term=>content.includes(term))?[i]:[];
  });
}
export function boundedElement(element:SlideElement):SlideElement {const w=Math.max(12,Math.min(SLIDE_WIDTH,element.w)),h=Math.max(8,Math.min(SLIDE_HEIGHT,element.h));return {...element,w,h,x:Math.max(0,Math.min(SLIDE_WIDTH-w,element.x)),y:Math.max(0,Math.min(SLIDE_HEIGHT-h,element.y))};}
export function moveElements(elements:SlideElement[],ids:string[],dx:number,dy:number,snap=false):SlideElement[] {const items=elements.filter(e=>ids.includes(e.id)&&!e.locked);if(!items.length)return elements;const left=Math.min(...items.map(e=>e.x)),top=Math.min(...items.map(e=>e.y)),right=Math.max(...items.map(e=>e.x+e.w)),bottom=Math.max(...items.map(e=>e.y+e.h));if(snap){dx=Math.round((left+dx)/5)*5-left;dy=Math.round((top+dy)/5)*5-top;}dx=Math.max(-left,Math.min(SLIDE_WIDTH-right,dx));dy=Math.max(-top,Math.min(SLIDE_HEIGHT-bottom,dy));return elements.map(e=>items.includes(e)?{...e,x:e.x+dx,y:e.y+dy}:e);}
export function resizeElement(e:SlideElement,handle:string,dx:number,dy:number,snap=false,keepAspect=false):SlideElement {const angle=-e.rotation*Math.PI/180;const px=dx*Math.cos(angle)-dy*Math.sin(angle),py=dx*Math.sin(angle)+dy*Math.cos(angle);let x=e.x,y=e.y,w=e.w,h=e.h;if(handle.includes("e"))w=Math.max(12,Math.min(SLIDE_WIDTH-x,w+px));if(handle.includes("s"))h=Math.max(8,Math.min(SLIDE_HEIGHT-y,h+py));if(handle.includes("w")){x=Math.max(0,Math.min(e.x+e.w-12,e.x+px));w=e.x+e.w-x;}if(handle.includes("n")){y=Math.max(0,Math.min(e.y+e.h-8,e.y+py));h=e.y+e.h-y;}if(snap){w=Math.round(w/5)*5;h=Math.round(h/5)*5;}if(keepAspect){const scale=Math.max(12/e.w,8/e.h,Math.abs(w/e.w-1)>Math.abs(h/e.h-1)?w/e.w:h/e.h),anchorX=handle.includes("w")?e.x+e.w:e.x,anchorY=handle.includes("n")?e.y+e.h:e.y;const maxScale=Math.min((handle.includes("w")?anchorX:SLIDE_WIDTH-anchorX)/e.w,(handle.includes("n")?anchorY:SLIDE_HEIGHT-anchorY)/e.h);w=e.w*Math.min(scale,maxScale);h=e.h*Math.min(scale,maxScale);x=handle.includes("w")?anchorX-w:anchorX;y=handle.includes("n")?anchorY-h:anchorY;}return boundedElement({...e,x,y,w,h});}
export function alignElements(elements:SlideElement[],ids:string[],direction:"left"|"center"|"right"|"top"|"middle"|"bottom"):SlideElement[] {const items=elements.filter(e=>ids.includes(e.id)&&!e.locked);if(!items.length)return elements;const multiple=items.length>1,left=multiple?Math.min(...items.map(e=>e.x)):0,top=multiple?Math.min(...items.map(e=>e.y)):0,right=multiple?Math.max(...items.map(e=>e.x+e.w)):SLIDE_WIDTH,bottom=multiple?Math.max(...items.map(e=>e.y+e.h)):SLIDE_HEIGHT;return elements.map(e=>!items.includes(e)?e:boundedElement({...e,x:direction==="left"?left:direction==="center"?(left+right-e.w)/2:direction==="right"?right-e.w:e.x,y:direction==="top"?top:direction==="middle"?(top+bottom-e.h)/2:direction==="bottom"?bottom-e.h:e.y}));}
export function distributeElements(elements:SlideElement[],ids:string[],axis:"x"|"y"):SlideElement[] {const items=elements.filter(e=>ids.includes(e.id)&&!e.locked).sort((a,b)=>a[axis]-b[axis]);if(items.length<3)return elements;const size=axis==="x"?"w":"h",start=items[0][axis],end=items.at(-1)![axis]+items.at(-1)![size],space=(end-start-items.reduce((sum,e)=>sum+e[size],0))/(items.length-1);let current=start;const positions=new Map<string,number>();for(const e of items){positions.set(e.id,current);current+=e[size]+space;}return elements.map(e=>positions.has(e.id)?boundedElement({...e,[axis]:positions.get(e.id)!}):e);}
export function cloneElements(elements:SlideElement[],offset=16):SlideElement[] {const groups=new Map<string,string>();return elements.map(e=>{if(e.group&&!groups.has(e.group))groups.set(e.group,crypto.randomUUID());return boundedElement({...structuredClone(e),id:crypto.randomUUID(),x:e.x+offset,y:e.y+offset,group:e.group?groups.get(e.group):undefined,locked:false});});}
export function elementStyle(e:SlideElement):Partial<SlideElement>{const style:Partial<SlideElement>={};for(const key of ["font","fontSize","color","align","fill","stroke","strokeWidth","fillOpacity","radius","opacity","fit","positionX","positionY","header"] as const)if(e[key]!==undefined)(style as Record<string,unknown>)[key]=structuredClone(e[key]);return style;}
export function applyElementStyle(e:SlideElement,style:Partial<SlideElement>,type:SlideElement["type"]):SlideElement{if(e.locked||e.type!==type)return e;const next={...e,...style};if(e.type==="text"&&e.doc){const doc=structuredClone(e.doc);function write(node:RichNode){if(node.type==="paragraph"||node.type==="heading")node.attrs={...node.attrs,...(style.align?{textAlign:style.align}:{})};for(const mark of node.marks||[])if(mark.type==="textStyle")mark.attrs={...mark.attrs,...(style.color?{color:style.color}:{}),...(style.font?{fontFamily:style.font}:{}),...(style.fontSize?{fontSize:style.fontSize+"px"}:{})};node.content?.forEach(write);}write(doc);next.doc=doc;}return next;}
