import {body,db,educator,HttpError,json} from "./server";
import {SlideDeck,PresentationRecord,PresentationSummary,validateDeck,newSlide,richText} from "./presentation";

type Row={id:string;owner:string;title:string;document:string;revision:number;write_id:string;updated_at:number};
export function presentationRecord(row:Row):PresentationRecord{return {deck:JSON.parse(row.document),revision:row.revision,writeId:row.write_id,updatedAt:row.updated_at};}
export async function listPresentations(request:Request){const user=(await educator(request))!;
  // Fetch only bounded metadata. A library with 200 large lessons must never
  // load 200 full documents or send full presentations just to show the cards.
  const rows=await db().prepare(`SELECT p.id,p.title,p.revision,p.updated_at,json_extract(p.document,'$.theme') theme,json_extract(p.document,'$.subject') subject,json_extract(p.document,'$.topic') topic,json_array_length(p.document,'$.slides') slide_count,(SELECT COUNT(*) FROM json_each(p.document,'$.slides') WHERE json_extract(value,'$.kind') = 'question') question_count,json_extract(p.document,'$.slides[0].title') first_title FROM presentations p WHERE p.owner = ? ORDER BY p.updated_at DESC LIMIT 200`).bind(user.id).all<{id:string;title:string;revision:number;updated_at:number;theme:string;subject:string;topic:string;slide_count:number;question_count:number;first_title:string}>();
  return json({presentations:rows.results.map(row=>{const cover=newSlide("cover",row.theme);cover.title=row.title;cover.elements=cover.elements.map(e=>e.type==="text"?{...e,doc:richText(e.fontSize!>40?row.title:`${row.slide_count} slides · ${row.question_count} perguntas`)}:e);const summary:PresentationSummary={id:row.id,title:row.title,subject:row.subject,topic:row.topic,slideCount:row.slide_count,questionCount:row.question_count,revision:row.revision,updatedAt:row.updated_at,cover,theme:row.theme};return summary;})});
}
export async function readPresentation(request:Request,id:string){const user=(await educator(request))!;const row=await db().prepare("SELECT * FROM presentations WHERE id = ? AND owner = ?").bind(id,user.id).first<Row>();if(!row)throw new HttpError(404,"Esta aula não foi encontrada no seu acesso.");return json({presentation:presentationRecord(row)});}
export async function savePresentation(request:Request){const user=(await educator(request))!;const data=await body(request,1048576);let deck:SlideDeck;try{deck=validateDeck(data.deck);}catch(e){throw new HttpError(400,(e as Error).message);}if(!Number.isInteger(data.revision)||data.revision<0||typeof data.writeId!=="string"||! /^[a-f0-9-]{36}$/.test(data.writeId))throw new HttpError(400,"Atualize a aula antes de salvar.");
  const previous=await db().prepare("SELECT * FROM presentations WHERE id = ?").bind(deck.id).first<Row>();if(previous&&previous.owner!==user.id)throw new HttpError(403,"Esta aula pertence a outro acesso.");if(previous&&previous.write_id===data.writeId)return json({presentation:presentationRecord(previous)});if((previous?.revision||0)!==data.revision)throw new HttpError(409,"Esta aula foi alterada em outra tela. Guarde sua cópia ou abra a versão da conta.");
  if(!previous){const count=await db().prepare("SELECT COUNT(*) n FROM presentations WHERE owner = ?").bind(user.id).first<{n:number}>();const limit=user.auth_id?200:50;if(count!.n>=limit)throw new HttpError(400,`Você pode guardar até ${limit} aulas neste acesso. Exporte uma cópia antes de excluir uma aula antiga.`);}
  const now=Math.max(Date.now(),(previous?.updated_at||0)+1);const result=await db().prepare("INSERT INTO presentations (id,owner,title,document,revision,write_id,created_at,updated_at) VALUES (?,?,?,?,1,?,?,?) ON CONFLICT(id) DO UPDATE SET title = excluded.title, document = excluded.document, revision = presentations.revision + 1, write_id = excluded.write_id, updated_at = excluded.updated_at WHERE presentations.owner = excluded.owner AND presentations.revision = ?").bind(deck.id,user.id,deck.title,JSON.stringify(deck),data.writeId,now,now,data.revision).run();if(!result.meta.changes){const raced=await db().prepare("SELECT * FROM presentations WHERE id = ? AND owner = ?").bind(deck.id,user.id).first<Row>();if(raced&&raced.write_id===data.writeId)return json({presentation:presentationRecord(raced)});throw new HttpError(409,"Outra tela salvou a aula. Sua edição continua nesta tela.");}return json({presentation:{deck,revision:data.revision+1,updatedAt:now,writeId:data.writeId}});
}
export async function deletePresentation(request:Request,id:string){const user=(await educator(request))!;const data=await body(request);if(!Number.isInteger(data.revision))throw new HttpError(400,"Atualize a lista antes de excluir.");const result=await db().prepare("DELETE FROM presentations WHERE id = ? AND owner = ? AND revision = ?").bind(id,user.id,data.revision).run();if(!result.meta.changes)throw new HttpError(409,"A aula mudou ou já foi removida. Atualize a lista.");return json({deleted:true});}
