import {mediaPath,newQuestion,Question,questionIssues,GameMode} from "./quiz";

export const SLIDE_WIDTH=1000,SLIDE_HEIGHT=562.5,MAX_SLIDES=150,MAX_ELEMENTS=60,MAX_LESSON_QUESTIONS=50;
export const FONTS=["Arial","Georgia","Verdana","Trebuchet MS","Times New Roman","Courier New"];
export type RichNode={type:string;text?:string;attrs?:Record<string,unknown>;marks?:{type:string;attrs?:Record<string,unknown>}[];content?:RichNode[]};
export type SlideElement={id:string;type:"text"|"image"|"shape"|"table"|"chart"|"video";x:number;y:number;w:number;h:number;rotation:number;opacity:number;locked:boolean;hidden:boolean;build:number;group?:string;
  doc?:RichNode;font?:string;fontSize?:number;color?:string;align?:"left"|"center"|"right"|"justify";fill?:string;stroke?:string;strokeWidth?:number;fillOpacity?:number;radius?:number;shape?:"rect"|"ellipse"|"line"|"arrow"|"triangle";src?:string;alt?:string;fit?:"cover"|"contain";positionX?:number;positionY?:number;cells?:string[][];header?:boolean;chart?:"bar"|"line"|"pie";labels?:string[];values?:number[];videoId?:string;videoStart?:number};
export type SlideBackground={color:string;color2?:string;angle?:number;image?:string;overlay?:number};
export type LessonSlide={id:string;kind:"content"|"question";title:string;notes:string;background:SlideBackground;transition:"none"|"fade"|"slide";elements:SlideElement[];question?:Question};
export type SlideDeck={id:string;title:string;subject:string;topic:string;theme:string;slides:LessonSlide[];mode:GameMode;untimed:boolean;showSlideNumbers:boolean};
export type PresentationRecord={deck:SlideDeck;revision:number;updatedAt:number;writeId:string};
export type PresentationSummary={id:string;title:string;subject:string;topic:string;slideCount:number;questionCount:number;revision:number;updatedAt:number;cover:LessonSlide;theme:string};
export type PublicSlide=Omit<LessonSlide,"question"|"notes"> & {notes?:string};
export type RoomPresentation={id:string;index:number;total:number;step:number;steps:number;blackout:boolean;slide:PublicSlide|null;questionIndex:number;review:boolean;theme:string;showSlideNumbers:boolean;outline?:{id:string;title:string;kind:LessonSlide["kind"];questionIndex:number}[]};
export const SLIDE_THEMES=[
  {id:"azul",name:"QuizEdu",background:"#ffffff",text:"#15203d",muted:"#61708a",accent:"#3155ed",secondary:"#eaf0ff",font:"Arial"},
  {id:"noite",name:"Noite",background:"#111c35",text:"#ffffff",muted:"#c0cce1",accent:"#d2fb66",secondary:"#20304b",font:"Arial"},
  {id:"campo",name:"Campo",background:"#f6fff8",text:"#123b2c",muted:"#4a7263",accent:"#168653",secondary:"#dcf5e5",font:"Trebuchet MS"},
  {id:"oceano",name:"Oceano",background:"#eefbff",text:"#09354b",muted:"#497486",accent:"#087eaa",secondary:"#cfeef8",font:"Arial"},
  {id:"sol",name:"Sol",background:"#fff9ec",text:"#442c15",muted:"#8a6946",accent:"#d77b08",secondary:"#ffebc6",font:"Georgia"},
  {id:"uva",name:"Uva",background:"#fbf7ff",text:"#33204f",muted:"#78618e",accent:"#863de5",secondary:"#efe0ff",font:"Arial"},
  {id:"papel",name:"Papel",background:"#ffffff",text:"#242424",muted:"#696969",accent:"#1b1b1b",secondary:"#eeeeee",font:"Georgia"},
  {id:"cereja",name:"Cereja",background:"#fff4f5",text:"#481c28",muted:"#88606a",accent:"#d33658",secondary:"#ffe0e7",font:"Verdana"}
];
export const SLIDE_LAYOUTS=[{id:"blank",name:"Em branco"},{id:"cover",name:"Capa"},{id:"title",name:"Título e conteúdo"},{id:"columns",name:"Duas colunas"},{id:"image",name:"Imagem e texto"},{id:"quote",name:"Frase em destaque"},{id:"section",name:"Divisão de assunto"},{id:"comparison",name:"Comparação"},{id:"chart",name:"Gráfico"},{id:"table",name:"Tabela"},{id:"closing",name:"Encerramento"}];
export function themeFor(id:string){return SLIDE_THEMES.find(t=>t.id===id)||SLIDE_THEMES[0];}
export function richText(text:string):RichNode{return {type:"doc",content:text.split("\n").map(line=>({type:"paragraph",content:line?[{type:"text",text:line}]:[]}))};}
export function richTextPlain(node?:RichNode):string {if(!node)return "";if(node.type==="text")return node.text||"";if(node.type==="hardBreak")return "\n";return (node.content||[]).map(richTextPlain).join(["doc","bulletList","orderedList"].includes(node.type)?"\n":"");}
export function color(value:unknown):value is string{return typeof value==="string"&&/^#[\da-f]{6}$/i.test(value);}
export function safeLink(value:unknown):string|null {if(typeof value!=="string"||value.length>1500)return null;try{const url=new URL(value);return ["https:","http:"].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}}
export function youtubeId(value:string):string|null {try{const url=new URL(value);if(!["https:","http:"].includes(url.protocol))return null;const host=url.hostname.replace(/^www\./,"");const id=host==="youtu.be"?url.pathname.slice(1):["youtube.com","youtube-nocookie.com","m.youtube.com"].includes(host)?url.searchParams.get("v")||url.pathname.match(/^\/(?:embed|shorts)\/([\w-]{11})/)?.[1]:null;return id&&/^[\w-]{11}$/.test(id)?id:null;}catch{return null;}}
export function baseElement(type:SlideElement["type"],theme="azul"):SlideElement {const t=themeFor(theme);const base:SlideElement={id:crypto.randomUUID(),type,x:80,y:100,w:480,h:170,rotation:0,opacity:100,locked:false,hidden:false,build:0};
  if(type==="text")return {...base,doc:richText("Digite seu texto"),font:t.font,fontSize:30,color:t.text,align:"left"};
  if(type==="image")return {...base,x:160,y:90,w:600,h:360,src:"",alt:"",fit:"cover",positionX:50,positionY:50,radius:12};
  if(type==="shape")return {...base,w:240,h:150,shape:"rect",fill:t.secondary,stroke:t.accent,strokeWidth:2,radius:12};
  if(type==="table")return {...base,x:80,y:160,w:840,h:290,cells:[["Item","Características","Exemplo"],["Item 1","Descrição","Exemplo 1"],["Item 2","Descrição","Exemplo 2"]],header:true,fontSize:24,color:t.text,fill:t.accent};
  if(type==="chart")return {...base,x:110,y:155,w:780,h:300,chart:"bar",labels:["Grupo A","Grupo B","Grupo C","Grupo D"],values:[30,55,75,45],fill:t.accent,color:t.text,fontSize:20};
  return {...base,x:140,y:105,w:720,h:405,videoId:"",videoStart:0};
}
function textElement(text:string,x:number,y:number,w:number,h:number,size:number,theme:string,accent=false):SlideElement {const t=themeFor(theme);return {...baseElement("text",theme),x,y,w,h,fontSize:size,color:accent?t.accent:t.text,doc:richText(text)};}
export function newSlide(layout="title",theme="azul"):LessonSlide {
  const t=themeFor(theme);const slide:LessonSlide={id:crypto.randomUUID(),kind:"content",title:SLIDE_LAYOUTS.find(l=>l.id===layout)?.name||"Slide",notes:"",background:{color:t.background},transition:"fade",elements:[]};
  const title=(text="Título do slide")=>textElement(text,65,45,865,90,44,theme);
  if(layout==="blank")return slide;
  if(layout==="cover"||layout==="section"||layout==="closing") {slide.elements=[{...baseElement("shape",theme),x:0,y:0,w:18,h:SLIDE_HEIGHT,fill:t.accent,strokeWidth:0,radius:0},textElement(layout==="closing"?"O que aprendemos hoje?":layout==="section"?"Novo assunto":"Título da sua aula",80,145,830,170,62,theme),textElement(layout==="closing"?"Converse com a turma e retome as ideias principais.":"Adicione um subtítulo ou o objetivo da aula.",85,345,800,100,28,theme)];}
  else if(layout==="columns"||layout==="comparison")slide.elements=[title(),{...baseElement("shape",theme),x:65,y:165,w:420,h:315,fill:t.secondary,strokeWidth:0},{...baseElement("shape",theme),x:515,y:165,w:420,h:315,fill:t.secondary,strokeWidth:0},textElement("Primeira ideia",90,190,360,55,30,theme,true),textElement("Explique aqui sua primeira ideia.\n\nUse exemplos que a turma conhece.",90,265,360,180,26,theme),textElement("Segunda ideia",540,190,360,55,30,theme,true),textElement("Explique aqui sua segunda ideia.\n\nCompare e discuta com a turma.",540,265,360,180,26,theme)];
  else if(layout==="image")slide.elements=[title(),textElement("Explique a imagem e destaque o que a turma deve observar.",65,180,380,270,31,theme),{...baseElement("image",theme),x:495,y:160,w:440,h:325}];
  else if(layout==="quote")slide.elements=[textElement("Uma frase para pensar, conversar e aprender juntos.",95,140,810,235,49,theme,true),textElement("Fonte ou autoria",100,400,800,65,24,theme)];
  else if(layout==="chart")slide.elements=[title("Título do gráfico"),baseElement("chart",theme)];
  else if(layout==="table")slide.elements=[title("Título da tabela"),baseElement("table",theme)];
  else slide.elements=[title(),textElement("Apresente a ideia principal.\n\nAcrescente um exemplo.\n\nConvide a turma para observar e conversar.",70,175,850,310,34,theme)];
  return slide;
}
export function questionSlide(question=newQuestion(),theme="azul"):LessonSlide{return {...newSlide("blank",theme),kind:"question",title:question.text.slice(0,60)||"Pergunta para a turma",question};}
export function newDeck():SlideDeck{return {id:crypto.randomUUID(),title:"Minha aula interativa",subject:"",topic:"",theme:"azul",slides:[newSlide("cover")],mode:"speed",untimed:false,showSlideNumbers:true};}
export function duplicateSlide(slide:LessonSlide):LessonSlide {const copy=structuredClone(slide);copy.id=crypto.randomUUID();if(copy.question)copy.question.id=crypto.randomUUID();const groups=new Map<string,string>();copy.elements=copy.elements.map(e=>{if(e.group&&!groups.has(e.group))groups.set(e.group,crypto.randomUUID());return {...e,id:crypto.randomUUID(),...(e.group?{group:groups.get(e.group)}:{})};});return copy;}
export function duplicateDeck(deck:SlideDeck):SlideDeck {return {...structuredClone(deck),id:crypto.randomUUID(),title:`${deck.title.slice(0,90)} · cópia`,slides:deck.slides.map(duplicateSlide)};}
export function deckQuestions(deck:SlideDeck):Question[]{return deck.slides.filter(s=>s.kind==="question").map(s=>s.question!);}
export function questionIndexAt(deck:SlideDeck,index:number):number {return deck.slides.slice(0,index+1).filter(s=>s.kind==="question").length-1;}
export function slideSteps(slide?:LessonSlide|PublicSlide|null):number{return Math.max(0,...(slide?.elements||[]).filter(e=>!e.hidden).map(e=>e.build));}
export function allowedSlide(deck:SlideDeck,target:number,lastQuestion:number):boolean {if(!Number.isInteger(target)||target<0||target>=deck.slides.length)return false;const before=deck.slides.slice(0,target).filter(s=>s.kind==="question").length;return before<=lastQuestion+1&&questionIndexAt(deck,target)<=lastQuestion+1;}
export function changeDeckTheme(deck:SlideDeck,next:string):SlideDeck {const old=themeFor(deck.theme),t=themeFor(next);const swap=(c?:string)=>c===old.text?t.text:c===old.muted?t.muted:c===old.accent?t.accent:c===old.secondary?t.secondary:c===old.background?t.background:c;return {...deck,theme:t.id,slides:deck.slides.map(s=>({...s,background:{...s.background,color:swap(s.background.color)!},elements:s.elements.map(e=>({...e,color:swap(e.color),fill:swap(e.fill),stroke:swap(e.stroke),font:e.font===old.font?t.font:e.font}))}))};}
export function sampleDeck():SlideDeck {const theme="campo";const content=(title:string,text:string)=>{const s=newSlide("title",theme);s.title=title;s.elements[0].doc=richText(title);s.elements[1].doc=richText(text);return s;};const cover=newSlide("cover",theme);cover.title="Solo vivo, turma em ação";cover.elements[1].doc=richText(cover.title);cover.elements[2].doc=richText("Agroecologia · Observe, converse e participe");
  const a={...newQuestion(),text:"Qual prática ajuda a proteger o solo da erosão?",options:["Deixar o solo descoberto","Queimar a vegetação","Manter a cobertura vegetal","Retirar a matéria orgânica"],correct:2,explanation:"A cobertura protege a superfície do solo do impacto da chuva e ajuda a reduzir a erosão."};
  const b={...newQuestion("true_false"),text:"A matéria orgânica ajuda o solo a reter água.",correct:0,explanation:"A matéria orgânica contribui para a estrutura do solo e sua capacidade de reter água."};
  return {...newDeck(),title:cover.title,subject:"Agroecologia",topic:"Conservação do solo",theme,slides:[cover,content("O solo está vivo","Além de minerais, há água, ar, raízes e organismos no solo.\n\nUma boa estrutura permite que raízes cresçam e água infiltre."),content("Cobrir para proteger","Palhada, plantas de cobertura e restos vegetais protegem a superfície.\n\nNa nossa comunidade, onde o solo costuma ficar descoberto?"),questionSlide(a,theme),content("Matéria orgânica faz diferença","Restos vegetais em decomposição alimentam organismos e contribuem para a estrutura do solo.\n\nCobertura do solo e composto são práticas que podemos discutir."),content("Observe antes de decidir","Depois da chuva, observe enxurradas, sulcos e solo descoberto.\n\nCompare dois locais: um coberto e outro descoberto."),questionSlide(b,theme),content("Uma prática para levar à comunidade","Escolha uma prática possível de conservação do solo.\n\nExplique oralmente como ela protege o solo e quais cuidados exige.")]};
}

// Canonical JSON only: rendering never inserts author-provided HTML or CSS.
export function validateRichText(raw:unknown):RichNode {let nodes=0,characters=0;
  function read(value:any,depth:number):RichNode {if(!value||typeof value!=="object"||depth>12||++nodes>1200||!["doc","paragraph","heading","text","hardBreak","bulletList","orderedList","listItem","blockquote","horizontalRule"].includes(value.type))throw new Error("Verifique a formatação do texto.");const out:RichNode={type:value.type};
    if(value.type==="text"){if(typeof value.text!=="string"||(characters+=value.text.length)>16000)throw new Error("Use até 16.000 caracteres por caixa de texto.");out.text=value.text;if(value.marks){if(!Array.isArray(value.marks)||value.marks.length>8)throw new Error("Formatação de texto inválida.");out.marks=value.marks.map((m:any)=>{if(!m||!["bold","italic","underline","strike","code","textStyle","link"].includes(m.type))throw new Error("Formatação de texto inválida.");const mark:{type:string;attrs?:Record<string,unknown>}={type:m.type};if(m.type==="textStyle"){const a=m.attrs||{},attrs:Record<string,unknown>={};for(const k of ["color","backgroundColor"])if(color(a[k]))attrs[k]=a[k];if(FONTS.includes(a.fontFamily))attrs.fontFamily=a.fontFamily;if(typeof a.fontSize==="string"&&/^\d{1,3}(\.\d+)?px$/.test(a.fontSize)&&parseFloat(a.fontSize)>=8&&parseFloat(a.fontSize)<=160)attrs.fontSize=a.fontSize;if(typeof a.lineHeight==="string"&&/^(1|1\.[0-9]+|2|2\.[0-9]+)$/.test(a.lineHeight))attrs.lineHeight=a.lineHeight;mark.attrs=attrs;}if(m.type==="link"){const href=safeLink(m.attrs?.href);if(!href)throw new Error("Use links http ou https válidos.");mark.attrs={href};}return mark;});}}
    else {if(value.content!==undefined){if(!Array.isArray(value.content)||value.content.length>200)throw new Error("Texto inválido.");out.content=value.content.map((n:any)=>read(n,depth+1));}const attrs:Record<string,unknown>={};if(["left","center","right","justify"].includes(value.attrs?.textAlign))attrs.textAlign=value.attrs.textAlign;if(value.type==="heading")attrs.level=Math.min(6,Math.max(1,Math.round(Number(value.attrs?.level)||1)));if(value.type==="orderedList")attrs.start=Math.min(999,Math.max(1,Math.round(Number(value.attrs?.start)||1)));if(Object.keys(attrs).length)out.attrs=attrs;}
    return out;
  }
  const doc=read(raw,0);if(doc.type!=="doc")throw new Error("O texto precisa de um documento válido.");return doc;
}
export function validateDeck(raw:any,strict=false):SlideDeck {
  const fail=(message:string):never=>{throw new Error(message);};const id=(v:unknown)=>typeof v==="string"&&/^[a-f0-9-]{36}$/.test(v);const number=(v:unknown,min:number,max:number)=>typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max;const text=(v:unknown,max:number)=>typeof v==="string"&&v.length<=max;
  if(!raw||!id(raw.id)||!text(raw.title,100)||!raw.title.trim()||!text(raw.subject,60)||!text(raw.topic,60)||!SLIDE_THEMES.some(t=>t.id===raw.theme)||!["speed","accuracy"].includes(raw.mode)||typeof raw.untimed!=="boolean"||(raw.untimed&&raw.mode!=="accuracy")||typeof raw.showSlideNumbers!=="boolean"||!Array.isArray(raw.slides)||raw.slides.length<1||raw.slides.length>MAX_SLIDES)fail("Verifique a aula: título, modo de jogo e até 150 slides.");
  const ids=new Set<string>();const unique=(v:unknown)=>{if(!id(v)||ids.has(v as string))fail("Cada slide e objeto precisa de uma identificação única.");ids.add(v as string);};let questionCount=0;
  const slides:LessonSlide[]=raw.slides.map((s:any,i:number)=>{unique(s?.id);if(!["content","question"].includes(s.kind)||!text(s.title,100)||!text(s.notes,5000)||!["none","fade","slide"].includes(s.transition)||!s.background||!color(s.background.color)||!Array.isArray(s.elements)||s.elements.length>MAX_ELEMENTS)fail(`Slide ${i+1}: verifique o conteúdo e até 60 objetos.`);
    const background:SlideBackground={color:s.background.color};if(s.background.color2!==undefined){if(!color(s.background.color2))fail("Cor do fundo inválida.");background.color2=s.background.color2;}if(s.background.angle!==undefined){if(!number(s.background.angle,0,360))fail("Direção do degradê inválida.");background.angle=s.background.angle;}if(s.background.image){if(!mediaPath(s.background.image))fail("Use uma imagem enviada pelo QuizEdu.");background.image=s.background.image;}if(s.background.overlay!==undefined){if(!number(s.background.overlay,0,90))fail("Escurecimento de fundo inválido.");background.overlay=s.background.overlay;}
    const elements:SlideElement[]=s.elements.map((e:any)=>{unique(e?.id);if(!["text","image","shape","table","chart","video"].includes(e.type)||!number(e.x,0,SLIDE_WIDTH)||!number(e.y,0,SLIDE_HEIGHT)||!number(e.w,12,SLIDE_WIDTH)||!number(e.h,8,SLIDE_HEIGHT)||e.x+e.w>SLIDE_WIDTH+.1||e.y+e.h>SLIDE_HEIGHT+.1||!number(e.rotation,-180,180)||!number(e.opacity,0,100)||typeof e.locked!=="boolean"||typeof e.hidden!=="boolean"||!Number.isInteger(e.build)||e.build<0||e.build>20||(e.group!==undefined&&!id(e.group)))fail(`Slide ${i+1}: posição ou formato de objeto inválido.`);
      const base:SlideElement={id:e.id,type:e.type,x:e.x,y:e.y,w:e.w,h:e.h,rotation:e.rotation,opacity:e.opacity,locked:e.locked,hidden:e.hidden,build:e.build,...(e.group?{group:e.group}:{})};
      for(const key of ["color","fill","stroke"] as const)if(e[key]!==undefined){if(!color(e[key]))fail("Cor de objeto inválida.");base[key]=e[key];}
      if(e.fontSize!==undefined){if(!number(e.fontSize,8,160))fail("Escolha uma fonte de 8 a 160.");base.fontSize=e.fontSize;}
      if(e.fillOpacity!==undefined){if(!number(e.fillOpacity,0,100))fail("Transparência do preenchimento inválida.");base.fillOpacity=e.fillOpacity;}
      if(e.radius!==undefined){if(!number(e.radius,0,100))fail("Cantos de objeto inválidos.");base.radius=e.radius;}
      if(e.type==="text"){if(!FONTS.includes(e.font)||!["left","center","right","justify"].includes(e.align))fail("Fonte ou alinhamento inválido.");base.doc=validateRichText(e.doc);base.font=e.font;base.align=e.align;}
      if(e.type==="shape"){if(!["rect","ellipse","line","arrow","triangle"].includes(e.shape)||!number(e.strokeWidth,0,20))fail("Forma inválida.");base.shape=e.shape;base.strokeWidth=e.strokeWidth;}
      if(e.type==="image"){if((e.src&&!mediaPath(e.src))||!text(e.alt,300)||!["cover","contain"].includes(e.fit)||!number(e.positionX,0,100)||!number(e.positionY,0,100))fail("Imagem inválida.");base.src=e.src||"";base.alt=e.alt;base.fit=e.fit;base.positionX=e.positionX;base.positionY=e.positionY;}
      if(e.type==="table"){if(!Array.isArray(e.cells)||e.cells.length<1||e.cells.length>20||!Array.isArray(e.cells[0])||e.cells[0].length<1||e.cells[0].length>10||e.cells.some((row:any)=>!Array.isArray(row)||row.length!==e.cells[0].length||row.some((cell:any)=>!text(cell,300)))||typeof e.header!=="boolean")fail("A tabela pode ter até 20 linhas e 10 colunas.");base.cells=e.cells.map((row:string[])=>[...row]);base.header=e.header;}
      if(e.type==="chart"){if(!["bar","line","pie"].includes(e.chart)||!Array.isArray(e.labels)||!Array.isArray(e.values)||e.labels.length<1||e.labels.length>12||e.labels.length!==e.values.length||e.labels.some((label:any)=>!text(label,80))||e.values.some((v:any)=>!number(v,0,1000000000)))fail("O gráfico pode ter até 12 valores não negativos.");base.chart=e.chart;base.labels=[...e.labels];base.values=[...e.values];}
      if(e.type==="video"){if(typeof e.videoId!=="string"||(e.videoId&&!/^[\w-]{11}$/.test(e.videoId))||!Number.isInteger(e.videoStart)||e.videoStart<0||e.videoStart>86400)fail("Use um vídeo do YouTube válido.");base.videoId=e.videoId;base.videoStart=e.videoStart;}
      return base;
    });
    const slide:LessonSlide={id:s.id,kind:s.kind,title:s.title,notes:s.notes,transition:s.transition,background,elements};
    if(s.kind==="question"){if(++questionCount>MAX_LESSON_QUESTIONS)fail("Use até 50 perguntas por aula.");const q=s.question;if(!q||!text(q.id,64)||!text(q.text,400)||!text(q.explanation,500)||!Array.isArray(q.options)||q.options.length<2||q.options.length>4||q.options.some((o:any)=>!text(o,180))||!Number.isInteger(q.correct)||q.correct< -1||q.correct>=q.options.length||![10,15,20,30,45,60,90,120].includes(q.seconds)||(q.image&&!mediaPath(q.image))||(q.imageAlt!==undefined&&!text(q.imageAlt,180))||(q.optionImages&&(!Array.isArray(q.optionImages)||q.optionImages.length!==q.options.length||q.optionImages.some((v:any)=>typeof v!=="string"||(v&&!mediaPath(v))))))fail(`Slide ${i+1}: verifique a pergunta.`);if(q.kind!==undefined&&!["multiple","true_false","image","scenario"].includes(q.kind))fail("Modelo da pergunta inválido.");const question:Question={id:q.id,text:q.text,options:[...q.options],correct:q.correct,seconds:q.seconds,explanation:q.explanation,...(q.kind?{kind:q.kind}:{}),...(q.image?{image:q.image,imageAlt:q.imageAlt||""}:{}),...(q.optionImages?{optionImages:[...q.optionImages]}:{})};if(strict){const issue=questionIssues(question).find(issue=>issue.severity==="error");if(issue)fail(`Slide ${i+1}: ${issue.message}`);}slide.question=question;}
    return slide;
  });
  return {id:raw.id,title:raw.title.trim(),subject:raw.subject.trim(),topic:raw.topic.trim(),theme:raw.theme,slides,mode:raw.mode,untimed:raw.untimed,showSlideNumbers:raw.showSlideNumbers};
}
export function deckError(deck:SlideDeck,strict=true):string|null {try{validateDeck(deck,strict);return null;}catch(e){return (e as Error).message;}}
