"use client";
import { useEffect, useRef, useState } from "react";
import { BookOpen, Check, CircleHelp, Clock3, Cloud, Copy, DoorOpen, Edit3, FileText, GraduationCap, History, Loader2, LogOut, MonitorPlay, Play, Plus, QrCode, Search, Share2, ShieldCheck, Sparkles, Trash2, Users, X } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogClose, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Draft, newQuiz, Profile, Question, Quiz } from "@/lib/quiz";
import { api, Brand, Loading, Notifications } from "./shared";
import { draftKey, mergedDrafts, moveLocalDrafts } from "./draft-storage";
import { Editor } from "./editor";
import { QuestionBank } from "./question-bank";

type Room={code:string;title:string;status:string;created_at:number;player_count:number};
type DashboardData={profile:Profile|null;identity:{name:string;email:string}|null;quizzes:Quiz[];rooms:Room[];drafts:Draft[];history:Room[];importAvailable:boolean;temporaryId?:string};
export function Dashboard({signInHref="/signin-with-chatgpt?return_to=%2F%3Fvincular%3D1",signOutHref="/signout-with-chatgpt?return_to=%2F"}:{signInHref?:string;signOutHref?:string}) {
  const [profile,setProfile]=useState<Profile|null>(null);const [identity,setIdentity]=useState<DashboardData["identity"]>(null);const [quizzes,setQuizzes]=useState<Quiz[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [history,setHistory]=useState<Room[]>([]);const [drafts,setDrafts]=useState<Draft[]>([]);const [remoteDrafts,setRemoteDrafts]=useState<Draft[]>([]);const [importAvailable,setImportAvailable]=useState(false);const temporaryId=useRef<string|undefined>(undefined);
  const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [editor,setEditor]=useState<{quiz:Quiz;draft?:Draft;baseSavedAt?:number}|null>(null);const [tab,setTab]=useState("quizzes");const [search,setSearch]=useState("");
  const [profileOpen,setProfileOpen]=useState(false);const [joinOpen,setJoinOpen]=useState(false);const [name,setName]=useState("");const [code,setCode]=useState("");const [busy,setBusy]=useState(false);const [deleting,setDeleting]=useState<Quiz|null>(null);const [deletingDraft,setDeletingDraft]=useState<Draft|null>(null);const [sharing,setSharing]=useState<{quiz:Quiz;url:string}|null>(null);const afterProfile=useRef<(()=>void)|null>(null);
  async function refresh(){const wantsSlides=new URLSearchParams(window.location.search).get("aulas")==="1";try{let data=await api<DashboardData>("/api/dashboard");temporaryId.current=data.temporaryId;
    if(data.identity&&(!data.profile?.permanent||(data.importAvailable&&new URLSearchParams(window.location.search).get("vincular")==="1"))){const from=data.temporaryId||data.profile?.id;const linked=await api<{profile:Profile}>("/api/account/link",{name:data.profile?.name||data.identity.name});if(from)moveLocalDrafts(from,linked.profile.id);data=await api<DashboardData>("/api/dashboard");if(new URLSearchParams(window.location.search).has("vincular"))window.history.replaceState(null,"","/");}
    setProfile(data.profile);setIdentity(data.identity);setQuizzes(data.quizzes);setRooms(data.rooms);setHistory(data.history);setRemoteDrafts(data.drafts);setDrafts(data.profile?mergedDrafts(data.drafts,data.profile.id):[]);setImportAvailable(data.importAvailable);setError("");if(wantsSlides&&data.profile)window.location.replace("/aulas");
  }catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get("aba");if(["quizzes","rascunhos","banco","historico"].includes(value||""))setTab(value!);void refresh();},[]);
  function needProfile(action:()=>void){if(profile)action();else{afterProfile.current=action;setProfileOpen(true);}}
  function create(example=false){needProfile(()=>{if(example)void loadExample();else setEditor({quiz:newQuiz()});});}
  async function loadExample(){setBusy(true);try{const data=await api<{quiz:Quiz}>("/api/examples");setEditor({quiz:data.quiz});}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function register(e:React.FormEvent){e.preventDefault();setBusy(true);try{const data=await api<{profile:Profile}>("/api/profile",{name});setProfile(data.profile);setProfileOpen(false);await refresh();afterProfile.current?.();afterProfile.current=null;}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function importTemporary(){setBusy(true);try{const data=await api<{profile:Profile}>("/api/account/link",{});if(temporaryId.current)moveLocalDrafts(temporaryId.current,data.profile.id);await refresh();toast.success("Seus quizzes e rascunhos foram trazidos para a conta.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function signOut(){setBusy(true);try{await api("/api/logout",{});window.location.assign(identity?signOutHref:"/");}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function openRoom(quiz:Quiz){setBusy(true);try{const room=await api<{code:string}>("/api/rooms",{quizId:quiz.id});window.location.assign(`/sala/${room.code}`);}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function duplicate(quiz:Quiz){setBusy(true);try{await api("/api/quizzes",{...quiz,id:crypto.randomUUID(),title:`${quiz.title.slice(0,90)} · cópia`,questions:quiz.questions.map(q=>({...q,id:crypto.randomUUID()}))});await refresh();toast.success("Cópia criada.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function remove(){if(!deleting)return;setBusy(true);try{await api(`/api/quizzes/${deleting.id}`,{},"DELETE");await refresh();toast.success("Quiz excluído.");setDeleting(null);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function removeDraft(){if(!deletingDraft||!profile)return;setBusy(true);try{const remote=remoteDrafts.find(d=>d.id===deletingDraft.id);if(remote)await api(`/api/drafts/${remote.id}`,{revision:remote.revision},"DELETE");try{localStorage.removeItem(draftKey(profile.id,deletingDraft.id));}catch{}await refresh();setDeletingDraft(null);toast.success("Rascunho excluído.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function share(quiz:Quiz){setBusy(true);try{const data=await api<{path:string}>(`/api/quizzes/${quiz.id}/share`,{});setSharing({quiz,url:window.location.origin+data.path});}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function revokeShare(){if(!sharing)return;setBusy(true);try{await api(`/api/quizzes/${sharing.quiz.id}/share`,{},"DELETE");setSharing(null);toast.success("O link de cópia foi encerrado.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  function build(questions:Question[]){setEditor({quiz:{...newQuiz(),title:"Quiz do meu banco",questions}});}
  const normalize=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const filtered=quizzes.filter(q=>normalize(`${q.title} ${q.subject||""} ${q.topic||""}`).includes(normalize(search)));
  useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const definitions=[{name:"read_my_quizzes",title:"Consultar meus quizzes",description:"Lista os quizzes deste educador.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const data=await api<DashboardData>("/api/dashboard");return {quizzes:data.quizzes.map(q=>({id:q.id,title:q.title,questionCount:q.questions.length}))};}},{name:"start_quiz_creation",title:"Preparar novo quiz",description:"Abre o editor, sem abrir uma sala.",inputSchema:{type:"object",properties:{title:{type:"string",minLength:1,maxLength:100}},required:["title"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!profile)throw new Error("Entre como educador primeiro.");if(typeof input?.title!=="string"||!input.title.trim()||input.title.length>100)throw new Error("Título inválido.");const quiz={...newQuiz(),title:input.title.trim()};setEditor({quiz});return {status:"editor_open",id:quiz.id,title:quiz.title};}}];for(const tool of definitions){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[profile]);
  if(editor&&profile)return <><Editor initial={editor.quiz} ownerKey={profile.id} draft={editor.draft} baseSavedAt={editor.baseSavedAt} onBack={()=>{setEditor(null);void refresh();}} onSaved={()=>void refresh()} onRoom={openRoom}/><Notifications/></>;
  return <div className="app-shell"><header className="topbar"><Brand/><nav className="top-actions"><button className="btn btn-quiet" onClick={()=>setJoinOpen(true)}><QrCode size={18}/>Entrar em uma sala</button><button className="profile-chip" onClick={()=>{afterProfile.current=null;setName(profile?.name||"");setProfileOpen(true);}}><span className="profile-initial">{profile?Array.from(profile.name)[0].toUpperCase():<GraduationCap size={18}/>}</span><span>{profile?.name||"Sou educador"}<small>{profile?.permanent?"Conta permanente":profile?"Acesso temporário":"Entrar ou experimentar"}</small></span></button></nav></header>
    <main className="workspace"><div className="page-heading"><div><p className="eyebrow">ESPAÇO DO EDUCADOR</p><h1>{tab==="quizzes"?"Meus quizzes":tab==="rascunhos"?"Meus rascunhos":tab==="banco"?"Banco de questões":"Histórico das aulas"}<span className="title-dot">.</span></h1><p className="muted">{tab==="quizzes"?"Prepare a atividade e convide sua turma.":tab==="rascunhos"?"Continue de onde parou, mesmo antes de finalizar o quiz.":tab==="banco"?"Guarde boas perguntas e use-as em novas atividades.":"Consulte os resultados e descubra quais assuntos retomar."}</p></div><div className="presentation-dashboard-actions"><button className="btn btn-outline" onClick={()=>needProfile(()=>window.location.assign("/aulas"))}><MonitorPlay size={19}/>Aulas com slides</button><button className="btn btn-primary" onClick={()=>create()}><Plus size={20}/>Criar quiz</button></div></div>
      {error&&<div className="error-panel" role="alert"><p>{error}</p><button className="btn btn-outline" onClick={refresh}>Tentar novamente</button></div>}
      {!loading&&!profile?.permanent&&<div className="account-banner"><ShieldCheck size={24}/><div><b>Leve seus quizzes para o computador e o celular.</b><p>Vincule sua conta para guardar atividades e histórico além do acesso temporário.</p></div><a className="btn btn-primary" href={signInHref} target="_top">Continuar com ChatGPT</a></div>}
      {importAvailable&&<div className="account-banner"><Cloud size={24}/><div><b>Há um acesso temporário neste navegador.</b><p>Traga os quizzes, imagens e rascunhos dele para sua conta permanente.</p></div><button className="btn btn-primary" disabled={busy} onClick={importTemporary}>Trazer minhas atividades</button></div>}
      {rooms.length>0&&<div className="active-rooms">{rooms.map(r=><a href={`/sala/${r.code}`} key={r.code}><span className="live-dot"/><span><b>Sala {r.code}</b> · {r.title}</span><span className="resume">Retomar sala <DoorOpen size={18}/></span></a>)}</div>}
      <Tabs value={tab} onValueChange={v=>needProfile(()=>setTab(v))}><TabsList className="workspace-tabs"><TabsTrigger value="quizzes"><BookOpen size={16}/>Quizzes <span>{quizzes.length}</span></TabsTrigger><TabsTrigger value="rascunhos"><Cloud size={16}/>Rascunhos <span>{drafts.length}</span></TabsTrigger><TabsTrigger value="banco"><CircleHelp size={16}/>Banco de questões</TabsTrigger><TabsTrigger value="historico"><History size={16}/>Minhas aulas <span>{history.length}</span></TabsTrigger></TabsList></Tabs>
      {loading?<Loading label="Carregando suas atividades…"/>:tab==="quizzes"?<div className="dashboard-grid"><section className="quiz-library" aria-label="Seus quizzes">
        {!!quizzes.length&&<div className="search-field quiz-search"><Search size={18}/><input aria-label="Buscar meus quizzes" placeholder="Buscar por título, disciplina ou assunto" value={search} onChange={e=>setSearch(e.target.value)}/></div>}
        <div className="quiz-grid">{filtered.map((quiz,i)=><article className="quiz-card" key={quiz.id}><div className={`quiz-cover cover-${i%3}`}><span className="cover-label">{quiz.mode==="accuracy"?"APRENDIZAGEM":"COMPETIÇÃO AO VIVO"}</span><BookOpen size={52} strokeWidth={1.5}/><span className="cover-number">{String(quiz.questions.length).padStart(2,"0")}</span></div><div className="quiz-card-body"><div className="question-tags">{quiz.subject&&<span>{quiz.subject}</span>}{quiz.topic&&<span>{quiz.topic}</span>}</div><h2>{quiz.title}</h2><p className="quiz-meta"><CircleHelp size={16}/>{quiz.questions.length} {quiz.questions.length===1?"pergunta":"perguntas"}<span>·</span><Clock3 size={16}/>{quiz.untimed?"Tempo livre":`${Math.ceil(quiz.questions.reduce((s,q)=>s+q.seconds,0)/60)} min`}</p><div className="card-primary-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>openRoom(quiz)}><Play size={16} fill="currentColor"/>Abrir sala</button><button className="btn btn-outline" onClick={()=>setEditor({quiz})}><Edit3 size={16}/>Editar</button></div><div className="card-secondary-actions"><button onClick={()=>duplicate(quiz)} disabled={busy}><Copy size={15}/>Duplicar</button><button onClick={()=>share(quiz)} disabled={busy}><Share2 size={15}/>Compartilhar</button><button onClick={()=>setDeleting(quiz)} disabled={busy} aria-label={`Excluir ${quiz.title}`}><Trash2 size={15}/></button></div></div></article>)}<button className="new-quiz-card" onClick={()=>create()}><span className="new-quiz-icon"><Plus size={30}/></span><b>{quizzes.length?"Criar outro quiz":"Seu primeiro quiz"}</b><span>Adicione perguntas, escolha o modo<br/>e convide a turma.</span><span className="small-action">Criar do zero</span></button></div>
        {search&&!filtered.length&&<p className="field-help">Nenhum quiz corresponde à busca.</p>}
        <div className="presentation-dashboard-card"><div><span className="badge badge-lime">NOVO · GRATUITO</span><h2>Uma aula inteira. A turma participando.</h2><p>Crie seus slides, intercale perguntas e apresente com ranking ao vivo.</p></div><button className="btn btn-primary" onClick={()=>needProfile(()=>window.location.assign("/aulas"))}><MonitorPlay size={20}/>Criar aula com slides</button></div>
        <div className="example-card"><img className="example-photo" src="/examples/solo.jpg" alt="Mãos segurando solo escuro"/><div><span className="eyebrow">COMECE COM UM EXEMPLO</span><h2>Solo vivo, turma em ação</h2><p>6 perguntas: múltipla escolha, verdadeiro ou falso, imagens, situação prática e sim ou não.</p></div><button className="btn btn-outline" disabled={busy} onClick={()=>create(true)}>Usar este quiz</button></div>
      </section><aside className="how-card"><span className="badge badge-lime">SUA TURMA NO JOGO</span><h2>Da pergunta<br/>ao jogo<span>.</span></h2><ol className="steps"><li><span>01</span><div><b>Prepare seu quiz</b><p>Escreva perguntas ou escolha do seu banco. O rascunho é salvo automaticamente.</p></div></li><li><span>02</span><div><b>Reúna a turma</b><p>Abra a sala. Cada aluno entra pelo QR code ou pelo código, sem conta.</p></div></li><li><span>03</span><div><b>Jogue e acompanhe</b><p>Conduza as rodadas e consulte o relatório para planejar a próxima aula.</p></div></li></ol><div className="how-footer"><Users size={21}/><span>Até 100 participantes por sala.<br/><b>Você escolhe o ritmo.</b></span></div></aside></div>:!profile?<div className="empty-panel"><GraduationCap size={34}/><h2>Entre como educador</h2><button className="btn btn-primary" onClick={()=>setProfileOpen(true)}>Continuar</button></div>:tab==="banco"?<QuestionBank onBuild={build}/>:tab==="rascunhos"?<div className="draft-grid">{drafts.map(d=><article className="draft-card" key={d.id}><Cloud size={25}/><h2>{d.quiz.title||"Rascunho sem título"}</h2><p className="muted">{d.quiz.questions.length} perguntas · {new Date(d.updatedAt).toLocaleString("pt-BR")}</p><div><button className="btn btn-primary" onClick={()=>setEditor({quiz:d.quiz,draft:remoteDrafts.find(r=>r.id===d.id),baseSavedAt:quizzes.find(q=>q.id===d.id)?.updatedAt})}><Edit3 size={17}/>Continuar</button><button className="btn btn-quiet" aria-label={`Excluir rascunho ${d.quiz.title}`} onClick={()=>setDeletingDraft(d)}><Trash2 size={17}/></button></div></article>)}{!drafts.length&&<div className="empty-panel"><Cloud size={34}/><h2>Nenhum rascunho pendente</h2><p>Ao preparar um quiz, ele aparecerá aqui antes de ser finalizado.</p><button className="btn btn-primary" onClick={()=>create()}>Preparar novo quiz</button></div>}</div>:<div className="history-list">{history.map(r=><article className="history-card" key={r.code}><span className="history-icon"><FileText size={24}/></span><div><h2>{r.title}</h2><p className="muted">{new Date(r.created_at).toLocaleString("pt-BR")} · {r.player_count} participantes · sala {r.code}</p></div><span className="badge badge-blue">{r.status==="finished"?"Concluída":"Encerrada"}</span><a className="btn btn-outline" href={`/relatorio/${r.code}`}>Ver relatório</a></article>)}{!history.length&&<div className="empty-panel"><History size={34}/><h2>Seu histórico começa com a primeira aula</h2><p>As partidas encerradas ficam aqui para você consultar os resultados.</p></div>}</div>}
      <footer className="site-footer"><span>QuizEdu <span>·</span> Feito para aprender juntos</span><span><Check size={15}/>Sem serviços pagos no aplicativo</span></footer>
    </main>
    <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="q-dialog" showCloseButton={false}><DialogClose asChild><button className="dialog-close-button" aria-label="Fechar janela"><X size={20}/></button></DialogClose><DialogTitle className="dialog-title">{profile?"Seu acesso de educador":"Vamos preparar sua aula?"}</DialogTitle><DialogDescription>{profile?.permanent?"Sua conta mantém as atividades entre aparelhos. A recuperação do acesso é feita pela sua conta do ChatGPT.":"Entre com o ChatGPT para manter suas atividades, ou experimente usando apenas seu nome."}</DialogDescription>{!profile?.permanent&&<div className="permanent-entry"><a className="btn btn-primary" href={signInHref} target="_top"><ShieldCheck size={18}/>Continuar com ChatGPT</a><p className="field-help">Usamos a identificação e o nome da conta para guardar suas atividades. Os alunos entram sem login.</p></div>}<form onSubmit={register} className="form-stack"><label htmlFor="teacher-name">Como podemos chamar você?</label><input id="teacher-name" value={name} onChange={e=>setName(e.target.value)} maxLength={30} required minLength={2} placeholder="Ex.: Professor Emanuel"/>{!profile?.permanent&&<p className="field-help">O acesso temporário dura 30 dias neste navegador.</p>}<button className="btn btn-outline" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<GraduationCap size={19}/>} {profile?"Salvar nome":"Experimentar sem cadastro"}</button></form>{profile&&<button className="btn btn-quiet" onClick={signOut} disabled={busy}><LogOut size={17}/>Sair deste acesso</button>}</DialogContent></Dialog>
    <Dialog open={joinOpen} onOpenChange={setJoinOpen}><DialogContent className="q-dialog" showCloseButton={false}><DialogClose asChild><button className="dialog-close-button" aria-label="Fechar janela"><X size={20}/></button></DialogClose><DialogTitle className="dialog-title">Entre no jogo</DialogTitle><DialogDescription>Digite os 6 números da sala do professor.</DialogDescription><form className="form-stack" onSubmit={e=>{e.preventDefault();if(code.length===6)window.location.assign(`/participar/${code}`);}}><label htmlFor="room-code">Código da sala</label><input className="code-input" id="room-code" inputMode="numeric" autoComplete="off" pattern="[0-9]{6}" maxLength={6} placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} required/><button className="btn btn-primary" disabled={code.length!==6}>Entrar na sala</button><a className="btn btn-outline" href="/jogar?trocar=1"><QrCode size={18}/>Abrir app e ler QR code</a></form></DialogContent></Dialog>
    <Dialog open={!!sharing} onOpenChange={v=>{if(!v)setSharing(null);}}><DialogContent className="q-dialog"><DialogTitle>Compartilhar uma cópia</DialogTitle><DialogDescription>Quem receber o link poderá ver as perguntas e copiar o quiz para o próprio acesso. Sua atividade original permanece independente.</DialogDescription>{sharing&&<><h3>{sharing.quiz.title}</h3><label>Link para outros educadores<input value={sharing.url} readOnly onFocus={e=>e.target.select()}/></label><button className="btn btn-primary" onClick={async()=>{try{await navigator.clipboard.writeText(sharing.url);toast.success("Link copiado.");}catch{toast.info("Selecione o link e copie pelo navegador.");}}}><Copy size={17}/>Copiar link</button><button className="btn btn-quiet" disabled={busy} onClick={revokeShare}>Encerrar este compartilhamento</button></>}</DialogContent></Dialog>
    <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v)setDeleting(null);}}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir este quiz?</AlertDialogTitle><AlertDialogDescription>“{deleting?.title}” e seu link de cópia serão removidos. Salas já abertas e relatórios continuam com suas perguntas.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="btn-danger" disabled={busy} onClick={remove}>Excluir quiz</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!deletingDraft} onOpenChange={v=>{if(!v)setDeletingDraft(null);}}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir este rascunho?</AlertDialogTitle><AlertDialogDescription>A versão final do quiz, se já existir, será preservada.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={removeDraft}>Excluir rascunho</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Notifications/>
  </div>;
}
