"use client";
import { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronUp, ChevronDown, Check, Clock3, Copy, Download, Eye, Loader2, Play, Plus, Save, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { api, Brand } from "./shared";
import { DURATIONS, LETTERS, newQuestion, Question, Quiz, quizError } from "@/lib/quiz";

export function Editor({ initial, onBack, onSaved, onRoom }: { initial: Quiz; onBack: () => void; onSaved: () => void; onRoom: (q: Quiz) => Promise<void> }) {
  const [quiz, setQuiz] = useState<Quiz>(() => structuredClone(initial)); const [selected, setSelected] = useState(0); const [saved, setSaved] = useState(JSON.stringify(initial));
  const [busy, setBusy] = useState(false); const [leave, setLeave] = useState(false); const [removeQuestion, setRemoveQuestion] = useState(false); const file = useRef<HTMLInputElement>(null);
  const q = quiz.questions[selected]; const dirty = JSON.stringify(quiz) !== saved || !quiz.updatedAt;
  useEffect(() => { if (!dirty) return; const handler = (e: BeforeUnloadEvent) => { e.preventDefault(); }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  function update(patch: Partial<Question>) { setQuiz(old => ({ ...old, questions: old.questions.map((item, i) => i === selected ? { ...item, ...patch } : item) })); }
  function add() { if (quiz.questions.length >= 50) return; setQuiz({ ...quiz, questions: [...quiz.questions, newQuestion()] }); setSelected(quiz.questions.length); }
  function move(direction: number) { const target = selected + direction; if (target < 0 || target >= quiz.questions.length) return; const questions = [...quiz.questions]; [questions[target], questions[selected]] = [questions[selected], questions[target]]; setQuiz({ ...quiz, questions }); setSelected(target); }
  async function save(start = false) {
    const error = quizError(quiz); if (error) { toast.error(error); return; } setBusy(true);
    try { const data = await api<{ quiz: Quiz }>("/api/quizzes", quiz); setQuiz(data.quiz); setSaved(JSON.stringify(data.quiz)); onSaved(); toast.success("Quiz salvo."); if (start) await onRoom(data.quiz); }
    catch (e) { toast.error((e as Error).message); } finally { setBusy(false); }
  }
  function exportQuiz() { const blob = new Blob([JSON.stringify({ format: "quizedu", version: 1, quiz }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${quiz.title.replace(/[^a-zA-Z0-9À-ÿ_-]/g, "_") || "quiz"}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast.success("Arquivo do quiz exportado."); }
  async function importQuiz(event: React.ChangeEvent<HTMLInputElement>) {
    const uploaded = event.target.files?.[0]; if (!uploaded) return;
    try { if (uploaded.size > 65536) throw new Error("Use um arquivo de até 64 KB."); const raw = JSON.parse(await uploaded.text()); const value = raw.quiz || raw; const error = quizError(value); if (error) throw new Error(error); setQuiz({ ...value, id: quiz.id, updatedAt: undefined }); setSelected(0); toast.success("Perguntas importadas. Salve para guardar o quiz."); }
    catch { toast.error("Arquivo inválido. Escolha um quiz exportado pelo QuizEdu."); } event.target.value = "";
  }
  return <div className="app-shell editor-shell"><header className="topbar"><Brand /><span className="editor-status"><span className={`save-dot ${dirty ? "unsaved" : ""}`} />{dirty ? "Alterações para salvar" : "Quiz salvo"}</span><div className="top-actions"><button className="btn btn-outline" onClick={() => save()} disabled={busy}>{busy ? <Loader2 size={18} className="spin" /> : <Save size={18} />}Salvar quiz</button><button className="btn btn-primary" onClick={() => save(true)} disabled={busy}><Play size={17} fill="currentColor" />Abrir sala</button></div></header>
    <main className="editor-workspace"><button className="back-link" onClick={() => dirty ? setLeave(true) : onBack()}><ChevronLeft size={18} />Meus quizzes</button><div className="editor-title-row"><div><label className="eyebrow" htmlFor="quiz-title">TÍTULO DO QUIZ</label><input id="quiz-title" className="title-input" value={quiz.title} onChange={e => setQuiz({ ...quiz, title: e.target.value })} maxLength={100} placeholder="Dê um nome ao seu quiz" /></div><div className="file-actions"><button className="btn btn-quiet" onClick={exportQuiz}><Download size={17} />Exportar</button><button className="btn btn-quiet" onClick={() => file.current?.click()}><Upload size={17} />Importar</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={importQuiz} /></div></div>
      <div className="editor-grid"><aside className="question-sidebar"><div className="section-label">PERGUNTAS <span>{quiz.questions.length}/50</span></div><div className="question-list">{quiz.questions.map((question, i) => <button key={question.id} className={`question-tab ${selected === i ? "selected" : ""}`} onClick={() => setSelected(i)}><span className="question-index">{i + 1}</span><span>{question.text || "Nova pergunta"}</span>{question.text && <Check size={14} />}</button>)}</div><button className="btn btn-add" onClick={add} disabled={quiz.questions.length >= 50}><Plus size={18} />Adicionar pergunta</button></aside>
        <section className="question-form"><div className="question-form-heading"><h2>Pergunta {selected + 1}</h2><div className="icon-actions"><button aria-label="Mover pergunta para cima" disabled={selected === 0} onClick={() => move(-1)}><ChevronUp size={18} /></button><button aria-label="Mover pergunta para baixo" disabled={selected === quiz.questions.length - 1} onClick={() => move(1)}><ChevronDown size={18} /></button><button aria-label="Duplicar pergunta" disabled={quiz.questions.length >= 50} onClick={() => { const questions = [...quiz.questions]; questions.splice(selected + 1, 0, { ...structuredClone(q), id: crypto.randomUUID() }); setQuiz({ ...quiz, questions }); setSelected(selected + 1); }}><Copy size={17} /></button><button aria-label="Excluir pergunta" disabled={quiz.questions.length === 1} onClick={() => setRemoveQuestion(true)}><Trash2 size={17} /></button></div></div>
          <label htmlFor="question-text">O que você quer perguntar?</label><textarea id="question-text" rows={4} maxLength={400} value={q.text} onChange={e => update({ text: e.target.value })} placeholder="Escreva uma pergunta clara para sua turma…" /><div className="field-counter">{q.text.length}/400</div>
          <div className="alternatives-heading"><label>Alternativas</label><span><Check size={14} />Marque a correta</span></div><RadioGroup value={String(q.correct)} onValueChange={value => update({ correct: Number(value) })} className="alternatives">{q.options.map((option, i) => <div key={i} className={`alternative-field option-${i} ${q.correct === i ? "is-correct" : ""}`}><span className="letter">{LETTERS[i]}</span><input aria-label={`Alternativa ${LETTERS[i]}`} maxLength={180} value={option} onChange={e => { const options = [...q.options]; options[i] = e.target.value; update({ options }); }} placeholder={`Alternativa ${LETTERS[i]}`} /><RadioGroupItem value={String(i)} aria-label={`Marcar alternativa ${LETTERS[i]} como correta`} className="correct-radio" />{q.options.length > 2 && <button className="remove-option" aria-label={`Remover alternativa ${LETTERS[i]}`} onClick={() => update({ options: q.options.filter((_, at) => at !== i), correct: q.correct === i ? 0 : q.correct > i ? q.correct - 1 : q.correct })}>×</button>}</div>)}</RadioGroup>{q.options.length < 4 && <button className="text-button" onClick={() => update({ options: [...q.options, ""] })}><Plus size={15} />Adicionar alternativa</button>}
          <div className="question-settings"><div><label><Clock3 size={17} />Tempo para responder</label><Select value={String(q.seconds)} onValueChange={value => update({ seconds: Number(value) })}><SelectTrigger className="duration-select" aria-label="Tempo para responder"><SelectValue /></SelectTrigger><SelectContent>{DURATIONS.map(s => <SelectItem key={s} value={String(s)}>{s} segundos</SelectItem>)}</SelectContent></Select></div></div>
          <label htmlFor="explanation">Explicação após a rodada <span className="optional">(opcional)</span></label><textarea id="explanation" rows={2} maxLength={500} value={q.explanation} onChange={e => update({ explanation: e.target.value })} placeholder="Uma breve explicação ajuda a turma a aprender com a resposta." />
        </section>
        <aside className="preview-column"><div className="section-label"><Eye size={17} />PRÉVIA DA PERGUNTA</div><div className="question-preview"><span className="preview-kicker">PERGUNTA {selected + 1} DE {quiz.questions.length}</span><span className="preview-timer">{q.seconds}<small>s</small></span><h3>{q.text || "Sua pergunta aparece aqui"}</h3><div className="preview-options">{q.options.map((o, i) => <div className={`answer-option option-${i}`} key={i}><span className="letter">{LETTERS[i]}</span><span>{o || `Alternativa ${LETTERS[i]}`}</span></div>)}</div></div><p className="preview-help">Os alunos verão a pergunta e as alternativas no celular. A resposta correta só aparece ao encerrar a rodada.</p><div className="editor-tip"><b>Uma boa pergunta abre conversa.</b><p>Use o resultado de cada rodada para ouvir a turma antes de continuar.</p></div></aside>
      </div>
    </main>
    <AlertDialog open={leave} onOpenChange={setLeave}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Sair do editor?</AlertDialogTitle><AlertDialogDescription>Há alterações que ainda não foram salvas.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Continuar editando</AlertDialogCancel><AlertDialogAction onClick={onBack}>Sair sem salvar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={removeQuestion} onOpenChange={setRemoveQuestion}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir a pergunta {selected + 1}?</AlertDialogTitle><AlertDialogDescription>Ela será removida deste quiz quando você salvar.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => { setQuiz({ ...quiz, questions: quiz.questions.filter((_, i) => i !== selected) }); setSelected(Math.max(0, selected - 1)); }}>Excluir pergunta</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
