"use client";
import { useEffect, useRef, useState } from "react";
import { BookOpen, Check, ChevronDown, ChevronLeft, ChevronUp, Cloud, Copy, Download, Eye, ListChecks, Loader2, Play, Plus, Rows3, Save, Timer, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Draft, emptyQuestion, LETTERS, newQuestion, Question, QuestionKind, QUESTION_TEMPLATES, questionIssues, Quiz, quizError } from "@/lib/quiz";
import { api, ApiError, Brand } from "./shared";
import { QuestionFields, QuestionPatch } from "./question-fields";
import { QuestionBank } from "./question-bank";
import { draftKey, DraftAttempt, readLocal } from "./draft-storage";
import { QuestionImage, ReadButton } from "./learning-tools";
import { QuestionImportDialog } from "./question-import";
import { QuestionReviewDialog } from "./question-review";
import { QuestionTest } from "./question-test";
import { QuestionTimeDialog } from "./question-time";

export function Editor({initial,ownerKey,draft,baseSavedAt,onBack,onSaved,onRoom}:{initial:Quiz;ownerKey:string;draft?:Draft;baseSavedAt?:number;onBack:()=>void;onSaved:()=>void;onRoom:(q:Quiz)=>Promise<void>}) {
  const [quiz,setQuiz]=useState<Quiz>(()=>structuredClone(initial)); const [selected,setSelected]=useState(0); const [saved,setSaved]=useState(!draft&&initial.updatedAt?JSON.stringify(initial):"");
  const [busy,setBusy]=useState(false);const [leave,setLeave]=useState(false);const [removeQuestion,setRemoveQuestion]=useState(false);const [bankOpen,setBankOpen]=useState(false);const [bankBusy,setBankBusy]=useState(false);
  const [sync,setSync]=useState<"saving"|"synced"|"local"|"conflict">(draft?"synced":"local");const [syncError,setSyncError]=useState("");
  const file=useRef<HTMLInputElement>(null);const latest=useRef(quiz);latest.current=quiz;const revision=useRef(draft?.revision||0);const pending=useRef<DraftAttempt|null>(null);const queue=useRef<Promise<void>>(Promise.resolve());const synced=useRef(draft?JSON.stringify(draft.quiz):"");const mounted=useRef(true);const blocked=useRef(false);const busyRef=useRef(false);const editedAt=useRef(Date.now());const baseUpdatedAt=useRef(baseSavedAt||initial.updatedAt);
  const [importOpen,setImportOpen]=useState(false);const [templateOpen,setTemplateOpen]=useState(false);const [reviewOpen,setReviewOpen]=useState(false);const [timeOpen,setTimeOpen]=useState(false);const [showErrors,setShowErrors]=useState(false);const [testing,setTesting]=useState<Question|null>(null);const [uploads,setUploads]=useState(0);
  const q=quiz.questions[Math.min(selected,quiz.questions.length-1)];const serialized=JSON.stringify(quiz);const dirty=serialized!==saved;
  function writeLocal(){try{localStorage.setItem(draftKey(ownerKey,latest.current.id),JSON.stringify({quiz:latest.current,editedAt:editedAt.current,revision:revision.current,pending:pending.current}));}catch{}}
  useEffect(()=>{mounted.current=true;const local=readLocal(ownerKey,initial.id);if(local){if(local.pending?.writeId===draft?.writeId){pending.current=null;revision.current=draft!.revision;}else{pending.current=local.pending||null;if(!draft||local.editedAt>=draft.updatedAt)revision.current=local.revision;}}return()=>{mounted.current=false;};},[]);
  async function persist(){
    const run=async()=>{
      if(blocked.current)throw new ApiError("Reabra o rascunho para revisar a alteração feita em outra tela.",409);
      if(mounted.current)setSync("saving");
      try{
        // Reuse a write ID when a response was lost; retries cannot create extra revisions.
        if(pending.current){const old=pending.current;const result=await api<{draft:Draft}>("/api/drafts",old);revision.current=result.draft.revision;synced.current=JSON.stringify(old.quiz);pending.current=null;writeLocal();}
        const snapshot=structuredClone(latest.current);const content=JSON.stringify(snapshot);if(new TextEncoder().encode(content).byteLength>64000)throw new ApiError("A atividade está grande demais para sincronizar. Reduza os textos ou divida em dois quizzes. Sua cópia continua neste aparelho.",413);
        if(content!==synced.current){const attempt={quiz:snapshot,revision:revision.current,writeId:crypto.randomUUID()};pending.current=attempt;writeLocal();const result=await api<{draft:Draft}>("/api/drafts",attempt);revision.current=result.draft.revision;synced.current=content;pending.current=null;writeLocal();}
        if(mounted.current){setSync(JSON.stringify(latest.current)===synced.current?"synced":"local");setSyncError("");}
      }catch(e){writeLocal();if(mounted.current){const conflict=e instanceof ApiError&&e.status===409;blocked.current=conflict;setSync(conflict?"conflict":"local");setSyncError((e as Error).message);}throw e;}
    };
    queue.current=queue.current.catch(()=>{}).then(run);return queue.current;
  }
  useEffect(()=>{if(!dirty||busy)return;editedAt.current=Date.now();writeLocal();const timer=setTimeout(()=>void persist().catch(()=>{}),1200);return()=>clearTimeout(timer);},[serialized,busy,dirty]);
  useEffect(()=>{const online=()=>{if(mounted.current&&!busyRef.current)void persist().catch(()=>{});};window.addEventListener("online",online);const retry=setInterval(()=>{if(!blocked.current&&!busyRef.current&&JSON.stringify(latest.current)!==synced.current)void persist().catch(()=>{});},15000);return()=>{window.removeEventListener("online",online);clearInterval(retry);};},[]);
  useEffect(()=>{if(!dirty||sync==="synced")return;const handler=(e:BeforeUnloadEvent)=>{writeLocal();e.preventDefault();};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty,sync]);
  function update(patch:QuestionPatch){const id=q.id;setQuiz(old=>({...old,questions:old.questions.map(item=>item.id===id?{...item,...(typeof patch==="function"?patch(item):patch)}:item)}));}
  function go(index:number,validate=false){setSelected(Math.max(0,Math.min(index,latest.current.questions.length-1)));setShowErrors(validate);if(validate)setTimeout(()=>{const current=latest.current.questions[index];const issue=questionIssues(current).find(i=>i.severity==="error");const id=issue?.field==="options"?`option-${current.id}-${issue.option||0}`:issue?.field==="correct"?`correct-${current.id}-0`:issue?.field==="explanation"?`explanation-${current.id}`:`text-${current.id}`;const input=document.getElementById(id);input?.scrollIntoView({block:"center"});input?.focus();},0);}
  function add(kind?:QuestionKind){if(quiz.questions.length>=50)return;if(!kind){setTemplateOpen(true);return;}const question=newQuestion(kind,{seconds:q.seconds,optionCount:q.options.length});setQuiz(old=>({...old,questions:[...old.questions,question]}));setSelected(quiz.questions.length);setShowErrors(false);setTemplateOpen(false);}
  function completeNext(){const issues=questionIssues(q).filter(i=>i.severity==="error");if(issues.length){setShowErrors(true);go(selected,true);toast.error(issues[0].message);return;}void persist().catch(()=>{});if(selected+1<quiz.questions.length)go(selected+1);else if(quiz.questions.length<50)add(q.kind||"multiple");else toast.success("Esta pergunta está pronta.");}
  function test(){const issue=questionIssues(q).find(i=>i.severity==="error");if(issue){go(selected,true);toast.error(issue.message);return;}setTesting(structuredClone(q));}
  function imported(questions:Question[]):boolean {const current=latest.current;const index=Math.min(selected,current.questions.length-1);const replace=emptyQuestion(current.questions[index]);const list=[...current.questions];list.splice(index+(replace?0:1),replace?1:0,...questions);const next={...current,questions:list};if(list.length>50){toast.error("O limite é de 50 perguntas. Selecione menos perguntas para importar.");return false;}if(new TextEncoder().encode(JSON.stringify(next)).byteLength>64000){toast.error("Esta seleção ficou grande demais. Selecione menos perguntas ou reduza os textos.");return false;}setQuiz(next);setSelected(index+(replace?0:1));setShowErrors(false);toast.success(`${questions.length} perguntas adicionadas ao rascunho.`);return true;}
  function move(direction:number){const target=selected+direction;if(target<0||target>=quiz.questions.length)return;const questions=[...quiz.questions];[questions[target],questions[selected]]=[questions[selected],questions[target]];setQuiz({...quiz,questions});setSelected(target);}
  async function save(start=false){const error=quizError(latest.current);if(error){setReviewOpen(true);setShowErrors(true);toast.error(error);return;}if(uploads){toast.info("Aguarde o envio das imagens antes de salvar.");return;}setBusy(true);busyRef.current=true;try{await persist();const publication=structuredClone(latest.current);const data=await api<{quiz:Quiz}>("/api/quizzes",{...publication,draftRevision:revision.current,baseUpdatedAt:baseUpdatedAt.current});const changed=JSON.stringify(latest.current)!==JSON.stringify(publication);latest.current=changed?{...latest.current,updatedAt:data.quiz.updatedAt}:data.quiz;setQuiz(latest.current);setSaved(JSON.stringify(data.quiz));baseUpdatedAt.current=data.quiz.updatedAt;synced.current=JSON.stringify(data.quiz);revision.current=0;pending.current=null;if(changed)writeLocal();else try{localStorage.removeItem(draftKey(ownerKey,data.quiz.id));}catch{}setSync(changed?"local":"synced");onSaved();toast.success("Quiz salvo.");if(start)await onRoom(data.quiz);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);busyRef.current=false;}}
  async function saveToBank(){const error=quizError({id:quiz.id,title:"Banco",questions:[q]});if(error){toast.error(error);return;}setBankBusy(true);try{await api("/api/questions",{id:q.id,question:q,subject:quiz.subject||"",topic:quiz.topic||""});toast.success("Questão guardada no banco.");}catch(e){toast.error((e as Error).message);}finally{setBankBusy(false);}}
  function exportQuiz(){const blob=new Blob([JSON.stringify({format:"quizedu",version:2,quiz:latest.current},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${quiz.title.replace(/[^a-zA-Z0-9À-ÿ_-]/g,"_")||"quiz"}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function importQuiz(event:React.ChangeEvent<HTMLInputElement>){const uploaded=event.target.files?.[0];if(!uploaded)return;try{if(uploaded.size>65536)throw new Error("Use um arquivo de até 64 KB.");const raw=JSON.parse(await uploaded.text());const value=raw.quiz||raw;const error=quizError(value);if(error)throw new Error(error);setQuiz({...value,id:quiz.id,updatedAt:baseUpdatedAt.current,questions:value.questions.map((question:Question)=>({...question,id:crypto.randomUUID()}))});setSelected(0);setShowErrors(false);toast.success("Perguntas importadas.");}catch(e){toast.error((e as Error).message||"Arquivo inválido.");}event.target.value="";}
  function choose(question:Question){if(quiz.questions.length>=50){toast.error("O limite é de 50 perguntas.");return;}if(quiz.questions.length===1&&emptyQuestion(q)){setQuiz({...quiz,questions:[question]});setSelected(0);}else{setQuiz({...quiz,questions:[...quiz.questions,question]});setSelected(quiz.questions.length);}setBankOpen(false);}
  async function recoverCopy(){const oldId=latest.current.id;const copy:Quiz={...structuredClone(latest.current),id:crypto.randomUUID(),title:`${latest.current.title||"Quiz"} (cópia)`.slice(0,100),updatedAt:undefined};busyRef.current=true;setBusy(true);blocked.current=false;pending.current=null;revision.current=0;baseUpdatedAt.current=undefined;synced.current="";latest.current=copy;editedAt.current=Date.now();setQuiz(copy);setSaved("");writeLocal();try{await persist();try{localStorage.removeItem(draftKey(ownerKey,oldId));}catch{}onSaved();toast.success("Sua cópia foi guardada como um novo rascunho.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);busyRef.current=false;}}
  async function back(){if(dirty){try{await persist();onBack();}catch{setLeave(true);}}else onBack();}
  const reviews=quiz.questions.map(questionIssues);const ready=reviews.filter(items=>!items.some(i=>i.severity==="error")).length;const qReady=!reviews[Math.min(selected,quiz.questions.length-1)].some(i=>i.severity==="error");const replaceEmpty=emptyQuestion(q);const remaining=50-quiz.questions.length+(replaceEmpty?1:0);
  return <div className="app-shell editor-shell"><header className="topbar"><Brand/><span className={`editor-status sync-${sync}`} role="status">{sync==="saving"?<Loader2 size={16} className="spin"/>:<Cloud size={16}/>} {uploads?`Preparando ${uploads} imagem(ns)…`:sync==="saving"?"Salvando rascunho…":sync==="synced"?(dirty?"Rascunho salvo":"Quiz salvo"):sync==="conflict"?"Outra tela alterou o rascunho":"Cópia neste aparelho"}</span><div className="top-actions"><button className="btn btn-outline" onClick={()=>save()} disabled={busy||!!uploads}>{busy?<Loader2 size={18} className="spin"/>:<Save size={18}/>}Salvar quiz</button><button className="btn btn-primary" onClick={()=>save(true)} disabled={busy||!!uploads}><Play size={17} fill="currentColor"/>Abrir sala</button></div></header>
    <main className="editor-workspace"><button className="back-link" onClick={back} disabled={busy||!!uploads}><ChevronLeft size={18}/>Meus quizzes</button>{syncError&&<div className="draft-recovery" role="status"><p>{syncError} {sync==="conflict"?"Você pode guardar seu trabalho como outro rascunho ou exportar uma cópia.":"Sua cópia continua guardada neste aparelho enquanto você edita."}</p>{sync==="conflict"&&<button className="btn btn-outline" onClick={exportQuiz}>Exportar minha cópia</button>}<button className="btn btn-outline" disabled={busy} onClick={sync==="conflict"?()=>void recoverCopy():()=>void persist().catch(()=>{})}>{sync==="conflict"?"Salvar como novo rascunho":"Sincronizar agora"}</button></div>}
      <div className="editor-title-row"><div><label className="eyebrow" htmlFor="quiz-title">TÍTULO DO QUIZ</label><input id="quiz-title" className="title-input" value={quiz.title} disabled={busy} onChange={e=>setQuiz({...quiz,title:e.target.value})} maxLength={100} placeholder="Dê um nome ao seu quiz"/></div><div className="file-actions"><button className="btn btn-quiet" onClick={exportQuiz}><Download size={17}/>Exportar cópia</button><button className="btn btn-quiet" disabled={busy||!!uploads} onClick={()=>file.current?.click()}><Upload size={17}/>Importar cópia</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={importQuiz}/></div></div>
      <div className="authoring-toolbar"><span className="authoring-progress"><Check size={17}/>{ready}/{quiz.questions.length} prontas</span><div><button className="btn btn-outline" onClick={()=>setImportOpen(true)} disabled={busy||!!uploads||remaining<1}><Rows3 size={17}/>Adicionar em lote</button><button className="btn btn-outline" onClick={()=>setTimeOpen(true)} disabled={busy}><Timer size={17}/>Ajustar tempos</button><button className="btn btn-outline" onClick={()=>setReviewOpen(true)} disabled={busy}><ListChecks size={17}/>Revisar quiz</button></div></div>
      <details className="quiz-settings"><summary><b>Configurações da atividade</b><span>{quiz.mode==="accuracy"?"Aprendizagem":"Competição"}{quiz.untimed?" · tempo livre":""}{quiz.subject?` · ${quiz.subject}`:""}</span></summary><fieldset disabled={busy} className="quiz-configuration"><div className="metadata-fields"><label>Disciplina<input maxLength={60} value={quiz.subject||""} onChange={e=>setQuiz({...quiz,subject:e.target.value})} placeholder="Ex.: Agroecologia"/></label><label>Assunto<input maxLength={60} value={quiz.topic||""} onChange={e=>setQuiz({...quiz,topic:e.target.value})} placeholder="Ex.: Proteção do solo"/></label></div><div className="mode-configuration"><label>Como a turma vai jogar?</label><RadioGroup value={quiz.mode||"speed"} onValueChange={mode=>setQuiz({...quiz,mode:mode as Quiz["mode"],untimed:mode==="accuracy"?quiz.untimed:false})} className="mode-choices"><label className={quiz.mode!=="accuracy"?"mode-selected":""}><RadioGroupItem value="speed"/><span><b>Competição</b><small>Acerto + rapidez · até 1.000 pontos</small></span></label><label className={quiz.mode==="accuracy"?"mode-selected":""}><RadioGroupItem value="accuracy"/><span><b>Aprendizagem</b><small>1.000 pontos por acerto · sem bônus de rapidez</small></span></label></RadioGroup>{quiz.mode==="accuracy"&&<label className="untimed-choice"><Switch checked={!!quiz.untimed} onCheckedChange={untimed=>setQuiz({...quiz,untimed})} aria-label="Responder sem cronômetro"/><span>Tempo livre para responder</span></label>}</div></fieldset></details>
      <div className="editor-grid"><aside className="question-sidebar"><div className="section-label">PERGUNTAS <span>{quiz.questions.length}/50</span></div><div className="question-list">{quiz.questions.map((question,i)=>{const complete=!reviews[i].some(issue=>issue.severity==="error");return <button key={question.id} disabled={busy} className={`question-tab ${selected===i?"selected":""}`} aria-current={selected===i?"step":undefined} onClick={()=>go(i)}><span className="question-index">{i+1}</span><span className="question-tab-content"><span>{question.text||"Nova pergunta"}</span><small className={complete?"question-ready":"question-incomplete"}>{complete?"Pronta":"Completar"}</small></span>{complete&&<Check size={14}/>}</button>;})}</div><button className="btn btn-add" onClick={()=>add()} disabled={busy||quiz.questions.length>=50}><Plus size={18}/>Adicionar pergunta</button><button className="btn btn-outline bank-picker-button" onClick={()=>setBankOpen(true)} disabled={busy||!!uploads||(quiz.questions.length>=50&&!replaceEmpty)}><BookOpen size={17}/>Do meu banco</button></aside>
        <section className="question-form"><div className="question-form-heading"><h2>Pergunta {selected+1}</h2><div className="icon-actions"><button aria-label="Mover pergunta para cima" disabled={busy||selected===0} onClick={()=>move(-1)}><ChevronUp size={18}/></button><button aria-label="Mover pergunta para baixo" disabled={busy||selected===quiz.questions.length-1} onClick={()=>move(1)}><ChevronDown size={18}/></button><button aria-label="Duplicar pergunta" disabled={busy||!!uploads||quiz.questions.length>=50} onClick={()=>{const questions=[...quiz.questions];questions.splice(selected+1,0,{...structuredClone(q),id:crypto.randomUUID()});setQuiz({...quiz,questions});setSelected(selected+1);setShowErrors(false);}}><Copy size={17}/></button><button aria-label="Excluir pergunta" disabled={busy||!!uploads||quiz.questions.length===1} onClick={()=>setRemoveQuestion(true)}><Trash2 size={17}/></button></div></div><fieldset disabled={busy} className="question-fieldset"><QuestionFields key={q.id} q={q} onChange={update} untimed={!!quiz.untimed} showErrors={showErrors} onUploadChange={uploading=>setUploads(n=>Math.max(0,n+(uploading?1:-1)))}/></fieldset><div className="question-utility-actions"><button className="btn btn-outline save-bank-button" disabled={busy||bankBusy||!!uploads} onClick={saveToBank}>{bankBusy?<Loader2 size={17} className="spin"/>:<BookOpen size={17}/>}Guardar no banco</button><button className="btn btn-outline" onClick={test} disabled={busy||!!uploads}><Eye size={17}/>Testar como aluno</button></div>
          <div className="authoring-actions"><button className="btn btn-quiet authoring-previous" disabled={busy||selected===0} onClick={()=>go(selected-1)}>Anterior</button><span className="authoring-step">{selected+1}/{quiz.questions.length}</span><button className="btn btn-outline authoring-mobile-save" onClick={()=>save()} disabled={busy||!!uploads}>Salvar quiz</button><button className="btn btn-primary" onClick={completeNext} disabled={busy||!!uploads}>{selected+1<quiz.questions.length?"Concluir e próxima":quiz.questions.length<50?"Concluir e adicionar":"Concluir pergunta"}</button></div>
        </section>
        <aside className="preview-column"><div className="section-label"><Eye size={17}/>PRÉVIA DA PERGUNTA</div><div className="question-preview"><span className="preview-kicker">PERGUNTA {selected+1} DE {quiz.questions.length}</span><span className="preview-timer">{quiz.untimed?"∞":q.seconds}<small>{quiz.untimed?"livre":"s"}</small></span><h3>{q.text||"Sua pergunta aparece aqui"}</h3><QuestionImage url={q.image} alt={q.imageAlt}/><div className="preview-options">{q.options.map((o,i)=><div className={`answer-option option-${i}`} key={i}><span className="letter">{LETTERS[i]}</span><span>{q.optionImages?.[i]&&<img src={q.optionImages[i]} alt={o||`Alternativa ${LETTERS[i]}`} className="option-image"/>}{o||`Alternativa ${LETTERS[i]}`}</span></div>)}</div><ReadButton text={`${q.text}. ${q.options.map((o,i)=>`${LETTERS[i]}: ${o}`).join(". ")}`}/></div><button className="btn btn-outline preview-test-button" onClick={test} disabled={busy||!!uploads}><Eye size={17}/>Testar celular e telão</button><p className="preview-help">{qReady?"Campos obrigatórios preenchidos. Confira o gabarito antes de jogar.":"Complete o enunciado, as alternativas e a resposta correta para testar."}</p><div className="editor-tip"><b>Seu trabalho continua aqui.</b><p>O rascunho é guardado automaticamente. Use “Salvar quiz” para deixar a atividade pronta para jogar.</p></div></aside>
      </div>
    </main>
    {importOpen&&<QuestionImportDialog remaining={remaining} defaultSeconds={q.seconds} replaceEmpty={replaceEmpty} onImport={imported} onClose={()=>setImportOpen(false)}/>}
    {timeOpen&&<QuestionTimeDialog questions={quiz.questions} untimed={!!quiz.untimed} onClose={()=>setTimeOpen(false)} onApply={(ids,seconds)=>{setQuiz(old=>({...old,questions:old.questions.map(item=>ids.includes(item.id)?{...item,seconds}:item)}));toast.success("Tempos atualizados.");}}/>}
    {reviewOpen&&<QuestionReviewDialog quiz={quiz} onClose={()=>setReviewOpen(false)} onGo={index=>{setReviewOpen(false);go(index,true);}}/>}
    {testing&&<QuestionTest question={testing} mode={quiz.mode||"speed"} untimed={!!quiz.untimed} onClose={()=>setTesting(null)}/>}
    <Dialog open={templateOpen} onOpenChange={setTemplateOpen}><DialogContent className="q-dialog template-dialog"><DialogTitle>Que pergunta você quer criar?</DialogTitle><DialogDescription>A próxima pergunta usará {q.seconds} segundos.{quiz.untimed&&" O tempo livre continua ativado."}</DialogDescription><div className="template-picker">{QUESTION_TEMPLATES.map(template=><button key={template.kind} onClick={()=>add(template.kind)}><b>{template.label}</b><span>{template.description}</span></button>)}</div></DialogContent></Dialog>
    <Dialog open={bankOpen} onOpenChange={setBankOpen}><DialogContent className="q-dialog bank-picker-dialog"><DialogTitle>Escolher do meu banco</DialogTitle><DialogDescription>Adicionar uma questão cria uma cópia independente neste quiz.</DialogDescription><QuestionBank onChoose={question=>{if(emptyQuestion(q)){setQuiz(old=>({...old,questions:old.questions.map(item=>item.id===q.id?question:item)}));setBankOpen(false);setShowErrors(false);}else choose(question);}}/></DialogContent></Dialog>
    <AlertDialog open={leave} onOpenChange={setLeave}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Voltar aos meus quizzes?</AlertDialogTitle><AlertDialogDescription>O rascunho ainda não foi sincronizado. Sua cópia fica neste aparelho para continuar depois.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Continuar editando</AlertDialogCancel><AlertDialogAction onClick={()=>{writeLocal();onBack();}}>Voltar com cópia local</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={removeQuestion} onOpenChange={setRemoveQuestion}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir a pergunta {selected+1}?</AlertDialogTitle><AlertDialogDescription>Ela será removida deste rascunho.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{setQuiz({...quiz,questions:quiz.questions.filter((_,i)=>i!==selected)});setSelected(Math.max(0,selected-1));setShowErrors(false);}}>Excluir pergunta</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
