"use client";
import { useEffect, useState } from "react";
import { Check, ChevronLeft, Download, Printer, Users } from "lucide-react";
import { LessonReport, LETTERS, points } from "@/lib/quiz";
import { api, Brand, Loading } from "./shared";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export function LessonReportView({code}:{code:string}) {
  const [report,setReport]=useState<LessonReport|null>(null);const [error,setError]=useState("");
  async function load(){try{setReport(await api<LessonReport>(`/api/reports/${code}`));setError("");}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load();},[code]);
  return <div className="app-shell report-shell"><header className="topbar"><Brand/><a className="btn btn-outline" href="/?aba=historico"><ChevronLeft size={17}/>Minhas aulas</a></header><main className="workspace report-workspace">
    {error?<div className="error-panel"><p>{error}</p><button className="btn btn-outline" onClick={load}>Tentar novamente</button></div>:!report?<Loading label="Preparando o relatório da aula…"/>:<>
      <div className="page-heading"><div><p className="eyebrow">RELATÓRIO DA AULA · SALA {report.code}</p><h1>{report.title}</h1><p className="muted">{report.teacher} · {new Date(report.createdAt).toLocaleString("pt-BR")} · {report.mode==="accuracy"?"Aprendizagem":"Competição"}{report.untimed?" · tempo livre":""}</p></div><div className="report-actions"><a className="btn btn-outline" href={`/api/reports/${code}/csv`}><Download size={17}/>Planilha CSV</a><button className="btn btn-primary" onClick={()=>window.print()}><Printer size={17}/>Imprimir / salvar PDF</button></div></div>
      <div className="report-summary"><article><Users size={22}/><strong>{report.players.length}</strong><span>participantes</span></article><article><Check size={22}/><strong>{report.accuracy}%</strong><span>de acertos da turma</span></article><article><strong>{report.completed}/{report.total}</strong><span>perguntas concluídas</span></article></div>
      {!report.completed&&<div className="empty-panel"><h2>As primeiras respostas ainda estão chegando</h2><p>O relatório mostra apenas rodadas encerradas.</p></div>}
      {!!report.completed&&<><section className="report-section"><h2>Desempenho por participante</h2><div className="report-table"><Table><TableHeader><TableRow><TableHead>Posição</TableHead><TableHead>Participante</TableHead><TableHead>Pontos</TableHead><TableHead>Acertos</TableHead><TableHead>Erros</TableHead><TableHead>Sem resposta</TableHead><TableHead>Aproveitamento</TableHead></TableRow></TableHeader><TableBody>{report.players.map(p=><TableRow key={p.id}><TableCell>{p.position}º</TableCell><TableCell><span className="report-avatar">{p.avatar}</span>{p.name}</TableCell><TableCell>{points(p.score)}</TableCell><TableCell>{p.correctCount}</TableCell><TableCell>{p.answeredCount-p.correctCount}</TableCell><TableCell>{report.completed-p.answeredCount}</TableCell><TableCell>{Math.round(p.correctCount/report.completed*100)}%</TableCell></TableRow>)}</TableBody></Table></div></section>
      <section className="report-section"><h2>O que a turma compreendeu?</h2><p className="muted">O percentual inclui todos os participantes, inclusive quem não respondeu.</p><div className="report-questions">{report.questions.map((q,i)=><article className={`report-question ${q.accuracy<50?"review-question":""}`} key={q.question.id}><div className="report-question-heading"><span>Pergunta {i+1}</span><b>{q.accuracy}% de acertos</b></div><h3>{q.question.text}</h3>{q.question.image&&<img src={q.question.image} alt={q.question.imageAlt||"Imagem da pergunta"} className="report-image"/>}<div className="choice-distribution">{q.question.options.map((o,at)=><div className={`distribution-row ${at===q.question.correct?"distribution-correct":""}`} key={at}><div><span>{LETTERS[at]} · {o}</span><b>{q.choices[at]} {at===q.question.correct&&<Check size={15}/>}</b></div><span className="distribution-track"><span style={{width:`${report.players.length?q.choices[at]/report.players.length*100:0}%`}}/></span></div>)}</div><p className="muted">{q.correct} acertaram · {q.answered-q.correct} erraram · {report.players.length-q.answered} não responderam</p>{q.question.explanation&&<p className="report-explanation">{q.question.explanation}</p>}{q.accuracy<50&&<span className="review-label">Sugestão: retomar este assunto com a turma.</span>}</article>)}</div></section>
      <section className="report-section report-response-section"><h2>Respostas de cada participante</h2><div className="report-table"><Table><TableHeader><TableRow><TableHead>Participante</TableHead>{report.questions.map((_,i)=><TableHead key={i}>P{i+1}</TableHead>)}</TableRow></TableHeader><TableBody>{report.players.map(p=><TableRow key={p.id}><TableCell>{p.name}</TableCell>{p.answers.map((a,i)=><TableCell key={i}><span className={`answer-cell ${a?.correct?"cell-right":a?"cell-wrong":"cell-empty"}`}>{a?`${LETTERS[a.option]} ${a.correct?"✓":"×"}`:"—"}</span></TableCell>)}</TableRow>)}</TableBody></Table></div><p className="field-help">✓ acerto · × erro · — sem resposta. A planilha contém as respostas e os tempos completos.</p></section></>}
    </>}
  </main></div>;
}
