"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,MonitorSmartphone,ShieldCheck} from "lucide-react";
import {Brand} from "./shared";
export function NativePairing({id,signInHref}:{id:string;signInHref:string}){
 const [info,setInfo]=useState<any>(null),[account,setAccount]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[importTemporary,setImport]=useState(true);
 useEffect(()=>{let active=true;(async()=>{try{if(!id)throw new Error("Inicie o vínculo pelo aplicativo QuizEdu no Android.");const [a,b]=await Promise.all([fetch(`/api/native/requests/${id}`,{cache:"no-store"}),fetch("/api/dashboard",{cache:"no-store"})]);const i=await a.json() as any,p=await b.json() as any;if(!a.ok)throw new Error(i.error);if(active){setInfo(i);setAccount(p);setDone(i.approved);}}catch(e){if(active)setError((e as Error).message);}})();return()=>{active=false;};},[id]);
 async function approve(){setBusy(true);setError("");try{const r=await fetch("/api/native/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,importTemporary})}),data=await r.json() as any;if(!r.ok)throw new Error(data.error);setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="native-pair-page"><Brand/><section className="native-pair-card"><div className="native-pair-icon">{done?<CheckCircle2/>:<MonitorSmartphone/>}</div><p className="eyebrow">QUIZEDU NO ANDROID</p><h1>{done?"Aparelho vinculado!":"Sua aula, nos dois dispositivos."}</h1>{done?<><p>Volte ao aplicativo. Suas aulas e salas já podem ser acessadas pelo celular.</p><a className="btn btn-primary" href="/aulas">Minhas aulas</a></>:<><p>Autorize o aplicativo para editar suas aulas e controlar a apresentação no computador.</p>{info&&<div className="native-pair-device"><b>{info.deviceName}</b><span>Autorize somente o aparelho em que você iniciou este vínculo.</span></div>}{account?.identity||account?.profile?<><p>Vincular como <b>{account.identity?.name||account.profile?.name}</b>{account.identity?.email&&<small style={{display:"block"}}>{account.identity.email}</small>}</p>{info?.hasTemporaryLessons&&<label className="native-pair-import"><input type="checkbox" checked={importTemporary} onChange={e=>setImport(e.target.checked)}/> Trazer as aulas temporárias deste aparelho para esta conta</label>}<button className="btn btn-primary" onClick={approve} disabled={busy||!info}>{busy?"Vinculando…":"Vincular este Android"}</button>{!account.identity&&<a className="btn btn-quiet" href={signInHref} target="_top">Usar minha conta do ChatGPT</a>}</>:info?<a className="btn btn-primary" href={signInHref} target="_top">Entrar com ChatGPT e vincular</a>:!error?<p>Carregando o vínculo…</p>:null}<p className="native-pair-note"><ShieldCheck size={18}/> O aplicativo não recebe a senha da sua conta. Você pode revogar o acesso em “Aparelhos” no aplicativo.</p></>}{error&&<p role="alert" className="native-pair-error">{error}</p>}</section></main>;
}
