"use client";
import { useState } from "react";
import { Check, Clock3, Crown, Home, Loader2, Trophy, Users, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Progress } from "@/components/ui/progress";
import { AVATARS, LETTERS, points } from "@/lib/quiz";
import { api, Brand, Loading, Notifications, Offline, useClock } from "./shared";
import { Podium, Ranking, useRoom } from "./room-shared";

export function PlayerRoom({ code }: { code: string }) {
  const { state, error, refresh, apply } = useRoom(code); const [name, setName] = useState(""); const [avatar, setAvatar] = useState(AVATARS[0]); const [busy, setBusy] = useState(false); const [joinError, setJoinError] = useState("");
  const seconds = useClock(state?.serverNow || 0, state?.endsAt || null); const countdown = useClock(state?.serverNow || 0, state?.startsAt || null);
  async function join(e: React.FormEvent) { e.preventDefault(); setBusy(true); setJoinError(""); try { await api(`/api/rooms/${code}/join`, { name, avatar }); await refresh(); } catch (e) { setJoinError((e as Error).message); } finally { setBusy(false); } }
  async function respond(option: number) { if (!state?.me || state.me.answered || busy || !seconds || countdown > 0 || error) return; setBusy(true); try { await api(`/api/rooms/${code}/answer`, { index: state.index, option }); apply({ ...state, me: { ...state.me, answered: true, option } }); await refresh(); } catch (e) { toast.error((e as Error).message); await refresh().catch(() => {}); } finally { setBusy(false); } }
  if (!state) return <div className="player-shell"><header className="player-topbar"><Brand /></header>{error ? <main className="player-error"><h1>Vamos encontrar a sala</h1><p>{error}</p><button className="btn btn-primary" onClick={() => refresh()}>Tentar novamente</button><a href="/" className="back-link">Voltar ao início</a></main> : <Loading label="Encontrando sua sala…" />}</div>;
  const me = state.me; const final = state.status === "finished"; const closed = state.status === "closed";
  return <div className={`player-shell ${final ? "player-final" : ""}`}><header className="player-topbar"><Brand /><span className="player-room-code">SALA <b>{code}</b></span></header>{error && <Offline text="Reconectando… Aguarde a conexão para responder." />}
    {!me && !closed && !final && <main className="join-workspace"><span className="badge badge-blue">{state.status === "lobby" ? "A TURMA ESTÁ CHEGANDO" : "QUIZ EM ANDAMENTO"}</span><h1>Você também<br />entra no jogo<span>!</span></h1><p className="join-quiz-title">{state.title}<span>com {state.teacher}</span></p>{state.status === "lobby" ? <form className="join-form" onSubmit={join}><label htmlFor="player-name">Seu nome ou apelido</label><input id="player-name" value={name} onChange={e => setName(e.target.value)} placeholder="Como a turma conhece você?" minLength={2} maxLength={24} required autoComplete="nickname" /><label>Escolha seu avatar</label><RadioGroup value={avatar} onValueChange={setAvatar} className="avatar-grid" aria-label="Escolha seu avatar">{AVATARS.map((a, i) => <label className={`avatar-choice ${avatar === a ? "avatar-selected" : ""}`} key={a}><RadioGroupItem className="sr-only" value={a} aria-label={`Avatar ${["raposa", "panda", "sapo", "leão", "tigre", "coala", "pinguim", "coruja", "abelha", "borboleta", "tartaruga", "polvo"][i]}`} /><span aria-hidden="true">{a}</span>{avatar === a && <Check size={13} />}</label>)}</RadioGroup>{joinError && <p className="form-error" role="alert">{joinError}</p>}<button className="btn btn-primary join-button" disabled={busy}>{busy ? <Loader2 className="spin" size={20} /> : <Zap size={20} fill="currentColor" />}Entrar na sala</button><p className="join-note">Sem senha, sem cadastro. Só você e sua turma.</p></form> : <div className="join-unavailable"><Clock3 size={28} /><p>Esta partida já começou. Peça ao professor para convidar você na próxima sala.</p><a href="/" className="btn btn-outline">Voltar ao início</a></div>}</main>}
    {me && state.status === "lobby" && <main className="player-waiting"><span className="waiting-avatar">{me.avatar}<span><Check size={18} /></span></span><span className="badge badge-blue">VOCÊ ESTÁ NA SALA</span><h1>Boa, {me.name}!</h1><p>Agora é com {state.teacher}.<br />O quiz vai aparecer aqui quando começar.</p><div className="waiting-quiz"><span className="waiting-pulse" /><b>{state.title}</b><span><Users size={16} />{state.players.length} na sala</span></div><div className="mini-avatar-cloud">{state.players.slice(0, 12).map(p => <span key={p.id} title={p.name}>{p.avatar}</span>)}</div><div className="player-instruction"><Zap size={20} /><p>Acertar vale pontos.<br /><b>Acertar mais rápido vale ainda mais.</b></p></div><p className="muted">Mantenha esta página aberta.</p></main>}
    {me && state.status === "question" && state.question && <main className="player-live"><div className="player-score-row"><span>PERGUNTA {state.index + 1}/{state.total}</span><span>{me.avatar} {points(me.score)} pts</span></div>{countdown > 0 ? <div className="player-countdown"><span>Prepare-se!</span><strong key={countdown}>{countdown}</strong><p>A próxima pergunta está chegando.</p></div> : <><div className={`player-timer ${seconds <= 5 ? "timer-urgent" : ""}`}><Clock3 size={19} /><b>{seconds}s</b><Progress value={Math.min(100, seconds / state.question.seconds * 100)} aria-label="Tempo restante" /></div><h1>{state.question.text}</h1>{me.answered ? <div className="answer-sent"><span className="answer-sent-icon"><Check size={35} /></span><h2>Resposta enviada!</h2><p>{me.option !== null ? `Você escolheu ${LETTERS[me.option]}: ${state.question.options[me.option]}` : "Sua resposta foi registrada."}</p><span>Aguarde o resultado da rodada.</span></div> : <div className="player-options">{state.question.options.map((option, i) => <button className={`answer-option option-${i}`} key={i} disabled={busy || !seconds || !!error} onClick={() => respond(i)}><span className="letter">{LETTERS[i]}</span><span>{option}</span>{busy && <Loader2 size={16} className="spin" />}</button>)}</div>}{!me.answered && <p className="player-answer-note">{seconds ? "Toque na alternativa. Sua resposta é enviada na hora." : "Tempo encerrado. Aguarde o placar."}</p>}</>}</main>}
    {me && state.status === "results" && state.question && <main className="player-results"><span className={`result-icon ${me.roundCorrect ? "result-success" : "result-neutral"}`}>{me.roundCorrect ? <Check size={34} /> : <X size={34} />}</span><h1>{me.roundCorrect ? "Mandou bem!" : me.answered ? "Valeu a tentativa!" : "O tempo passou!"}</h1><p className="player-round-points">+{points(me.roundPoints)}<span>pontos nesta rodada</span></p><div className="player-correct-answer"><span>RESPOSTA CORRETA</span><b>{state.question.options[state.correct!]}</b>{state.explanation && <p>{state.explanation}</p>}</div><div className="my-ranking"><span><Trophy size={21} /><b>{me.position}º lugar</b></span><b>{points(me.score)}<small>pontos no total</small></b></div><h2 className="player-ranking-heading">Placar da turma</h2><Ranking players={state.players} me={me.id} /><p className="next-waiting"><Clock3 size={16} />Aguarde o professor continuar.</p></main>}
    {final && <main className="player-final-workspace"><span className="badge badge-blue">QUIZ CONCLUÍDO</span><h1>Aprendemos juntos<span>!</span></h1>{me && <div className="player-final-score"><span>{me.avatar}</span><div><b>{me.position}º lugar · {me.name}</b><p>{points(me.score)} pontos · {me.correctCount} acertos</p></div></div>}<Podium players={state.players} />{state.players.length > 2 && <Ranking players={state.players.slice(2)} me={me?.id} final />}<a href="/" className="btn btn-primary"><Home size={18} />Voltar ao início</a></main>}
    {closed && <main className="player-error"><Trophy size={42} /><h1>Sala encerrada</h1><p>Obrigado por participar! Peça ao professor o código da próxima sala.</p><a href="/" className="btn btn-primary">Voltar ao início</a></main>}
    <Notifications />
  </div>;
}
