"use client";
import { useEffect, useRef, useState } from "react";
import { Check, Clock3, Home, Loader2, Trophy, Users, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Progress } from "@/components/ui/progress";
import { AVATARS, LETTERS, points } from "@/lib/quiz";
import { api, ApiError, Brand, Loading, Notifications, Offline, useClock } from "./shared";
import { Podium, Ranking, useRoom } from "./room-shared";
import { ConnectionCheck, useGamePreferences } from "./learning-tools";
import { AnswerOptions, QuestionHeading } from "./question-view";
import { leaveActiveRoom, saveActiveRoom } from "@/lib/player-app";
import { AppInstallButton, AppInstallCard, ExitRoomButton, usePlayerManifest } from "./player-app";

type PendingAnswer={meId:string;index:number;option:number};
export function PlayerRoom({code}:{code:string}) {
  const {state,error,refresh}=useRoom(code);const [name,setName]=useState("");const [avatar,setAvatar]=useState(AVATARS[0]);const [busy,setBusy]=useState(false);const [joinError,setJoinError]=useState("");const [pending,setPending]=useState<PendingAnswer|null>(null);const [retryMessage,setRetryMessage]=useState("");const inFlight=useRef(false);const pendingRef=useRef<PendingAnswer|null>(null);pendingRef.current=pending;const preferences=useGamePreferences();const phase=useRef("");const current=useRef(state);current.current=state;const pendingKey=`qe_answer_${code}`;
  const leaving=useRef(false);
  usePlayerManifest(code,state?.me?.id);
  useEffect(()=>{if(!state||leaving.current)return;try{if(state.status==="closed")leaveActiveRoom(localStorage,code);else if(state.me||state.status==="lobby")saveActiveRoom(localStorage,state);}catch{}},[code,state?.me?.id,state?.status,state?.expiresAt,state?.title]);
  function exit(){leaving.current=true;try{leaveActiveRoom(localStorage,code);}catch{}}
  const seconds=useClock(state?.serverNow||0,state?.endsAt||null);const countdown=useClock(state?.serverNow||0,state?.startsAt||null);
  function clearPending(){setPending(null);pendingRef.current=null;setRetryMessage("");try{localStorage.removeItem(pendingKey);sessionStorage.removeItem(pendingKey);}catch{}}
  useEffect(()=>{if(!state?.me)return;if(state.status!=="question"||state.me.answered){clearPending();return;}try{const value=JSON.parse(localStorage.getItem(pendingKey)||sessionStorage.getItem(pendingKey)||"null");if(value&&value.meId===state.me.id&&value.index===state.index&&Number.isInteger(value.option)&&value.option>=0&&value.option<4)setPending(value);}catch{}},[state?.me?.id,state?.index,state?.status,state?.me?.answered]);
  useEffect(()=>{if(!state?.me||!["lobby","question","results"].includes(state.status))return;const beat=()=>{if(!document.hidden)void api(`/api/rooms/${code}/heartbeat`,{}).catch(()=>{});};beat();const timer=setInterval(beat,20000);window.addEventListener("online",beat);document.addEventListener("visibilitychange",beat);return()=>{clearInterval(timer);window.removeEventListener("online",beat);document.removeEventListener("visibilitychange",beat);};},[code,state?.me?.id,state?.status]);
  useEffect(()=>{if(!state)return;const key=`${state.status}:${state.index}`;if(phase.current&&phase.current!==key){if(state.status==="results"&&state.me?.roundCorrect)preferences.tone();if(state.status==="finished")preferences.tone(true);}phase.current=key;},[state?.status,state?.index]);
  async function transmit(item:PendingAnswer){
    if(inFlight.current)return;const latest=current.current;if(!latest?.me||latest.me.id!==item.meId||latest.index!==item.index||latest.status!=="question"){clearPending();return;}
    inFlight.current=true;
    try{await api(`/api/rooms/${code}/answer`,{index:item.index,option:item.option});clearPending();await refresh();}
    catch(e){if(e instanceof ApiError&&(e.status===0||e.status>=500)){setRetryMessage("Tentando confirmar no servidor. Mantenha a página aberta.");void refresh().catch(()=>{});}else{clearPending();toast.info((e as Error).message);void refresh().catch(()=>{});}}
    finally{inFlight.current=false;}
  }
  useEffect(()=>{if(!pending)return;void transmit(pending);const retry=()=>{const item=pendingRef.current;if(item)void transmit(item);};const timer=setInterval(retry,1800);window.addEventListener("online",retry);return()=>{clearInterval(timer);window.removeEventListener("online",retry);};},[pending?.meId,pending?.index,pending?.option]);
  async function join(e:React.FormEvent){e.preventDefault();setBusy(true);setJoinError("");try{await api(`/api/rooms/${code}/join`,{name,avatar});await refresh();}catch(e){setJoinError((e as Error).message);}finally{setBusy(false);}}
  function respond(option:number){if(!state?.me||state.me.answered||pending||busy||(!state.untimed&&!seconds)||countdown>0||error)return;const item={meId:state.me.id,index:state.index,option};try{localStorage.setItem(pendingKey,JSON.stringify(item));}catch{}setPending(item);pendingRef.current=item;void transmit(item);}
  if(!state)return <div className="player-shell"><header className="player-topbar"><Brand href="/jogar"/></header>{error?<main className="player-error"><h1>Vamos encontrar a sala</h1><p>{error}</p><button className="btn btn-primary" onClick={()=>refresh()}>Tentar novamente</button><a href="/jogar?trocar=1" className="back-link" onClick={exit}>Entrar em outra sala</a></main>:<Loading label="Encontrando sua sala…"/>}</div>;
  const me=state.me;const final=state.status==="finished",closed=state.status==="closed";
  return <div className={`player-shell ${final?"player-final":""}`} style={{"--read-scale":preferences.scale} as React.CSSProperties}><header className="player-topbar"><Brand href="/jogar"/><div className="player-room-actions"><span className="player-room-code">SALA <b>{code}</b></span>{me&&state.status!=="lobby"&&<AppInstallButton compact/>}<ExitRoomButton code={code} onExit={exit}/></div></header>{error&&<Offline text="Reconectando… Aguarde a conexão para responder."/>}
    {!closed&&(!me||state.status==="lobby")&&<div className="player-install-wrap"><AppInstallCard/></div>}
    {me&&!closed&&!final&&<div className="player-preferences">{preferences.controls}</div>}
    {!me&&!closed&&!final&&<main className="join-workspace"><span className="badge badge-blue">{state.status==="lobby"?"A TURMA ESTÁ CHEGANDO":"QUIZ EM ANDAMENTO"}</span><h1>Você também<br/>entra no jogo<span>!</span></h1><p className="join-quiz-title">{state.title}<span>com {state.teacher}</span></p>{state.status==="lobby"?<form className="join-form" onSubmit={join}><label htmlFor="player-name">Seu nome ou apelido</label><input id="player-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Como a turma conhece você?" minLength={2} maxLength={24} required autoComplete="nickname"/><label>Escolha seu avatar</label><RadioGroup value={avatar} onValueChange={setAvatar} className="avatar-grid" aria-label="Escolha seu avatar">{AVATARS.map((a,i)=><label className={`avatar-choice ${avatar===a?"avatar-selected":""}`} key={a}><RadioGroupItem className="sr-only" value={a} aria-label={`Avatar ${["raposa","panda","sapo","leão","tigre","coala","pinguim","coruja","abelha","borboleta","tartaruga","polvo"][i]}`}/><span aria-hidden="true">{a}</span>{avatar===a&&<Check size={13}/>}</label>)}</RadioGroup>{joinError&&<p className="form-error" role="alert">{joinError}</p>}<button className="btn btn-primary join-button" disabled={busy}>{busy?<Loader2 className="spin" size={20}/>:<Zap size={20} fill="currentColor"/>}Entrar na sala</button><p className="join-note">Sem senha, sem cadastro. Só você e sua turma.</p></form>:<div className="join-unavailable"><Clock3 size={28}/><p>Esta partida já começou. Peça ao professor para convidar você na próxima sala.</p><a href="/jogar?trocar=1" className="btn btn-outline" onClick={exit}>Entrar em outra sala</a></div>}</main>}
    {me&&state.status==="lobby"&&<main className="player-waiting"><span className="waiting-avatar">{me.avatar}<span><Check size={18}/></span></span><span className="badge badge-blue">VOCÊ ESTÁ NA SALA</span><h1>Boa, {me.name}!</h1><p>Agora é com {state.teacher}.<br/>O quiz vai aparecer aqui quando começar.</p><div className="waiting-quiz"><span className="waiting-pulse"/><b>{state.title}</b><span><Users size={16}/>{state.players.length} na sala</span></div><div className="mini-avatar-cloud">{state.players.slice(0,12).map(p=><span key={p.id} title={p.name}>{p.avatar}</span>)}</div><div className="player-instruction"><Zap size={20}/><p>{state.mode==="accuracy"?<>Cada acerto vale <b>1.000 pontos.</b><br/>{state.untimed?"Responda no seu tempo.":"A rapidez não altera a pontuação."}</>:<>Primeiro acerto: <b>1.000 pontos.</b><br/>Demais acertos: <b>até 700</b>, conforme o tempo.</>}</p></div><ConnectionCheck/><p className="muted">Mantenha esta página aberta.</p></main>}
    {me&&state.status==="question"&&state.question&&<main className="player-live"><div className="player-score-row"><span>PERGUNTA {state.index+1}/{state.total}</span><span>{me.avatar} {points(me.score)} pts</span></div>{countdown>0?<div className="player-countdown"><span>Prepare-se!</span><strong key={countdown}>{countdown}</strong><p>A próxima pergunta está chegando.</p></div>:<><div className={`player-timer ${!state.untimed&&seconds<=5?"timer-urgent":""}`}><Clock3 size={19}/><b>{state.untimed?"Tempo livre":`${seconds}s`}</b>{!state.untimed&&<Progress value={Math.min(100,seconds/state.question.seconds*100)} aria-label="Tempo restante"/>}</div><QuestionHeading question={state.question}/>
      {me.answered?<div className="answer-sent"><span className="answer-sent-icon"><Check size={35}/></span><h2>Resposta confirmada!</h2><p>{me.option!==null?`Você escolheu ${LETTERS[me.option]}: ${state.question.options[me.option]}`:"Sua resposta foi registrada."}</p><span>Aguarde o resultado da rodada.</span></div>:pending?<div className="answer-pending" role="status"><Loader2 size={30} className="spin"/><h2>Confirmando sua resposta…</h2><p>{LETTERS[pending.option]} · {state.question.options[pending.option]}</p><span>{retryMessage||"A confirmação aparece quando o servidor registra sua escolha."}</span></div>:<AnswerOptions question={state.question} onChoose={respond} disabled={busy||(!state.untimed&&!seconds)||!!error}/>}
      {!me.answered&&!pending&&<p className="player-answer-note">{state.untimed||seconds?"Toque na alternativa. Sua escolha não pode ser alterada depois do envio.":"Tempo encerrado. Aguarde o placar."}</p>}</>}</main>}
    {me&&state.status==="results"&&state.question&&<main className="player-results"><span className={`result-icon ${me.roundCorrect?"result-success":"result-neutral"}`}>{me.roundCorrect?<Check size={34}/>:<X size={34}/>}</span><h1>{me.roundCorrect?"Mandou bem!":me.answered?"Valeu a tentativa!":"Esta ficou sem resposta"}</h1><p className="player-round-points">+{points(me.roundPoints)}<span>pontos nesta rodada</span></p><div className="player-correct-answer"><span>RESPOSTA CORRETA</span><b>{state.question.options[state.correct!]}</b>{state.question.optionImages?.[state.correct!]&&<img className="reveal-image" src={state.question.optionImages[state.correct!]} alt={state.question.options[state.correct!]}/>} {state.explanation&&<p>{state.explanation}</p>}</div><div className="my-ranking"><span><Trophy size={21}/><b>{me.position}º lugar</b></span><b>{points(me.score)}<small>pontos no total</small></b></div><h2 className="player-ranking-heading">Placar da turma</h2><Ranking players={state.players} me={me.id}/><p className="next-waiting"><Clock3 size={16}/>Aguarde o professor continuar.</p></main>}
    {final&&<main className="player-final-workspace"><span className="badge badge-blue">QUIZ CONCLUÍDO</span><h1>Aprendemos juntos<span>!</span></h1>{me&&<div className="player-final-score"><span>{me.avatar}</span><div><b>{me.position}º lugar · {me.name}</b><p>{points(me.score)} pontos · {me.correctCount} acertos</p></div></div>}<Podium players={state.players}/>{state.players.length>2&&<Ranking players={state.players.slice(2)} me={me?.id} final/>}<a href="/jogar?trocar=1" className="btn btn-primary" onClick={exit}><Home size={18}/>Entrar em outra sala</a></main>}
    {closed&&<main className="player-error"><Trophy size={42}/><h1>Sala encerrada</h1><p>Obrigado por participar! Peça ao professor o código da próxima sala.</p><a href="/" className="btn btn-primary">Voltar ao início</a></main>}
    <Notifications/>
  </div>;
}
