"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {PresentationRecord,SlideDeck,validateDeck} from "@/lib/presentation";
import {api,ApiError} from "./shared";
export function usePresentationDraft(owner:string,record:PresentationRecord,onIdentity?:(id:string)=>void) {
  const [deck,setDeck]=useState(record.deck);const [past,setPast]=useState<SlideDeck[]>([]),[future,setFuture]=useState<SlideDeck[]>([]);const [saveState,setSaveState]=useState<"saved"|"dirty"|"saving"|"offline"|"conflict">("saved");const [saveError,setSaveError]=useState("");
  const latest=useRef(deck);latest.current=deck;const meta=useRef({revision:record.revision,writeId:record.writeId});const saved=useRef(JSON.stringify(record.deck));const flight=useRef<Promise<boolean>|null>(null);const pending=useRef<{deck:SlideDeck;revision:number;writeId:string;serialized:string}|null>(null);const conflict=useRef(false);const gesture=useRef<SlideDeck|null>(null);const merge=useRef({key:"",at:0});const mounted=useRef(true);
  const key=(id:string)=>`qe_presentation_v1:${owner}:${id}`;
  const backup=useCallback((value:SlideDeck)=>{try{localStorage.setItem(key(value.id),JSON.stringify({deck:value,revision:meta.current.revision,at:Date.now()}));}catch{}},[owner]);
  const commit=useCallback((value:SlideDeck|((old:SlideDeck)=>SlideDeck),mergeKey="")=>{const previous=latest.current;const next=typeof value==="function"?value(previous):value;if(JSON.stringify(previous)===JSON.stringify(next))return;const combine=mergeKey&&merge.current.key===mergeKey&&Date.now()-merge.current.at<700;merge.current={key:mergeKey,at:Date.now()};if(!combine)setPast(list=>[...list,previous].slice(-40));setFuture([]);latest.current=next;setDeck(next);setSaveState(conflict.current?"conflict":"dirty");backup(next);},[backup]);
  function beginGesture(){gesture.current=latest.current;}
  function previewGesture(value:SlideDeck){latest.current=value;setDeck(value);}
  function endGesture(){const base=gesture.current;gesture.current=null;if(!base||JSON.stringify(base)===JSON.stringify(latest.current))return;setPast(list=>[...list,base].slice(-40));setFuture([]);setSaveState(conflict.current?"conflict":"dirty");backup(latest.current);}
  function undo(){if(!past.length)return;const previous=past.at(-1)!;setPast(past.slice(0,-1));setFuture(list=>[latest.current,...list]);latest.current=previous;setDeck(previous);setSaveState(conflict.current?"conflict":"dirty");backup(previous);}
  function redo(){if(!future.length)return;const next=future[0];setFuture(future.slice(1));setPast(list=>[...list,latest.current].slice(-40));latest.current=next;setDeck(next);setSaveState(conflict.current?"conflict":"dirty");backup(next);}
  const save=useCallback(async():Promise<boolean>=>{
    if(conflict.current)return false;if(flight.current)return flight.current;if(saved.current===JSON.stringify(latest.current)&&meta.current.revision>0){setSaveState("saved");return true;}
    let canonical:SlideDeck;try{canonical=validateDeck(latest.current);}catch(e){setSaveState("offline");setSaveError((e as Error).message);return false;}
    const payload=pending.current||{deck:canonical,revision:meta.current.revision,writeId:crypto.randomUUID(),serialized:JSON.stringify(latest.current)};pending.current=payload;setSaveState("saving");
    const task=(async()=>{try{const {serialized,...request}=payload;const data=await api<{presentation:PresentationRecord}>("/api/presentations",request);meta.current={revision:data.presentation.revision,writeId:data.presentation.writeId};saved.current=serialized;pending.current=null;setSaveError("");const clean=JSON.stringify(latest.current)===serialized;if(mounted.current)setSaveState(clean?"saved":"dirty");if(clean){try{localStorage.removeItem(key(payload.deck.id));}catch{}}else backup(latest.current);return true;}catch(e){const error=e as ApiError;if(error.status===409||error.status===403){conflict.current=true;if(mounted.current)setSaveState("conflict");}else if(mounted.current)setSaveState("offline");setSaveError(error.message);backup(latest.current);return false;}finally{flight.current=null;}})();flight.current=task;return task;
  },[backup,owner]);
  async function flush():Promise<boolean>{for(let i=0;i<6;i++){if(!await save())return false;if(saved.current===JSON.stringify(latest.current))return true;}return false;}
  useEffect(()=>{let stored:{deck:SlideDeck;revision:number}|null=null;try{stored=JSON.parse(localStorage.getItem(key(record.deck.id))||"null");}catch{}if(stored?.deck&&JSON.stringify(stored.deck)!==JSON.stringify(record.deck)){try{const recovered=validateDeck(stored.deck);if(stored.revision===record.revision){latest.current=recovered;setDeck(recovered);setSaveState("dirty");}else{latest.current=recovered;setDeck(recovered);conflict.current=true;setSaveState("conflict");setSaveError("Há uma cópia neste aparelho e uma versão diferente na conta. Escolha qual manter.");}}catch{}}else if(record.revision===0)setSaveState("dirty");},[]);
  useEffect(()=>{if(!["dirty","offline"].includes(saveState))return;const timer=setTimeout(()=>void save(),saveState==="offline"?10000:1200);return()=>clearTimeout(timer);},[deck,saveState,save]);
  useEffect(()=>{mounted.current=true;const online=()=>void save();const unload=(e:BeforeUnloadEvent)=>{if(saved.current!==JSON.stringify(latest.current)){backup(latest.current);e.preventDefault();e.returnValue="";}};const hidden=()=>{if(document.hidden&&saved.current!==JSON.stringify(latest.current))backup(latest.current);};window.addEventListener("online",online);window.addEventListener("beforeunload",unload);document.addEventListener("visibilitychange",hidden);return()=>{mounted.current=false;window.removeEventListener("online",online);window.removeEventListener("beforeunload",unload);document.removeEventListener("visibilitychange",hidden);};},[save,backup]);
  function useCloud(){try{localStorage.removeItem(key(latest.current.id));}catch{}latest.current=record.deck;saved.current=JSON.stringify(record.deck);setDeck(record.deck);setPast([]);setFuture([]);conflict.current=false;pending.current=null;window.location.reload();}
  async function keepCopy(){if(flight.current)await flight.current;const next={...latest.current,id:crypto.randomUUID(),title:`${latest.current.title.slice(0,90)} · cópia`};meta.current={revision:0,writeId:""};pending.current=null;conflict.current=false;saved.current="";latest.current=next;setDeck(next);setPast([]);setFuture([]);setSaveState("dirty");backup(next);onIdentity?.(next.id);return flush();}
  return {deck,latest,commit,past,future,undo,redo,beginGesture,previewGesture,endGesture,save,flush,saveState,saveError,useCloud,keepCopy};
}
