"use client";
import { AvatarImage } from "./avatar-picker";
import { ActionDock } from "./action-dock";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Check,Clock3,Expand,ExternalLink,FileText,List,Loader2,Monitor,MousePointer2,NotebookPen,Play,QrCode,Trophy,Users,X} from "lucide-react";
import {toast} from "sonner";
import QRCode from "qrcode";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogTitle} from "@/components/ui/alert-dialog";
import {RoomState,points} from "@/lib/quiz";
import {deckQuestions,richTextPlain,SlideDeck,slideSteps} from "@/lib/presentation";
import {api,Brand,Notifications,Offline,useClock} from "./shared";
import {Ranking} from "./room-shared";
import {SlideCanvas} from "./slide-canvas";

async function fullscreen(element?:HTMLElement|null){try{if(document.fullscreenElement)await document.exitFullscreen();else await (element||document.documentElement).requestFullscreen();}catch{toast.info("Use a opção de tela inteira do navegador.");}}
export function PresentationLive({state,error,apply,refresh,projection=false}:{state:RoomState;error:string;apply:(state:RoomState)=>void;refresh:()=>Promise<unknown>;projection?:boolean}) {
  const p=state.presentation!;const [busy,setBusy]=useState(false),[outline,setOutline]=useState(false),[notes,setNotes]=useState(false),[invite,setInvite]=useState(false),[qr,setQr]=useState(""),[ranking,setRanking]=useState(true),[laser,setLaser]=useState(false),[pointer,setPointer]=useState<{x:number;y:number}|null>(null),[confirm,setConfirm]=useState<"end_round"|"close"|null>(null);const channel=useRef<BroadcastChannel|null>(null);const stage=useRef<HTMLDivElement>(null);const current=useRef(state);current.current=state;const blocked=busy||!!error;
  const seconds=useClock(state.serverNow,state.endsAt,state.clock),countdown=useClock(state.serverNow,state.startsAt,state.clock);
  async function action(action:string,targetSlide?:number,blackout?:boolean){if(busy||error)return;setBusy(true);const s=current.current;try{apply(await api<RoomState>(`/api/rooms/${s.code}/control`,{action,index:s.index,status:s.status,slideIndex:s.presentation!.index,step:s.presentation!.step,targetSlide,blackout}));}catch(e){toast.error((e as Error).message);void refresh().catch(()=>{});}finally{setBusy(false);setConfirm(null);}}
  useEffect(()=>{const url=`${window.location.origin}/participar/${state.code}`;void QRCode.toDataURL(url,{width:300,margin:3}).then(setQr).catch(()=>toast.info(`Use o código ${state.code} para entrar na sala.`));},[state.code]);
  useEffect(()=>{if(!("BroadcastChannel" in window))return;const c=new BroadcastChannel(`qe_presenter_${state.code}`);channel.current=c;c.onmessage=event=>{const v=event.data;if(v?.type==="laser"&&projection)setPointer(v.point&&typeof v.point.x==="number"&&typeof v.point.y==="number"&&v.point.x>=0&&v.point.x<=1&&v.point.y>=0&&v.point.y<=1?{x:v.point.x,y:v.point.y}:null);};return()=>{c.close();channel.current=null;};},[state.code,projection]);
  useEffect(()=>{function key(e:KeyboardEvent){if(projection||confirm||invite||outline||e.ctrlKey||e.metaKey||e.altKey||e.target instanceof HTMLElement&&e.target.closest("input,textarea,select,[contenteditable=true]"))return;if(e.key===" "&&e.target instanceof HTMLElement&&e.target.closest("button"))return;const s=current.current;if(["ArrowRight","PageDown"," "].includes(e.key)&&s.status!=="question"){e.preventDefault();void action("next");}else if(["ArrowLeft","PageUp"].includes(e.key)&&s.status!=="question"&&s.presentation!.index>0){e.preventDefault();void action("previous");}else if(e.key.toLowerCase()==="b"&&s.status!=="question"){e.preventDefault();void action("blackout",undefined,!s.presentation!.blackout);}else if(e.key.toLowerCase()==="f"){e.preventDefault();void fullscreen();}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[busy,error,projection,confirm,invite,outline]);
  function move(event:React.PointerEvent){if(!laser||!stage.current)return;const rect=stage.current.getBoundingClientRect();const point={x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))};setPointer(point);channel.current?.postMessage({type:"laser",point});}
  function clearPointer(){setPointer(null);channel.current?.postMessage({type:"laser",point:null});}
  const nextLabel=state.status==="question"?"Aguardando respostas":p.step<p.steps&&state.status==="slide"?"Mostrar próximo item":p.index+1===p.total?"Concluir aula":p.outline?.[p.index+1]?.kind==="question"?"Iniciar pergunta":"Próximo slide";
  return <div className={`lesson-live ${!projection?"has-action-dock":""} ${projection?"lesson-projection":""} ${ranking?"":"lesson-no-ranking"}`}><header className="lesson-live-topbar"><Brand dark/><div><b>{state.title}</b><span>Slide {p.index+1}/{p.total} · sala {state.code}</span></div><nav>{!projection&&<><button aria-label="Convidar turma" title="QR code da sala" onClick={()=>setInvite(true)}><QrCode size={20}/></button><a title="Abrir telão em outra janela" aria-label="Abrir telão em outra janela" href={`/sala/${state.code}/tela`} target="_blank" rel="noopener noreferrer"><ExternalLink size={20}/></a></>}<button title="Mostrar ou esconder ranking" aria-label="Mostrar ou esconder ranking" aria-pressed={ranking} onClick={()=>setRanking(!ranking)}><Trophy size={20}/></button><button aria-label="Tela inteira" onClick={()=>fullscreen()}><Expand size={20}/></button>{!projection&&<button aria-label="Encerrar aula" onClick={()=>setConfirm("close")}><X size={20}/></button>}</nav></header>{error&&<Offline text="Reconectando à aula. Aguarde para avançar ou responder."/>}
    <main className="lesson-live-grid"><section className="lesson-stage-area"><div className="lesson-stage-meta"><span>{state.status==="question"?`PERGUNTA ${state.index+1}/${state.total}`:p.review?"REVISÃO · PONTOS PRESERVADOS":state.status==="results"?"RESPOSTA E RESULTADO":"APRESENTAÇÃO"}</span><span><Users size={16}/>{state.status==="question"?`${state.answeredCount}/${state.players.length} responderam`:`${state.players.length} na sala`}</span></div><div ref={stage} className={`lesson-slide-stage transition-${p.slide?.transition||"none"} ${laser?"lesson-laser-active":""}`} onPointerMove={move} onPointerLeave={clearPointer}>{p.blackout?<div className="lesson-blackout"><Monitor size={38}/><span>Aguarde o professor</span></div>:p.slide&&<SlideCanvas key={`${p.index}:${state.status}`} slide={p.slide} theme={p.theme} step={p.step} number={p.index} showNumber={p.showSlideNumbers} interactive question={state.question||undefined} correct={state.correct} explanation={state.explanation||""} countdown={state.status==="question"?countdown:0} seconds={state.status==="question"?seconds:undefined} untimed={state.untimed}/>} {pointer&&!p.blackout&&<span className="lesson-laser" style={{left:`${pointer.x*100}%`,top:`${pointer.y*100}%`}}/>}</div>{state.status==="results"&&<div className="lesson-round-summary"><Check size={18}/><b>{state.players.filter(player=>player.roundCorrect).length} acertaram</b><span>O ranking foi atualizado. Continue a aula quando desejar.</span></div>}{state.status==="question"&&<div className="lesson-round-summary"><Clock3 size={18}/><span>{countdown>0?"A pergunta começa em instantes.":state.untimed?"Cada acerto vale 1.000 pontos. Aguarde ou encerre a rodada.":`${seconds}s restantes · ${state.mode==="speed"?"Primeiro acerto: 1.000 pontos. Demais: até 700.":"Cada acerto vale 1.000 pontos."}`}</span></div>}{state.correct!==null&&state.explanation&&<div className="lesson-question-feedback"><b>Vamos entender a resposta</b><p>{state.explanation}</p></div>}</section>{ranking&&<aside className="lesson-live-ranking"><div><h2><Trophy size={22}/>Ranking da aula</h2><span>Pontuação acumulada</span></div>{state.players.length?<Ranking players={state.players}/>:<p>A turma aparecerá aqui ao entrar na sala.</p>}</aside>}</main>
    {!projection&&<ActionDock dark className="lesson-control-dock"><div className="presenter-tools"><button onClick={()=>setOutline(!outline)} aria-pressed={outline}><List size={18}/><span>Slides</span></button><button onClick={()=>setNotes(!notes)} aria-pressed={notes}><NotebookPen size={18}/><span>Notas</span></button><button disabled={blocked||state.status==="question"} onClick={()=>action("blackout",undefined,!p.blackout)} aria-pressed={p.blackout}><Monitor size={18}/><span>{p.blackout?"Mostrar telão":"Pausar telão"}</span></button><button aria-pressed={laser} onClick={()=>{setLaser(!laser);clearPointer();}}><MousePointer2 size={18}/><span>Ponteiro</span></button></div><div className="presenter-navigation"><button className="btn btn-room-outline" disabled={blocked||state.status==="question"||(p.index===0&&p.step===0)} onClick={()=>action("previous")}><ArrowLeft size={18}/>Anterior</button>{state.status==="question"?<button className="btn btn-lime" disabled={blocked} onClick={()=>setConfirm("end_round")}>Encerrar rodada</button>:<button className="btn btn-lime" disabled={blocked} onClick={()=>action("next")}>{busy?<Loader2 className="spin" size={18}/>:<Play size={18}/>} {nextLabel}</button>}</div></ActionDock>}
    {notes&&!projection&&<aside className="lesson-presenter-notes"><h3><NotebookPen size={18}/>Notas do professor <small>Use o telão separado para projetar só o slide e o ranking.</small></h3><p>{p.slide?.notes||"Este slide não tem notas. Adicione-as no editor da aula."}</p></aside>}
    <Dialog open={outline&&!projection} onOpenChange={setOutline}><DialogContent className="q-dialog lesson-outline-dialog"><DialogTitle>Slides da aula</DialogTitle><DialogDescription>Você pode rever slides e perguntas concluídas. Novas perguntas seguem a ordem da aula.</DialogDescription><ol>{p.outline?.map((s,i)=><li key={s.id}><button disabled={blocked||state.status==="question"||s.questionIndex>state.index+1||(s.kind==="content"&&s.questionIndex>state.index)} className={i===p.index?"selected":""} onClick={()=>{setOutline(false);void action("goto",i);}}><span>{String(i+1).padStart(2,"0")}</span><b>{s.title}</b><small>{s.kind==="question"?"Pergunta":"Slide"}</small></button></li>)}</ol></DialogContent></Dialog>
    <Dialog open={invite&&!projection} onOpenChange={setInvite}><DialogContent className="q-dialog"><DialogTitle>Convide a turma</DialogTitle><DialogDescription>A sala é a mesma durante toda a aula. Novos alunos podem entrar enquanto você apresenta um slide.</DialogDescription>{qr&&<img className="lesson-invite-qr" src={qr} width={260} height={260} alt={`QR code da sala ${state.code}`}/>}<strong className="lesson-invite-code">{state.code}</strong><button className="btn btn-primary" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/participar/${state.code}`);toast.success("Link copiado.");}catch{toast.info(`Use o código ${state.code}.`);}}}>Copiar link da sala</button></DialogContent></Dialog>
    <AlertDialog open={!!confirm} onOpenChange={open=>{if(!open)setConfirm(null);}}><AlertDialogContent className="q-dialog"><AlertDialogTitle>{confirm==="close"?"Encerrar esta aula?":"Concluir a rodada agora?"}</AlertDialogTitle><AlertDialogDescription>{confirm==="close"?"A turma deixará de responder. A aula salva e o relatório continuam no seu acesso.":"As respostas recebidas entram no ranking. Depois, você pode continuar a apresentação."}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>action(confirm!)}>Confirmar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Notifications/>
  </div>;
}
export function StudentSlide({state}:{state:RoomState}) {
  const p=state.presentation!,me=state.me!;const [open,setOpen]=useState(false),[text,setText]=useState(false),[zoom,setZoom]=useState(1);const shown=p.slide?.elements.filter(e=>!e.hidden&&e.build<=p.step)||[];
  return <main className="student-lesson-slide"><div className="student-lesson-meta"><b>SLIDE {p.index+1}/{p.total}</b><span><AvatarImage value={me.avatar} size={28}/> {points(me.score)} pontos · {me.position}º lugar</span></div><h1>{p.slide?.title||state.title}</h1>{p.blackout?<div className="student-lesson-pause"><Monitor size={32}/><p>Aguarde o professor continuar.</p></div>:p.slide&&<SlideCanvas key={p.index} slide={p.slide} theme={p.theme} step={p.step} number={p.index} showNumber={p.showSlideNumbers} interactive question={state.question||undefined} correct={state.correct} explanation={state.explanation||""}/>}<div className="student-slide-tools"><button className="btn btn-outline" disabled={p.blackout} onClick={()=>setOpen(true)}><Expand size={17}/>Ampliar slide</button><button className="btn btn-quiet" onClick={()=>setText(!text)} aria-expanded={text}><FileText size={17}/>Ler conteúdo</button></div>{text&&!p.blackout&&<div className="student-slide-readable">{state.question&&<><h2>{state.question.text}</h2><ul>{state.question.options.map((option,i)=><li key={i}>{option}{state.correct===i?" ✓":""}</li>)}</ul>{state.explanation&&<p>{state.explanation}</p>}</>}{shown.map(e=>e.type==="text"?<p key={e.id}>{richTextPlain(e.doc)}</p>:e.type==="image"&&e.alt?<p key={e.id}>Imagem: {e.alt}</p>:e.type==="table"?<table key={e.id}><tbody>{e.cells?.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>:e.type==="chart"?<ul key={e.id}>{e.labels?.map((l,i)=><li key={i}>{l}: {e.values?.[i]}</li>)}</ul>:null)}</div>}<p className="student-slide-waiting"><Clock3 size={17}/>{p.review?"Pergunta já concluída. Seus pontos permanecem os mesmos.":"Acompanhe a explicação. A próxima pergunta aparece aqui."}</p><Dialog open={open} onOpenChange={setOpen}><DialogContent className="q-dialog student-slide-dialog"><DialogTitle>{p.slide?.title||"Slide da aula"}</DialogTitle><DialogDescription>Amplie para ler e deslize a área quando necessário.</DialogDescription><label className="student-slide-zoom">Ampliação<input type="range" min={1} max={3} step={.25} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/>{Math.round(zoom*100)}%</label><div className="student-slide-large-scroll"><div style={{width:`${zoom*100}%`}}>{p.slide&&<SlideCanvas slide={p.slide} theme={p.theme} step={p.step} interactive question={state.question||undefined} correct={state.correct} explanation={state.explanation||""}/>}</div></div></DialogContent></Dialog></main>;
}
export function DeckPreview({deck,start=0,onClose}:{deck:SlideDeck;start?:number;onClose:()=>void}) {
  const [index,setIndex]=useState(start),[step,setStep]=useState(0),[reveal,setReveal]=useState(false),[notes,setNotes]=useState(false);const current=deck.slides[index];const wrapper=useRef<HTMLDivElement>(null);
  function advance(direction:number){if(direction>0&&step<slideSteps(current)){setStep(step+1);return;}if(direction<0&&step>0){setStep(step-1);return;}setIndex(i=>Math.max(0,Math.min(deck.slides.length-1,i+direction)));setStep(0);setReveal(false);}
  useEffect(()=>{function key(e:KeyboardEvent){if(e.ctrlKey||e.metaKey||e.altKey)return;if(["ArrowRight","PageDown"," "].includes(e.key)){e.preventDefault();advance(1);}else if(["ArrowLeft","PageUp"].includes(e.key)){e.preventDefault();advance(-1);}else if(e.key==="Escape"&&!document.fullscreenElement)onClose();}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[index,step]);
  return <div className="lesson-preview" ref={wrapper}><header><span><Monitor size={20}/>Prévia da aula · {index+1}/{deck.slides.length}</span><div><button onClick={()=>fullscreen(wrapper.current)} aria-label="Tela inteira"><Expand size={20}/></button><button onClick={onClose} aria-label="Fechar prévia"><X size={21}/></button></div></header><main><SlideCanvas key={index} slide={current} theme={deck.theme} step={step} number={index} showNumber={deck.showSlideNumbers} interactive draft correct={reveal&&current.question&&current.question.correct>=0?current.question.correct:null} explanation={reveal?current.question?.explanation:""}/></main><footer><button className="btn btn-room-outline" onClick={()=>setNotes(!notes)}><NotebookPen size={17}/>Notas</button>{current.kind==="question"&&<button className="btn btn-room-outline" disabled={!current.question||current.question.correct<0} onClick={()=>setReveal(!reveal)}>{reveal?"Ocultar resposta":"Ver resposta"}</button>}<span>{deckQuestions(deck).length} perguntas · abra uma sala para jogar com a turma</span><button className="btn btn-room-outline" disabled={index===0&&step===0} onClick={()=>advance(-1)}><ArrowLeft size={18}/>Anterior</button><button className="btn btn-lime" disabled={index===deck.slides.length-1&&step===slideSteps(current)} onClick={()=>advance(1)}>Avançar<ArrowRight size={18}/></button></footer>{reveal&&current.question?.explanation&&<aside className="lesson-preview-notes"><b>Explicação da resposta</b><p>{current.question.explanation}</p></aside>}{notes&&<aside className="lesson-preview-notes"><b>Notas do professor</b><p>{current.notes||"Sem notas neste slide."}</p></aside>}</div>;
}
