"use client";
import {useEffect,useRef,useState} from "react";
import {Search,TextCursorInput,PanelLeftClose,PanelLeftOpen,Lock,Unlock,Eye,EyeOff,AlignCenter,ArrowDown,ArrowLeft,ArrowUp,BarChart3,BookOpen,Check,ChevronDown,ChevronLeft,ChevronRight,Cloud,Copy,Download,FileUp,Grid2X2,Group,Image as ImageIcon,LayoutTemplate,Layers,Loader2,Maximize,Minus,MonitorPlay,MousePointer2,Plus,Redo2,Save,Shapes,Sparkles,Table2,Trash2,Type,Undo2,Ungroup,Video,X} from "lucide-react";
import {toast} from "sonner";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogTitle} from "@/components/ui/alert-dialog";
import {baseElement,deckQuestions,duplicateSlide,LessonSlide,MAX_ELEMENTS,MAX_LESSON_QUESTIONS,MAX_SLIDES,newSlide,PresentationRecord,questionSlide,RichNode,richTextPlain,SlideDeck,SlideElement,SLIDE_HEIGHT,SLIDE_LAYOUTS,SLIDE_WIDTH,validateDeck} from "@/lib/presentation";
import {applyTextChange,matchingSlides,alignElements,boundedElement,cloneElements,distributeElements,moveElements,resizeElement} from "@/lib/presentation-editor";
import {newQuestion,Profile,Question,Quiz,questionIssues} from "@/lib/quiz";
import {api,Notifications} from "./shared";
import {SlideCanvas} from "./slide-canvas";
import {SlideInspector} from "./slide-inspector";
import {SlideRichEditor} from "./slide-rich-editor";
import {SlideInlineTextEditor} from "./slide-text-tools";
import {usePresentationDraft} from "./presentation-draft";
import {DeckPreview} from "./presentation-live";
import {QuestionBank} from "./question-bank";
import {QuestionImportDialog} from "./question-import";
import {QuestionAiDialog} from "./question-ai";
import type {QuestionPatch} from "./question-fields";

type Panel="slides"|"properties"|"layers";
type Modal="layout"|"question"|"bank"|"import"|"ai"|"quiz"|"export"|"help"|null;
export function PresentationEditor({profile,record}:{profile:Profile;record:PresentationRecord}) {
  const draft=usePresentationDraft(profile.id,record,id=>window.history.replaceState(null,"",`/aulas/${id}`));const {deck}=draft;
  const [index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>([]),[panel,setPanel]=useState<Panel>("properties"),[modal,setModal]=useState<Modal>(null),[zoom,setZoom]=useState(100),[snap,setSnap]=useState(true),[grid,setGrid]=useState(false),[rich,setRich]=useState<string|null>(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[quizzes,setQuizzes]=useState<Quiz[]>([]),[deleteSlide,setDeleteSlide]=useState(false),[guides,setGuides]=useState({x:false,y:false}),[canvasWidth,setCanvasWidth]=useState(800),[editing,setEditing]=useState<string|null>(null),[toolbarHost,setToolbarHost]=useState<HTMLDivElement|null>(null),[slideQuery,setSlideQuery]=useState(""),[questionsOnly,setQuestionsOnly]=useState(false),[focusMode,setFocusMode]=useState(false),[notesOpen,setNotesOpen]=useState(false);
  const clipboard=useRef<SlideElement[]>([]),slideDrag=useRef<string|null>(null),file=useRef<HTMLInputElement>(null),workspace=useRef<HTMLDivElement>(null),filmstrip=useRef<HTMLOListElement>(null),gestureCleanup=useRef<(()=>void)|null>(null);
  const slide=deck.slides[Math.min(index,deck.slides.length-1)],selectedElements=slide.elements.filter(e=>selected.includes(e.id)),questions=deckQuestions(deck);
  const visibleSlides=matchingSlides(deck,slideQuery,questionsOnly);
  const stateRef=useRef({draft,index,selected,slide,modal,rich,editing,preview,snap,uploads});stateRef.current={draft,index,selected,slide,modal,rich,editing,preview,snap,uploads};
  useEffect(()=>{if(record.revision===0)window.history.replaceState(null,"",`/aulas/${deck.id}`);},[]);
  useEffect(()=>{if(index>=deck.slides.length)setIndex(deck.slides.length-1);setSelected(old=>old.filter(id=>slide.elements.some(e=>e.id===id)));},[slide.id,deck.slides.length]);
  useEffect(()=>{if(modal!=="quiz")return;void api<{quizzes:Quiz[]}>("/api/dashboard").then(data=>setQuizzes(data.quizzes)).catch(e=>toast.error(e.message));},[modal]);
  useEffect(()=>{const area=workspace.current;if(!area)return;const observer=new ResizeObserver(()=>{const style=getComputedStyle(area),width=area.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),height=area.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);setCanvasWidth(Math.max(160,window.innerWidth>900?Math.min(width,Math.max(90,height)*16/9):width));});observer.observe(area);return()=>observer.disconnect();},[]);
  useEffect(()=>()=>gestureCleanup.current?.(),[]);
  useEffect(()=>{filmstrip.current?.querySelector(`[data-slide-id="${slide.id}"]`)?.scrollIntoView({block:"nearest",behavior:"auto"});},[slide.id,slideQuery,questionsOnly]);
  useEffect(()=>{if(!editing)return;const element=slide.elements.find(e=>e.id===editing);if(!element||element.locked||!selected.includes(editing)){setEditing(null);return;}const outside=(event:PointerEvent)=>{if(!(event.target as HTMLElement)?.closest(".slide-inline-text,.presentation-text-tools,[data-slot=popover-content],.presentation-inspector"))setEditing(null);};document.addEventListener("pointerdown",outside);return()=>document.removeEventListener("pointerdown",outside);},[editing,slide.id,selected.join(":"),selectedElements[0]?.locked]);
  function finishText(){setEditing(null);requestAnimationFrame(()=>workspace.current?.focus({preventScroll:true}));}
  function startText(id:string,expanded=false){const element=draft.latest.current.slides.find(s=>s.id===slide.id)?.elements.find(e=>e.id===id);if(!element||element.type!=="text")return;if(element.locked){toast.info("Desbloqueie o texto antes de editar.");return;}gestureCleanup.current?.();setSelected([id]);setPanel("properties");if(expanded||window.innerWidth<=900){setEditing(null);setRich(id);}else{setRich(null);setEditing(id);}}
  function textChange(id:string,doc:RichNode){draft.commit(old=>applyTextChange(old,slide.id,id,doc),`text:${id}`);}
  function selectSlide(i:number){if(uploads){toast.info("Aguarde o envio da imagem antes de trocar de slide.");return;}setEditing(null);setIndex(Math.max(0,Math.min(deck.slides.length-1,i)));setSelected([]);setPanel("properties");}
  function patchSlide(patch:Partial<LessonSlide>,mergeKey=""){draft.commit(old=>({...old,slides:old.slides.map(s=>s.id===slide.id?{...s,...patch}:s)}),mergeKey);}
  function patchElement(patch:Partial<SlideElement>){draft.commit(old=>({...old,slides:old.slides.map(s=>s.id===slide.id?{...s,elements:s.elements.map(e=>selected.includes(e.id)?boundedElement({...e,...patch}):e)}:s)}),`element:${selected.join(":")}:${Object.keys(patch).join(":")}`);}
  function patchObject(id:string,patch:Partial<SlideElement>){draft.commit(old=>({...old,slides:old.slides.map(s=>s.id===slide.id?{...s,elements:s.elements.map(e=>e.id===id?boundedElement({...e,...patch}):e)}:s)}),`object:${id}:${Object.keys(patch).join(":")}`);}
  function changeQuestion(patch:QuestionPatch){const latestQuestion=draft.latest.current.slides.find(s=>s.id===slide.id)?.question;if(!latestQuestion)return;const q={...latestQuestion,...(typeof patch==="function"?patch(latestQuestion):patch)};patchSlide({question:q,title:q.text.trim().slice(0,80)||"Pergunta da turma"},`question:${slide.id}`);}
  function insertSlides(items:LessonSlide[]){if(deck.slides.length+items.length>MAX_SLIDES){toast.error("Use até 150 slides por aula.");return false;}if(questions.length+items.filter(s=>s.kind==="question").length>MAX_LESSON_QUESTIONS){toast.error("Use até 50 perguntas por aula.");return false;}draft.commit({...deck,slides:[...deck.slides.slice(0,index+1),...items,...deck.slides.slice(index+1)]});setIndex(index+1);setSelected([]);setPanel("properties");return true;}
  function importQuestions(items:Question[]){const ok=insertSlides(items.map(q=>questionSlide({...structuredClone(q),id:crypto.randomUUID()},deck.theme)));if(ok){setModal(null);toast.success(`${items.length} pergunta(s) inserida(s) após o slide atual.`);}return ok;}
  function addObject(type:SlideElement["type"]){if(slide.kind==="question"){toast.info("Use o painel da pergunta para editar o conteúdo deste slide.");return;}if(slide.elements.length>=MAX_ELEMENTS){toast.error("Use até 60 objetos por slide.");return;}const e=baseElement(type,deck.theme);patchSlide({elements:[...slide.elements,e]});setSelected([e.id]);setPanel("properties");if(type==="text"){if(window.innerWidth<=900)setRich(e.id);else setEditing(e.id);}}
  function removeObjects(){patchSlide({elements:slide.elements.filter(e=>!selected.includes(e.id)||e.locked)});setSelected([]);}
  function duplicateObjects(){const copies=cloneElements(selectedElements.filter(e=>!e.locked));if(slide.elements.length+copies.length>MAX_ELEMENTS){toast.error("Use até 60 objetos por slide.");return;}patchSlide({elements:[...slide.elements,...copies]});setSelected(copies.map(e=>e.id));}
  function layer(direction:"front"|"back"|"up"|"down"){const items=[...slide.elements];if(direction==="front"||direction==="back"){const chosen=items.filter(e=>selected.includes(e.id)),rest=items.filter(e=>!selected.includes(e.id));patchSlide({elements:direction==="front"?[...rest,...chosen]:[...chosen,...rest]});return;}const order=direction==="up"?[...items.keys()].reverse():[...items.keys()];for(const i of order){const j=direction==="up"?i+1:i-1;if(j>=0&&j<items.length&&selected.includes(items[i].id)&&!selected.includes(items[j].id))[items[i],items[j]]=[items[j],items[i]];}patchSlide({elements:items});}
  function reorderSlide(id:string,target:number){const from=deck.slides.findIndex(s=>s.id===id);if(from<0||from===target)return;const items=[...deck.slides];const [moving]=items.splice(from,1);items.splice(target,0,moving);draft.commit({...deck,slides:items});setIndex(target);setSelected([]);}
  function cloneSlide(){if(insertSlides([duplicateSlide(slide)]))toast.success("Slide duplicado.");}
  function groupObjects(){const group=crypto.randomUUID();patchSlide({elements:slide.elements.map(e=>selected.includes(e.id)?{...e,group}:e)});}
  function ungroupObjects(){patchSlide({elements:slide.elements.map(e=>selected.includes(e.id)?{...e,group:undefined}:e)});}
  function beginPointer(id:string,event:React.PointerEvent,handle?:string){if(event.button!==0||editing===id)return;setEditing(null);gestureCleanup.current?.();event.stopPropagation();const element=slide.elements.find(e=>e.id===id);if(!element)return;let ids=selected;const groupIds=element.group?slide.elements.filter(e=>e.group===element.group).map(e=>e.id):[id];if(event.shiftKey&&!handle){ids=ids.includes(id)?ids.filter(v=>!groupIds.includes(v)):[...new Set([...ids,...groupIds])];setSelected(ids);if(!ids.includes(id))return;}else if(!ids.includes(id)){ids=groupIds;setSelected(ids);}setPanel("properties");if(element.locked)return;event.preventDefault();const surface=(event.currentTarget as HTMLElement).closest(".slide-frame") as HTMLElement|null;if(!surface)return;const scale=surface.getBoundingClientRect().width/SLIDE_WIDTH,startX=event.clientX,startY=event.clientY,base=draft.latest.current,origin=base.slides.find(s=>s.id===slide.id)!;draft.beginGesture();let ended=false;
    const move=(e:PointerEvent)=>{if(e.pointerId!==event.pointerId||ended)return;const dx=(e.clientX-startX)/scale,dy=(e.clientY-startY)/scale;let elements=handle?origin.elements.map(o=>o.id===id?resizeElement(o,handle,dx,dy,snap&&!e.altKey):o):moveElements(origin.elements,ids,dx,dy,snap&&!e.altKey);if(!handle&&elements.filter(o=>ids.includes(o.id)).length===1){const item=elements.find(o=>o.id===id)!;const cx=item.x+item.w/2,cy=item.y+item.h/2,gx=snap&&Math.abs(cx-SLIDE_WIDTH/2)<6,gy=snap&&Math.abs(cy-SLIDE_HEIGHT/2)<6;if(gx||gy)elements=moveElements(elements,ids,gx?SLIDE_WIDTH/2-cx:0,gy?SLIDE_HEIGHT/2-cy:0);setGuides({x:gx,y:gy});}draft.previewGesture({...base,slides:base.slides.map(s=>s.id===origin.id?{...s,elements}:s)});};
    const finish=()=>{if(ended)return;ended=true;window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);window.removeEventListener("pointercancel",end);window.removeEventListener("blur",finish);gestureCleanup.current=null;draft.endGesture();setGuides({x:false,y:false});};const end=(e:PointerEvent)=>{if(e.pointerId===event.pointerId)finish();};gestureCleanup.current=finish;window.addEventListener("pointermove",move);window.addEventListener("pointerup",end);window.addEventListener("pointercancel",end);window.addEventListener("blur",finish);
  }
  useEffect(()=>{const key=(e:KeyboardEvent)=>{
    const {draft:d,index:i,selected:ids,slide:s,modal:m,rich:r,editing:typing,preview:p,uploads:pendingUploads}=stateRef.current;
    if(e.defaultPrevented||gestureCleanup.current||m||r||p)return;
    const modifier=e.ctrlKey||e.metaKey;
    if(modifier&&e.key.toLowerCase()==="s"){e.preventDefault();void d.flush().then(ok=>ok&&toast.success("Aula salva."));return;}
    if(typing){if(e.key==="Escape"&&!(e.target as HTMLElement)?.closest("[data-slot=popover-content]")){e.preventDefault();setEditing(null);}return;}
    if((e.target as HTMLElement)?.closest("input,textarea,select,[contenteditable=true],[role=dialog]"))return;
    const update=(elements:SlideElement[])=>d.commit(old=>({...old,slides:old.slides.map(sl=>sl.id===s.id?{...sl,elements}:sl)}),e.key.startsWith("Arrow")?"nudge":"");
    if(modifier&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?d.redo():d.undo();}
    else if(modifier&&e.key.toLowerCase()==="y"){e.preventDefault();d.redo();}
    else if(modifier&&e.key.toLowerCase()==="a"){e.preventDefault();setSelected(s.elements.map(o=>o.id));}
    else if(modifier&&e.key.toLowerCase()==="c"&&ids.length){e.preventDefault();clipboard.current=structuredClone(s.elements.filter(o=>ids.includes(o.id)));}
    else if(modifier&&["v","d"].includes(e.key.toLowerCase())){const source=e.key.toLowerCase()==="d"?s.elements.filter(o=>ids.includes(o.id)):clipboard.current;if(!source.length)return;e.preventDefault();const copies=cloneElements(source);if(s.elements.length+copies.length>MAX_ELEMENTS){toast.error("Use até 60 objetos por slide.");return;}update([...s.elements,...copies]);setSelected(copies.map(o=>o.id));}
    else if(["Delete","Backspace"].includes(e.key)&&ids.length){e.preventDefault();update(s.elements.filter(o=>!ids.includes(o.id)||o.locked));setSelected([]);}
    else if(e.key==="Escape")setSelected([]);
    else if(e.key==="Enter"&&ids.length===1&&s.elements.find(o=>o.id===ids[0])?.type==="text"&&!(e.target as HTMLElement)?.closest("button")){e.preventDefault();const element=s.elements.find(o=>o.id===ids[0])!;if(!element.locked){if(window.innerWidth<=900)setRich(element.id);else setEditing(element.id);}}
    else if(e.key.startsWith("Arrow")&&ids.length){e.preventDefault();const amount=e.shiftKey?10:1;update(moveElements(s.elements,ids,e.key==="ArrowLeft"?-amount:e.key==="ArrowRight"?amount:0,e.key==="ArrowUp"?-amount:e.key==="ArrowDown"?amount:0));}
    else if(e.key==="PageDown"||e.key==="PageUp"){e.preventDefault();if(pendingUploads)return;setIndex(Math.max(0,Math.min(d.latest.current.slides.length-1,i+(e.key==="PageDown"?1:-1))));setSelected([]);}
  };window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
  async function openRoom(){if(uploads){toast.info("Aguarde o envio das imagens.");return;}try{validateDeck(deck,true);}catch(e){toast.error((e as Error).message);const invalid=deck.slides.findIndex(s=>s.question&&questionIssues(s.question).some(issue=>issue.severity==="error"));if(invalid>=0)selectSlide(invalid);return;}setBusy(true);try{if(!await draft.flush())throw new Error(draft.saveError||"Salve a aula antes de abrir a sala.");const room=await api<{code:string}>("/api/rooms",{presentationId:draft.latest.current.id});window.location.assign(`/sala/${room.code}`);}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function download(kind:"json"|"pptx"){if(uploads){toast.info("Aguarde o envio das imagens antes de exportar.");return;}setBusy(true);try{const exports=await import("@/lib/presentation-export");if(kind==="json")exports.downloadDeck(deck);else await exports.downloadPowerPoint(deck);toast.success(kind==="json"?"Cópia da aula exportada.":"PowerPoint exportado. As rodadas ao vivo acontecem no QuizEdu.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function importFile(upload:File){try{if(upload.size>1048576)throw new Error("Use uma aula QuizEdu de até 1 MB.");const raw=JSON.parse(await upload.text());const imported=validateDeck(raw.deck||raw);if(deck.slides.length+imported.slides.length>MAX_SLIDES)throw new Error("A aula completa pode ter até 150 slides.");insertSlides(imported.slides.map(duplicateSlide));toast.success("Slides inseridos após o slide atual.");}catch(e){toast.error((e as Error).message);}if(file.current)file.current.value="";}
  async function back(){if(await draft.flush())window.location.assign("/aulas");else toast.error("Guarde uma cópia da aula ou resolva o aviso de salvamento antes de sair.");}
  const saveLabels={saved:"Salvo na conta",dirty:"Alterações pendentes",saving:"Salvando…",offline:"Salvamento pendente",conflict:"Escolha a versão"};
  const richElement=slide.elements.find(e=>e.id===rich&&e.type==="text");
  return <div className={`presentation-editor ${focusMode?"presentation-focus":""}`}><header className="presentation-editor-header"><button className="slide-icon-button" aria-label="Voltar às aulas" onClick={back}><ArrowLeft size={20}/></button><div className="presentation-document-name"><label className="sr-only" htmlFor="lesson-title">Título da aula</label><input id="lesson-title" aria-label="Título da aula" value={deck.title} maxLength={100} onChange={e=>draft.commit({...deck,title:e.target.value},"deck-title")}/><span className={`presentation-save-state save-${draft.saveState}`}>{draft.saveState==="saving"?<Loader2 size={13} className="spin"/>:draft.saveState==="saved"?<Check size={13}/>:<Cloud size={13}/>} {saveLabels[draft.saveState]}</span></div><div className="presentation-header-actions"><button className="btn btn-quiet" onClick={()=>setModal("help")} aria-label="Ajuda do editor"><MousePointer2 size={17}/><span>Ajuda</span></button><button className="btn btn-outline" aria-label="Arquivos e exportação" onClick={()=>setModal("export")}><Download size={17}/><span>Arquivo</span></button><button className="btn btn-outline" aria-label="Prévia da aula" onClick={()=>{setEditing(null);setPreview(true);}}><MonitorPlay size={17}/><span>Prévia</span></button><button className="btn btn-primary" disabled={busy||uploads>0} onClick={openRoom}>{busy?<Loader2 className="spin" size={17}/>:<MonitorPlay size={17}/>}Abrir sala</button></div></header>
    {(draft.saveState==="offline"||draft.saveState==="conflict")&&<div className="presentation-save-alert" role="status"><span>{draft.saveError||"Sem conexão. Tentaremos salvar novamente quando ela voltar."}</span>{draft.saveState==="conflict"?<><button onClick={()=>void draft.keepCopy()}>Guardar minha cópia</button><button onClick={draft.useCloud}>Abrir versão da conta</button></>:<button onClick={()=>void draft.flush()}>Tentar salvar</button>}<button onClick={()=>download("json")}>Baixar cópia</button></div>}
    <nav className="presentation-toolstrip" aria-label="Ferramentas do slide"><div className="slide-tool-group"><button disabled={!draft.past.length} aria-label="Desfazer" title="Desfazer · Ctrl Z" onClick={draft.undo}><Undo2 size={18}/></button><button disabled={!draft.future.length} aria-label="Refazer" title="Refazer · Ctrl Shift Z" onClick={draft.redo}><Redo2 size={18}/></button></div><div className="slide-tool-group"><button onClick={()=>setModal("layout")}><LayoutTemplate size={18}/>Novo slide</button><button className="slide-insert-question" onClick={()=>setModal("question")}><Sparkles size={18}/>Pergunta</button></div><div className="slide-tool-group">{[{type:"text",Icon:Type,label:"Texto"},{type:"image",Icon:ImageIcon,label:"Imagem"},{type:"shape",Icon:Shapes,label:"Forma"},{type:"table",Icon:Table2,label:"Tabela"},{type:"chart",Icon:BarChart3,label:"Gráfico"},{type:"video",Icon:Video,label:"Vídeo"}].map(tool=><button key={tool.type} disabled={slide.kind==="question"} onClick={()=>addObject(tool.type as SlideElement["type"])}><tool.Icon size={18}/>{tool.label}</button>)}</div><div className="slide-tool-group slide-tool-last"><button aria-label={focusMode?"Mostrar painéis":"Ocultar painéis para focar no slide"} aria-pressed={focusMode} title="Foco no slide" onClick={()=>setFocusMode(!focusMode)}>{focusMode?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button><button aria-label="Mostrar grade" aria-pressed={grid} onClick={()=>setGrid(!grid)} title="Grade"><Grid2X2 size={18}/></button><label className="slide-snap-toggle" title="Ajustar objetos à grade e ao centro. Alt desativa durante o arraste."><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/>Alinhar</label></div></nav>
    <div className="presentation-mobile-tabs"><button aria-pressed={panel==="slides"} onClick={()=>setPanel("slides")}><LayoutTemplate size={16}/>Slides</button><button aria-pressed={panel==="properties"} onClick={()=>setPanel("properties")}><Shapes size={16}/>Propriedades</button><button aria-pressed={panel==="layers"} onClick={()=>setPanel("layers")}><Layers size={16}/>Camadas</button></div>
    <main className={`presentation-edit-body mobile-panel-${panel}`}><aside className="presentation-filmstrip" aria-label="Sequência dos slides"><div className="presentation-pane-heading"><b>Sequência</b><span>{deck.slides.length} slides</span></div><div className="slide-navigation-search"><label><Search size={16}/><input type="search" aria-label="Buscar slides por título ou conteúdo" placeholder="Buscar slides…" value={slideQuery} onChange={e=>setSlideQuery(e.target.value)}/>{slideQuery&&<button type="button" aria-label="Limpar busca de slides" onClick={()=>setSlideQuery("")}><X size={15}/></button>}</label><div><button type="button" aria-pressed={!questionsOnly} onClick={()=>setQuestionsOnly(false)}>Todos</button><button type="button" aria-pressed={questionsOnly} onClick={()=>setQuestionsOnly(true)}><Sparkles size={14}/>Perguntas</button></div>{(slideQuery||questionsOnly)&&<small role="status">{visibleSlides.length} de {deck.slides.length} slides</small>}</div><ol ref={filmstrip}>{visibleSlides.map(i=>{const s=deck.slides[i];return <li key={s.id} data-slide-id={s.id} className={`${s.id===slide.id?"is-current":""} ${s.kind==="question"?"is-question":""}`} draggable={!slideQuery&&!questionsOnly&&!uploads} onDragStart={e=>{slideDrag.current=s.id;e.dataTransfer.effectAllowed="move";}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(slideDrag.current)reorderSlide(slideDrag.current,i);slideDrag.current=null;}}><button className="slide-thumbnail" onClick={()=>selectSlide(i)} aria-current={s.id===slide.id?"true":undefined} aria-label={`Slide ${i+1}: ${s.title}`}><SlideCanvas slide={s} theme={deck.theme} draft/><span className="slide-thumbnail-label"><b>{String(i+1).padStart(2,"0")}</b>{s.kind==="question"&&<Sparkles size={12}/>}<span>{s.title||"Sem título"}</span></span></button></li>;})}{!visibleSlides.length&&<li className="slide-search-empty">Nenhum slide encontrado.<button onClick={()=>{setSlideQuery("");setQuestionsOnly(false);}}>Mostrar todos</button></li>}</ol><button className="presentation-add-slide" onClick={()=>setModal("layout")}><Plus size={18}/>Adicionar slide</button></aside>
    <section className="presentation-workbench"><div className="presentation-canvas-heading"><div><span className={`badge ${slide.kind==="question"?"badge-lime":"badge-blue"}`}>{slide.kind==="question"?"PERGUNTA AO VIVO":"SLIDE DE CONTEÚDO"}</span><span className="presentation-active-slide-name" title={slide.title}>{slide.title||"Sem título"}</span></div><div><button aria-label="Mover slide para cima" disabled={!index} onClick={()=>reorderSlide(slide.id,index-1)}><ArrowUp size={17}/></button><button aria-label="Mover slide para baixo" disabled={index===deck.slides.length-1} onClick={()=>reorderSlide(slide.id,index+1)}><ArrowDown size={17}/></button><button aria-label="Duplicar slide" onClick={cloneSlide}><Copy size={17}/></button><button aria-label="Excluir slide" disabled={deck.slides.length===1} onClick={()=>setDeleteSlide(true)}><Trash2 size={17}/></button></div></div>
      <div ref={setToolbarHost} className={`presentation-text-tools ${editing?"is-editing":""}`}/><div className="presentation-canvas-scroll" ref={workspace} tabIndex={-1} onPointerDown={e=>{if(!(e.target as HTMLElement).closest(".slide-element")){setSelected([]);setEditing(null);}}}><div className={`presentation-canvas-zoom ${grid?"show-canvas-grid":""}`} style={{width:canvasWidth*zoom/100}}><SlideCanvas slide={slide} theme={deck.theme} number={index} showNumber={deck.showSlideNumbers} editor selected={selected} editingId={editing} onElementFocus={id=>{if(!editing){const element=slide.elements.find(e=>e.id===id);setSelected(element?.group?slide.elements.filter(e=>e.group===element.group).map(e=>e.id):[id]);}}} onElementKey={(id,e)=>{if(editing===id)return;if(e.key==="Enter"||e.key===" "){e.preventDefault();e.stopPropagation();setSelected([id]);if(e.key==="Enter")startText(id);}}} renderElement={e=>editing===e.id?<SlideInlineTextEditor key={e.id} element={e} toolbarHost={toolbarHost} onChange={doc=>textChange(e.id,doc)} onDone={finishText} onExpand={()=>startText(e.id,true)}/>:undefined} onSelect={(id,e)=>beginPointer(id,e)} onHandle={(id,h,e)=>beginPointer(id,e,h)} onDoubleClick={id=>startText(id)} draft/>{guides.x&&<div className="slide-guide-x"/>}{guides.y&&<div className="slide-guide-y"/>}</div></div>
      <div className="presentation-selection-tools">{selected.length?<><span className="slide-selection-count">{selected.length===1?(selectedElements[0]?.type==="text"?"Texto selecionado":"Objeto selecionado"):`${selected.length} objetos`}</span>{selectedElements.length===1&&selectedElements[0].type==="text"&&!selectedElements[0].locked&&<button className="slide-selection-edit" onClick={()=>startText(selected[0])}><TextCursorInput size={16}/>Editar texto</button>}<select aria-label="Alinhar objetos" value="" onChange={e=>{patchSlide({elements:alignElements(slide.elements,selected,e.target.value as Parameters<typeof alignElements>[2])});}}><option value="" disabled>Alinhar…</option><option value="left">Esquerda</option><option value="center">Centro horizontal</option><option value="right">Direita</option><option value="top">Topo</option><option value="middle">Centro vertical</option><option value="bottom">Base</option></select>{selected.length>2&&<><button onClick={()=>patchSlide({elements:distributeElements(slide.elements,selected,"x")})}>Distribuir na horizontal</button><button onClick={()=>patchSlide({elements:distributeElements(slide.elements,selected,"y")})}>Distribuir na vertical</button></>}{selected.length>1&&<button onClick={groupObjects}><Group size={15}/>Agrupar</button>}{selectedElements.some(e=>e.group)&&<button onClick={ungroupObjects}><Ungroup size={15}/>Desagrupar</button>}<button onClick={duplicateObjects} aria-label="Duplicar seleção"><Copy size={15}/></button><button onClick={removeObjects} aria-label="Excluir seleção"><Trash2 size={15}/></button></>:<span>{slide.kind==="question"?"Edite a pergunta no painel de propriedades.":"Arraste para mover · Dois cliques ou Enter para escrever · Shift seleciona vários"}</span>}</div>
      <div className="presentation-notes-editor"><button className="presentation-notes-toggle" aria-expanded={notesOpen} aria-controls="slide-notes-panel" onClick={()=>setNotesOpen(!notesOpen)}><BookOpen size={16}/>Notas do professor{slide.notes&&<span className="slide-notes-count">{slide.notes.length} caracteres</span>}<span>Visíveis apenas para você</span><ChevronDown size={16}/></button>{notesOpen&&<div id="slide-notes-panel"><label className="sr-only" htmlFor="speaker-notes">Notas do professor</label><textarea id="speaker-notes" value={slide.notes} maxLength={5000} onChange={e=>patchSlide({notes:e.target.value},`notes:${slide.id}`)} placeholder="Exemplos, perguntas para discussão e lembretes para conduzir este slide…" rows={3}/></div>}</div>
      <footer className="presentation-editor-status"><span>Slide {index+1}/{deck.slides.length} · {questions.length} perguntas · 16:9</span><div><button aria-label="Diminuir zoom" disabled={zoom<=50} onClick={()=>setZoom(Math.max(50,zoom-25))}><Minus size={15}/></button><button onClick={()=>setZoom(100)} title="Ajustar à tela"><Maximize size={15}/>{zoom}%</button><button aria-label="Aumentar zoom" disabled={zoom>=200} onClick={()=>setZoom(Math.min(200,zoom+25))}><Plus size={15}/></button></div></footer>
    </section><aside className="presentation-inspector"><div className="presentation-inspector-tabs"><button aria-pressed={panel!=="layers"} onClick={()=>setPanel("properties")}>Propriedades</button><button aria-pressed={panel==="layers"} onClick={()=>setPanel("layers")}><Layers size={15}/>Camadas</button></div>{panel==="layers"?<div className="slide-layers"><p>Os objetos do topo aparecem à frente.</p>{[...slide.elements].reverse().map((e,i)=><div className={`slide-layer-row ${selected.includes(e.id)?"selected":""}`} key={e.id}><button className="slide-layer-select" onClick={()=>setSelected(e.group?slide.elements.filter(o=>o.group===e.group).map(o=>o.id):[e.id])} aria-pressed={selected.includes(e.id)}><span>{e.type==="text"?<Type size={17}/>:e.type==="image"?<ImageIcon size={17}/>:e.type==="chart"?<BarChart3 size={17}/>:e.type==="table"?<Table2 size={17}/>:e.type==="video"?<Video size={17}/>:<Shapes size={17}/>}</span><b>{e.type==="text"?richTextPlain(e.doc).slice(0,40)||"Texto":e.type==="image"?e.alt||"Imagem":e.type==="shape"?"Forma":e.type==="chart"?"Gráfico":e.type==="table"?"Tabela":"Vídeo"}</b><small>{i+1}</small></button><div><button title={e.hidden?"Mostrar objeto":"Ocultar objeto"} aria-label={`${e.hidden?"Mostrar":"Ocultar"} objeto ${i+1}`} aria-pressed={e.hidden} onClick={()=>patchObject(e.id,{hidden:!e.hidden})}>{e.hidden?<EyeOff size={16}/>:<Eye size={16}/>}</button><button title={e.locked?"Desbloquear objeto":"Bloquear objeto"} aria-label={`${e.locked?"Desbloquear":"Bloquear"} objeto ${i+1}`} aria-pressed={e.locked} onClick={()=>patchObject(e.id,{locked:!e.locked})}>{e.locked?<Lock size={16}/>:<Unlock size={16}/>}</button></div></div>)}{!slide.elements.length&&<p>{slide.kind==="question"?"O conteúdo desta pergunta é editado em Propriedades.":"Insira um texto, imagem ou forma."}</p>}<div className="slide-small-actions"><button disabled={!selected.length} onClick={()=>layer("front")}>Para a frente</button><button disabled={!selected.length} onClick={()=>layer("back")}>Para o fundo</button></div></div>:<SlideInspector onClearSelection={()=>{setEditing(null);setSelected([]);}} deck={deck} slide={slide} selected={selectedElements} onElement={patchElement} onSlide={patch=>patchSlide(patch,`slide:${Object.keys(patch).join(":")}`)} onDeck={next=>draft.commit(next,"deck-settings")} onRichEdit={()=>startText(selected[0])} onDelete={removeObjects} onDuplicate={duplicateObjects} onLayer={layer} onQuestion={changeQuestion} onUploadChange={value=>setUploads(n=>Math.max(0,n+(value?1:-1)))}/>}</aside></main>
    <input ref={file} className="sr-only" type="file" accept=".json,application/json" onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);}}/>
    <Dialog open={modal==="layout"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog slide-layout-dialog"><DialogTitle>Escolha o próximo slide</DialogTitle><DialogDescription>O modelo é um ponto de partida. Todos os objetos podem ser editados.</DialogDescription><div className="slide-layout-grid">{SLIDE_LAYOUTS.map(layout=><button key={layout.id} onClick={()=>{if(insertSlides([newSlide(layout.id,deck.theme)]))setModal(null);}}><SlideCanvas slide={newSlide(layout.id,deck.theme)} theme={deck.theme}/><b>{layout.name}</b></button>)}</div></DialogContent></Dialog>
    <Dialog open={modal==="question"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog"><DialogTitle>Hora de ouvir a turma</DialogTitle><DialogDescription>A pergunta entra após o slide atual e usa a pontuação acumulada da aula.</DialogDescription><div className="slide-question-choices">{[{id:"multiple",label:"Múltipla escolha",detail:"Duas a quatro alternativas"},{id:"true_false",label:"Verdadeiro ou falso",detail:"Uma afirmação para avaliar"},{id:"yes_no",label:"Sim ou não",detail:"Duas respostas para a turma"},{id:"image",label:"Pergunta com imagem",detail:"Observe e responda"}].map(kind=><button key={kind.id} onClick={()=>{const q=kind.id==="yes_no"?{...newQuestion("multiple",{optionCount:2}),options:["Sim","Não"]}:newQuestion(kind.id as "multiple"|"true_false"|"image");if(insertSlides([questionSlide(q,deck.theme)]))setModal(null);}}><Sparkles size={20}/><div><b>{kind.label}</b><span>{kind.detail}</span></div><Plus size={16}/></button>)}</div><div className="slide-small-actions"><button onClick={()=>setModal("bank")}><BookOpen size={16}/>Meu banco</button><button onClick={()=>setModal("quiz")}><Copy size={16}/>Usar um quiz</button><button onClick={()=>setModal("import")}><FileUp size={16}/>Importar</button><button onClick={()=>setModal("ai")}><Sparkles size={16}/>Criar com IA</button></div></DialogContent></Dialog>
    <Dialog open={modal==="bank"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog slide-bank-dialog"><DialogTitle>Perguntas do seu banco</DialogTitle><DialogDescription>Escolha uma pergunta para inserir neste ponto da aula.</DialogDescription><QuestionBank onChoose={q=>importQuestions([q])}/></DialogContent></Dialog>
    <Dialog open={modal==="quiz"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog"><DialogTitle>Trazer perguntas de um quiz</DialogTitle><DialogDescription>As perguntas serão copiadas. Depois, arraste os slides para intercalá-las com o conteúdo.</DialogDescription><div className="slide-quiz-picker">{quizzes.map(q=><button key={q.id} onClick={()=>importQuestions(q.questions)}><BookOpen size={20}/><b>{q.title}<small>{q.questions.length} perguntas</small></b><Plus size={18}/></button>)}{!quizzes.length&&<p>Crie um quiz no painel inicial ou insira perguntas do zero.</p>}</div></DialogContent></Dialog>
    {modal==="import"&&<QuestionImportDialog remaining={MAX_LESSON_QUESTIONS-questions.length} defaultSeconds={30} replaceEmpty={false} onImport={importQuestions} onClose={()=>setModal(null)}/>}
    {modal==="ai"&&<QuestionAiDialog topic={deck.topic} remaining={MAX_LESSON_QUESTIONS-questions.length} defaultSeconds={30} replaceEmpty={false} onImport={importQuestions} onClose={()=>setModal(null)}/>}
    <Dialog open={modal==="export"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog"><DialogTitle>Leve sua aula com você</DialogTitle><DialogDescription>O arquivo QuizEdu preserva perguntas e objetos. PowerPoint e impressão apresentam o conteúdo; a participação pelo celular e o ranking funcionam na sala QuizEdu.</DialogDescription><div className="slide-export-actions"><button disabled={busy} onClick={()=>download("json")}><Save size={22}/><div><b>Baixar aula QuizEdu</b><span>Cópia completa para guardar e importar</span></div></button><button onClick={()=>{setModal(null);file.current?.click();}}><FileUp size={22}/><div><b>Inserir aula QuizEdu</b><span>Importar slides de um arquivo .json</span></div></button><button disabled={busy} onClick={()=>download("pptx")}><MonitorPlay size={22}/><div><b>Exportar PowerPoint</b><span>Texto, formas, tabelas e gráficos editáveis</span></div></button><button disabled={busy||uploads>0} onClick={async()=>{const target=window.open("about:blank","_blank");if(target)target.opener=null;if(await draft.flush()){const path=`/aulas/${draft.latest.current.id}/imprimir`;if(target)target.location.replace(path);else window.location.assign(path);}else{target?.close();toast.error("Salve a aula antes de imprimir.");}}}><Download size={22}/><div><b>Imprimir ou salvar PDF</b><span>Um slide por página, sem as notas do professor</span></div></button></div></DialogContent></Dialog>
    <Dialog open={modal==="help"} onOpenChange={v=>!v&&setModal(null)}><DialogContent className="q-dialog"><DialogTitle>Seu ritmo, sua aula</DialogTitle><DialogDescription>Crie a sequência, prepare as perguntas e abra uma sala quando estiver pronto.</DialogDescription><ol className="slide-editor-help"><li>Adicione slides pelos modelos ou comece em branco.</li><li>Arraste objetos; use as alças para redimensionar. Dê dois cliques no texto ou selecione e pressione Enter para escrever diretamente. No celular, use a edição ampliada.</li><li>Use Shift para selecionar vários objetos. Agrupe, alinhe e distribua a seleção.</li><li>Arraste as miniaturas ou use as setas para mudar a ordem dos slides.</li><li>Insira as perguntas nos pontos da aula em que a turma vai responder.</li><li>Na sala, use a tela da turma para projetar. Suas notas ficam só na tela do professor.</li></ol><p className="field-help">Esc conclui a edição direta · Ctrl/Cmd Enter aplica a edição ampliada · Ctrl/Cmd S salva · Ctrl/Cmd Z desfaz · Ctrl/Cmd Shift Z refaz · Ctrl/Cmd C/V copia e cola objetos · Ctrl/Cmd D duplica · setas movem · Shift + setas move 10 · Alt durante o arraste desliga o alinhamento · Page Up/Down troca slide.</p></DialogContent></Dialog>
    <AlertDialog open={deleteSlide} onOpenChange={setDeleteSlide}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir este slide?</AlertDialogTitle><AlertDialogDescription>Você pode desfazer esta alteração enquanto o editor estiver aberto.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{draft.commit({...deck,slides:deck.slides.filter(s=>s.id!==slide.id)});setIndex(Math.max(0,index-1));setSelected([]);setDeleteSlide(false);}}>Excluir slide</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {richElement&&<SlideRichEditor key={richElement.id} element={richElement} slide={slide} theme={deck.theme} onClose={()=>setRich(null)} onSave={doc=>{textChange(richElement.id,doc);setRich(null);}}/>}{preview&&<DeckPreview deck={deck} start={index} onClose={()=>setPreview(false)}/>}<Notifications/>
  </div>;
}
