"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,BookOpen,Copy,Edit3,FileUp,GraduationCap,Loader2,MonitorPlay,Plus,Search,ShieldCheck,Sparkles,Trash2} from "lucide-react";
import {toast} from "sonner";
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogTitle} from "@/components/ui/alert-dialog";
import {duplicateDeck,newDeck,PresentationRecord,PresentationSummary,SlideDeck,validateDeck} from "@/lib/presentation";
import type {Profile} from "@/lib/quiz";
import {api,ApiError,Brand,Loading,Notifications} from "./shared";
import {SlideCanvas} from "./slide-canvas";
import {PresentationImportDialog} from "./presentation-import";
import {PresentationEditor} from "./presentation-editor";

export function EducatorEntry({signInHref,onEntered}:{signInHref:string;onEntered:()=>void}) {const [name,setName]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");return <div className="presentation-entry"><span className="badge badge-blue">ESPAÇO DO EDUCADOR</span><h1>Uma aula inteira.<br/>A turma participando.</h1><p>Crie slides, intercale perguntas e acompanhe o aprendizado ao vivo.</p><a className="btn btn-primary" href={signInHref} target="_top"><ShieldCheck size={18}/>Continuar com ChatGPT</a><span className="presentation-entry-divider">ou experimente com seu nome</span><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/profile",{name});onEntered();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label htmlFor="slides-teacher">Como podemos chamar você?</label><input id="slides-teacher" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={30} required placeholder="Professora Ana"/><button className="btn btn-outline" disabled={busy}>{busy?<Loader2 size={18} className="spin"/>:<GraduationCap size={18}/>}Experimentar gratuitamente</button>{error&&<p className="form-error" role="alert">{error}</p>}</form><small>O acesso temporário dura 30 dias neste navegador. A conta permanente permite retomar as aulas em outros aparelhos.</small></div>;}
export function PresentationLibrary({signInHref}:{signInHref:string}) {const [profile,setProfile]=useState<Profile|null>(null),[lessons,setLessons]=useState<PresentationSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[deleting,setDeleting]=useState<PresentationSummary|null>(null);const [importing,setImporting]=useState(false);
  async function refresh(){setLoading(true);try{const dashboard=await api<{profile:Profile|null}>("/api/dashboard");setProfile(dashboard.profile);if(dashboard.profile){const data=await api<{presentations:PresentationSummary[]}>("/api/presentations");setLessons(data.presentations);}setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]);
  async function saveCopy(record:PresentationRecord,example=false){setBusy(true);try{const deck=example?record.deck:duplicateDeck(record.deck);await api("/api/presentations",{deck,revision:0,writeId:crypto.randomUUID()});window.location.assign(`/aulas/${deck.id}`);}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function duplicate(id:string){setBusy(true);try{const data=await api<{presentation:PresentationRecord}>(`/api/presentations/${id}`);await saveCopy(data.presentation);}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function useExample(){setBusy(true);try{const data=await api<{presentation:SlideDeck}>("/api/examples");await saveCopy({deck:data.presentation,revision:0,updatedAt:0,writeId:""},true);}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function openRoom(id:string){setBusy(true);try{const data=await api<{code:string}>("/api/rooms",{presentationId:id});window.location.assign(`/sala/${data.code}`);}catch(e){toast.error((e as Error).message);setBusy(false);}}

  const normal=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const filtered=lessons.filter(s=>normal(`${s.title} ${s.subject} ${s.topic}`).includes(normal(search)));
  return <div className="app-shell"><header className="topbar"><Brand/><a className="btn btn-quiet" href="/"><ArrowLeft size={17}/>Meus quizzes</a></header><main className="workspace presentation-library"><div className="page-heading"><div><p className="eyebrow">DO CONTEÚDO À PARTICIPAÇÃO</p><h1>Aulas com slides<span className="title-dot">.</span></h1><p className="muted">Apresente no seu ritmo. Transforme uma explicação em uma pergunta para a turma.</p></div>{profile&&<div className="presentation-library-actions"><button className="btn btn-outline" disabled={busy} onClick={()=>setImporting(true)}><FileUp size={17}/>Importar apresentação</button><a className="btn btn-primary" href="/aulas/nova"><Plus size={19}/>Nova aula</a></div>}</div>
    {loading?<Loading label="Carregando suas aulas…"/>:!profile?<EducatorEntry signInHref={signInHref} onEntered={()=>void refresh()}/>:<><div className="presentation-free-banner"><MonitorPlay size={27}/><div><b>Slides e perguntas, juntos. Disponível gratuitamente.</b><p>Editor visual, sala por QR code, respostas no celular e ranking acumulado durante a aula.</p></div><span className="badge badge-lime">LIBERADO AGORA</span></div>{error&&<div className="error-panel" role="alert"><p>{error}</p><button className="btn btn-outline" onClick={refresh}>Tentar novamente</button></div>}
    {!!lessons.length&&<div className="search-field"><Search size={18}/><input aria-label="Buscar aulas com slides" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por título, disciplina ou assunto"/></div>}<div className="presentation-deck-grid">{filtered.map(s=><article className="presentation-deck-card" key={s.id}><a href={`/aulas/${s.id}`} aria-label={`Editar ${s.title}`}><SlideCanvas slide={s.cover} theme={s.theme} draft/></a><div className="presentation-deck-card-body"><div className="question-tags">{s.subject&&<span>{s.subject}</span>}{s.topic&&<span>{s.topic}</span>}</div><h2>{s.title}</h2><p>{s.slideCount} slides · {s.questionCount} perguntas</p><small>Atualizada em {new Date(s.updatedAt).toLocaleDateString("pt-BR")}</small><div className="card-primary-actions"><a className="btn btn-outline" href={`/aulas/${s.id}`}><Edit3 size={16}/>Editar</a><button className="btn btn-primary" disabled={busy} onClick={()=>openRoom(s.id)}><MonitorPlay size={16}/>Abrir sala</button></div><div className="card-secondary-actions"><button disabled={busy} onClick={()=>duplicate(s.id)}><Copy size={15}/>Duplicar</button><button disabled={busy} aria-label={`Excluir ${s.title}`} onClick={()=>setDeleting(s)}><Trash2 size={15}/></button></div></div></article>)}<a className="new-quiz-card presentation-new-card" href="/aulas/nova"><span className="new-quiz-icon"><Plus size={30}/></span><b>{lessons.length?"Preparar outra aula":"Sua primeira apresentação"}</b><span>Comece pela capa, escolha um tema<br/>e conte sua história.</span><span className="small-action">Criar do zero</span></a></div>{search&&!filtered.length&&<p className="field-help">Nenhuma aula corresponde à busca.</p>}<div className="example-card"><img className="example-photo" src="/examples/plantio.jpg" alt="Mãos plantando uma muda"/><div><span className="eyebrow">EXPERIMENTE UMA AULA COMPLETA</span><h2>Solo vivo, turma em ação</h2><p>14 slides com fotos e 6 perguntas intercaladas, prontos para editar e apresentar.</p></div><button className="btn btn-outline" disabled={busy} onClick={useExample}>Usar exemplo</button></div></>}
    <footer className="site-footer"><span>QuizEdu · Feito para aprender juntos</span><span>O QuizEdu padrão continua gratuito.</span></footer></main>{importing&&<PresentationImportDialog onClose={()=>setImporting(false)} onImport={async deck=>{await api("/api/presentations",{deck,revision:0,writeId:crypto.randomUUID()});window.location.assign(`/aulas/${deck.id}`);}}/>}<AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent className="q-dialog"><AlertDialogTitle>Excluir esta aula?</AlertDialogTitle><AlertDialogDescription>“{deleting?.title}” será removida. Salas já abertas e relatórios mantêm sua própria cópia. Exporte a aula antes se quiser guardá-la.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(!deleting)return;setBusy(true);try{await api(`/api/presentations/${deleting.id}`,{revision:deleting.revision},"DELETE");setDeleting(null);await refresh();toast.success("Aula excluída.");}catch(e){toast.error((e as Error).message);await refresh();}finally{setBusy(false);}}}>Excluir aula</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Notifications/></div>;
}
export function PresentationWorkspace({id,signInHref}:{id:string;signInHref:string}) {const [profile,setProfile]=useState<Profile|null>(null),[record,setRecord]=useState<PresentationRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const creation=useRef<PresentationRecord|null>(null);
  async function load(){setLoading(true);try{const data=await api<{profile:Profile|null}>("/api/dashboard");setProfile(data.profile);if(data.profile){if(id==="nova"){creation.current ||= {deck:newDeck(),revision:0,writeId:"",updatedAt:0};setRecord(creation.current);}else{const data=await api<{presentation:PresentationRecord}>(`/api/presentations/${id}`);setRecord(data.presentation);}}setError("");}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[id]);
  if(profile&&record)return <PresentationEditor key={record.deck.id} profile={profile} record={record}/>;
  return <div className="app-shell"><header className="topbar"><Brand/><a className="btn btn-quiet" href="/aulas"><ArrowLeft size={17}/>Minhas aulas</a></header><main className="workspace">{loading?<Loading label="Abrindo o editor…"/>:error?<div className="empty-panel" role="alert"><BookOpen size={34}/><h1>Vamos encontrar a aula</h1><p>{error}</p><button className="btn btn-primary" onClick={load}>Tentar novamente</button><a className="btn btn-outline" href="/aulas">Minhas aulas</a></div>:<EducatorEntry signInHref={signInHref} onEntered={()=>void load()}/>}</main><Notifications/></div>;
}
export function PresentationPrint({id}:{id:string}) {const [deck,setDeck]=useState<PresentationRecord["deck"]|null>(null),[error,setError]=useState("");useEffect(()=>{void api<{presentation:PresentationRecord}>(`/api/presentations/${id}`).then(data=>setDeck(data.presentation.deck)).catch(e=>setError(e.message));},[id]);return <div className="presentation-print"><header><a className="btn btn-outline" href={`/aulas/${id}`}><ArrowLeft size={16}/>Voltar ao editor</a><span>{deck?.title||"Preparando impressão"}</span><button className="btn btn-primary" disabled={!deck} onClick={()=>window.print()}><DownloadIcon/>Imprimir / salvar PDF</button></header>{error?<p role="alert">{error}</p>:!deck?<Loading label="Preparando os slides…"/>:<main>{deck.slides.map((slide,i)=><section key={slide.id} className="slide-print-page"><SlideCanvas slide={slide} theme={deck.theme} number={i} showNumber={deck.showSlideNumbers} eagerImages draft/></section>)}</main>}</div>;}
function DownloadIcon(){return <FileUp size={17}/>;}
