"use client";
import {useRef,useState} from "react";
import {Check,ClipboardPaste,Copy,ExternalLink,Sparkles} from "lucide-react";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {AI_DIFFICULTIES,AiQuestionKind,questionAiPrompt} from "@/lib/question-ai";
import {Question,QUESTION_TEMPLATES} from "@/lib/quiz";
import {QuestionImportDialog} from "./question-import";

export function QuestionAiDialog({topic,remaining,defaultSeconds,replaceEmpty,onImport,onClose}:{topic:string;remaining:number;defaultSeconds:number;replaceEmpty:boolean;onImport:(questions:Question[])=>boolean;onClose:()=>void}) {
  const limit=Math.min(20,remaining);const [subject,setSubject]=useState(topic);const [audience,setAudience]=useState("");const [count,setCount]=useState(String(Math.min(5,limit)));const [difficulty,setDifficulty]=useState("balanced");const [kind,setKind]=useState<AiQuestionKind>("multiple");const [material,setMaterial]=useState("");
  const [prompt,setPrompt]=useState("");const [copied,setCopied]=useState(false);const [copying,setCopying]=useState(false);const [error,setError]=useState("");const [review,setReview]=useState(false);const [response,setResponse]=useState("");const promptField=useRef<HTMLTextAreaElement>(null);const topicField=useRef<HTMLInputElement>(null);
  function prepare(){try{setPrompt(questionAiPrompt({topic:subject,audience,count:Number(count),difficulty,kind,seconds:defaultSeconds,material}));setCopied(false);setError("");}catch(e){setError((e as Error).message);if(!subject.trim())topicField.current?.focus();}}
  async function copy(){setCopying(true);try{await navigator.clipboard.writeText(prompt);setCopied(true);setError("");}catch{promptField.current?.focus();promptField.current?.select();setError("Não foi possível copiar automaticamente. Selecione o pedido abaixo e use Copiar no seu aparelho.");}finally{setCopying(false);}}
  if(review)return <QuestionImportDialog remaining={remaining} defaultSeconds={defaultSeconds} replaceEmpty={replaceEmpty} initialText={response} ai onTextChange={setResponse} onBack={()=>setReview(false)} onImport={questions=>onImport(questions.map(q=>kind==="scenario"&&q.kind!=="true_false"?{...q,kind:"scenario"}:q))} onClose={onClose}/>;
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="q-dialog ai-dialog"><DialogTitle><Sparkles size={21}/>Criar com IA</DialogTitle><DialogDescription>Prepare o pedido, gere as perguntas no seu ChatGPT e traga a resposta para revisar.</DialogDescription>
    <div className="ai-account-note"><b>A geração usa a conta aberta no ChatGPT.</b><p>O login no Prativerso guarda suas atividades. Aqui, você vai abrir o ChatGPT e colar o pedido na sua própria conversa; o uso segue os limites dessa conta.</p></div>
    <ol className="ai-steps" aria-label="Etapas da criação com IA"><li className={!prompt?"ai-step-current":"ai-step-done"} aria-current={!prompt?"step":undefined}><span>{prompt?<Check size={15}/>:1}</span>Preparar pedido</li><li className={prompt?"ai-step-current":""} aria-current={prompt?"step":undefined}><span>2</span>Gerar no ChatGPT</li><li><span>3</span>Revisar no Prativerso</li></ol>
    {!prompt?<>
      <label className="ai-field" htmlFor="ai-question-topic">Sobre qual assunto?<input id="ai-question-topic" ref={topicField} value={subject} maxLength={120} onChange={e=>{setSubject(e.target.value);setError("");}} placeholder="Ex.: erosão e conservação do solo"/></label>
      <label className="ai-field" htmlFor="ai-question-audience">Para qual turma? <span className="ai-optional">Opcional</span><input id="ai-question-audience" value={audience} maxLength={120} onChange={e=>setAudience(e.target.value)} placeholder="Ex.: EJA, técnico em Agroecologia, linguagem acessível"/></label>
      <div className="ai-settings"><div><label htmlFor="ai-question-count">Perguntas</label><Select value={count} onValueChange={setCount}><SelectTrigger id="ai-question-count"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:limit},(_,i)=><SelectItem value={String(i+1)} key={i}>{i+1} {i===0?"pergunta":"perguntas"}</SelectItem>)}</SelectContent></Select></div><div><label htmlFor="ai-question-difficulty">Dificuldade</label><Select value={difficulty} onValueChange={setDifficulty}><SelectTrigger id="ai-question-difficulty"><SelectValue/></SelectTrigger><SelectContent>{AI_DIFFICULTIES.map(d=><SelectItem key={d.value} value={d.value}>{d.label}</SelectItem>)}</SelectContent></Select></div></div>
      <div className="ai-field"><label htmlFor="ai-question-kind">Modelo de pergunta</label><Select value={kind} onValueChange={value=>setKind(value as AiQuestionKind)}><SelectTrigger id="ai-question-kind"><SelectValue/></SelectTrigger><SelectContent>{QUESTION_TEMPLATES.filter(t=>t.kind!=="image").map(t=><SelectItem key={t.kind} value={t.kind}>{t.label}</SelectItem>)}</SelectContent></Select></div>
      <details className="ai-material"><summary>Usar um texto de apoio <span className="ai-optional">Opcional</span></summary><label htmlFor="ai-question-material">Cole o conteúdo que a turma estudou</label><textarea id="ai-question-material" rows={6} maxLength={12000} value={material} onChange={e=>setMaterial(e.target.value)} placeholder="Cole um trecho da aula, apostila ou resumo. As perguntas serão solicitadas com base nesse conteúdo."/><p className="field-help">{material.length.toLocaleString("pt-BR")}/12.000 caracteres. O texto só vai ao ChatGPT quando você copiar e enviar o pedido.</p></details>
      <div className="ai-bottom-actions"><button className="text-button" onClick={()=>setReview(true)}>Já tenho uma resposta da IA</button><button className="btn btn-primary" onClick={prepare} disabled={limit<1}><Sparkles size={18}/>Preparar pedido</button></div>
    </>:<>
      <div className="ai-prompt-heading"><b>{count} perguntas · {QUESTION_TEMPLATES.find(t=>t.kind===kind)?.label}</b><button className="text-button" onClick={()=>{setPrompt("");setCopied(false);setError("");}}>Editar pedido</button></div>
      <div className="ai-prompt-actions"><button className="btn btn-primary" onClick={copy} disabled={copying}>{copied?<Check size={18}/>:<Copy size={18}/>} {copied?"Pedido copiado":"Copiar pedido"}</button><a className="btn btn-outline" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/>Abrir ChatGPT</a></div>
      <p className="ai-instruction">Cole o pedido no ChatGPT e envie. Depois, copie a resposta completa e volte a esta janela. Abrir o ChatGPT mantém o seu quiz aqui.</p>
      <label htmlFor="ai-question-prompt">Pedido pronto para copiar</label><textarea id="ai-question-prompt" ref={promptField} className="ai-prompt" readOnly value={prompt} rows={10}/>
      <div className="ai-bottom-actions"><p>As perguntas só entram no rascunho depois da sua revisão.</p><button className="btn btn-primary" onClick={()=>setReview(true)}><ClipboardPaste size={18}/>Colar resposta e revisar</button></div>
    </>}
    {error&&<p className="form-error" role="alert">{error}</p>}
  </DialogContent></Dialog>;
}
