"use client";
import {useRef,useState} from "react";
import {Check,ClipboardPaste,Download,FileSpreadsheet,Loader2} from "lucide-react";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {ImportItem,IMPORT_CSV,IMPORT_EXAMPLE,parseQuestionCsv,parseQuestionRows,parseQuestionText,QuestionImport} from "@/lib/question-import";
import {LETTERS,Question,questionIssues} from "@/lib/quiz";

export function QuestionImportDialog({remaining,defaultSeconds,replaceEmpty,onImport,onClose,initialText="",ai=false,onTextChange,onBack}:{remaining:number;defaultSeconds:number;replaceEmpty:boolean;onImport:(questions:Question[])=>boolean;onClose:()=>void;initialText?:string;ai?:boolean;onTextChange?:(text:string)=>void;onBack?:()=>void}) {
  const [text,setText]=useState(initialText);const [result,setResult]=useState<QuestionImport|null>(null);const [selection,setSelection]=useState<number[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [source,setSource]=useState("");const file=useRef<HTMLInputElement>(null);const token=useRef(0);
  function changeText(value:string){setText(value);onTextChange?.(value);}
  function reviewed(parsed:QuestionImport,label:string){if(!parsed.items.length)throw new Error("Nenhuma pergunta encontrada. Use o exemplo ou confira os cabeçalhos da planilha.");setResult(parsed);setSource(label);setSelection(parsed.items.map((row,i)=>!row.fatal.length?i:-1).filter(i=>i>=0).slice(0,remaining));setError("");}
  function reviewText(){try{reviewed(parseQuestionText(text,defaultSeconds),"Texto colado");}catch(e){setError((e as Error).message);}}
  async function readFile(uploaded:File){const current=++token.current;setBusy(true);setError("");try{
    const extension=uploaded.name.split(".").pop()?.toLowerCase();let parsed:QuestionImport;
    if(extension==="xlsx"){if(uploaded.size>3*1024*1024)throw new Error("Use um arquivo Excel de até 3 MB.");const {readSheet}=await import("read-excel-file/universal");const rows=await readSheet(uploaded);parsed=parseQuestionRows(rows,defaultSeconds);}
    else if(["csv","txt"].includes(extension||"")){if(uploaded.size>524288)throw new Error("Use um CSV ou texto de até 512 KB.");const content=await uploaded.text();parsed=extension==="csv"?parseQuestionCsv(content,defaultSeconds):parseQuestionText(content,defaultSeconds);if(current===token.current)changeText(extension==="txt"?content:"");}
    else throw new Error("Escolha um arquivo CSV, XLSX ou TXT. Para uma atividade do Word, copie e cole o texto.");
    if(current===token.current)reviewed(parsed,uploaded.name);
  }catch(e){if(current===token.current)setError((e as Error).message.includes("Use ")||(e as Error).message.includes("planilha")||(e as Error).message.includes("CSV")||(e as Error).message.includes("pergunta")?(e as Error).message:"Não foi possível ler esse arquivo. Confira se ele está íntegro ou use o modelo CSV.");}finally{if(current===token.current)setBusy(false);}}
  function reset(){token.current++;setResult(null);setError("");setBusy(false);}
  function download(){const url=URL.createObjectURL(new Blob([IMPORT_CSV],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="QuizEdu-modelo-perguntas.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function toggle(i:number,on:boolean){setSelection(old=>on?[...old,i]:old.filter(at=>at!==i));}
  function rowIssues(row:ImportItem){return [...row.fatal,...questionIssues(row.question).map(i=>i.message),...row.notes];}
  const pending=result?selection.filter(i=>questionIssues(result.items[i].question).some(issue=>issue.severity==="error")).length:0;
  return <Dialog open onOpenChange={open=>{if(!open){token.current++;onClose();}}}><DialogContent className="q-dialog import-dialog"><DialogTitle>{ai?"Revisar perguntas da IA":"Adicionar várias perguntas"}</DialogTitle><DialogDescription>{replaceEmpty?"A pergunta vazia será substituída pela seleção.":"A seleção será inserida depois da pergunta atual."} Você pode adicionar até {remaining} nesta atividade.</DialogDescription>
    {ai&&<div className="authoring-notice"><b>Confira os fatos e o gabarito antes de usar com a turma.</b><p>A IA pode errar. A revisão automática confere os campos preenchidos; a conferência do conteúdo fica com você.</p></div>}
    {!result?<>{onBack&&<button className="text-button" onClick={()=>{token.current++;onBack();}}>Voltar ao pedido</button>}<label htmlFor="question-list-paste">{ai?"Cole a resposta completa do ChatGPT":"Cole sua atividade com alternativas e gabarito"}</label><textarea id="question-list-paste" className="import-text" rows={12} maxLength={524288} value={text} onChange={e=>{token.current++;setBusy(false);changeText(e.target.value);setError("");}} placeholder={IMPORT_EXAMPLE}/><p className="field-help">Use A), B), C), D) e “Resposta: A”. Para verdadeiro ou falso, use “Resposta: Verdadeiro” ou “Resposta: Falso”.</p><div className="import-source-actions"><button className="btn btn-primary" onClick={reviewText} disabled={!text.trim()||busy}><ClipboardPaste size={18}/>Revisar perguntas</button><button className="btn btn-outline" onClick={()=>file.current?.click()} disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<FileSpreadsheet size={17}/>}Importar arquivo</button>{!ai&&<button className="btn btn-quiet" onClick={()=>changeText(IMPORT_EXAMPLE)} disabled={busy}>Usar exemplo</button>}</div><div className="import-file-help"><button className="text-button" onClick={download}><Download size={16}/>Baixar modelo de planilha</button><p>CSV, Excel (.xlsx) ou texto (.txt). No Excel, as perguntas devem estar na primeira aba.</p></div><input hidden type="file" ref={file} accept=".csv,.xlsx,.txt" onChange={e=>{const uploaded=e.target.files?.[0];if(uploaded)void readFile(uploaded);e.target.value="";}}/></>:<>
      <div className="import-review-heading"><div><b>{result.items.length} perguntas encontradas</b><small>{source} · confira as alternativas e o gabarito</small></div><button className="btn btn-outline" onClick={reset}>Voltar à importação</button></div>
      {result.notes.length>0&&<div className="authoring-notice">{result.notes.map((note,i)=><p key={i}>{note}</p>)}</div>}
      <div className="import-selection"><button className="text-button" onClick={()=>setSelection(result.items.map((r,i)=>r.fatal.length?-1:i).filter(i=>i>=0).slice(0,remaining))}>Selecionar até {remaining}</button><button className="text-button" onClick={()=>setSelection([])}>Limpar seleção</button><span>{selection.length} selecionadas</span></div>
      <div className="import-review-list">{result.items.map((row,i)=>{const issues=rowIssues(row);return <article className={`import-question ${row.fatal.length?"import-question-blocked":""}`} key={row.question.id}><Checkbox checked={selection.includes(i)} onCheckedChange={checked=>toggle(i,!!checked)} disabled={!!row.fatal.length} aria-label={`Adicionar pergunta ${i+1}: ${row.question.text}`}/><div><span className="import-source">{row.source} · {row.question.seconds}s</span><h3>{i+1}. {row.question.text||"Enunciado vazio"}</h3><details open={issues.length>0}><summary>{row.question.correct<0?"Gabarito a marcar":`Correta: ${LETTERS[row.question.correct]}`} · ver alternativas</summary><ul>{row.question.options.map((o,at)=><li key={at} className={at===row.question.correct?"import-correct":""}><b>{LETTERS[at]||String.fromCharCode(65+at)}</b><span>{o||"Alternativa vazia"}</span>{at===row.question.correct&&<Check size={16}/>}</li>)}</ul>{row.question.explanation&&<p className="import-explanation">{row.question.explanation}</p>}</details>{issues.length>0&&<div className="import-issues">{[...new Set(issues)].map((issue,at)=><p key={at}>{issue}</p>)}</div>}</div></article>;})}</div>
      <div className="import-review-footer"><p>{pending?`${pending} da seleção precisam ser completadas no editor antes de jogar.`:"As perguntas selecionadas têm os campos obrigatórios preenchidos."}{selection.length>remaining&&` Selecione até ${remaining}.`}</p><button className="btn btn-primary" disabled={!selection.length||selection.length>remaining} onClick={()=>{if(onImport(selection.map(i=>({...structuredClone(result.items[i].question),id:crypto.randomUUID()}))))onClose();}}>Adicionar {selection.length} {selection.length===1?"pergunta":"perguntas"}</button></div>
    </>}
    {error&&<p className="form-error" role="alert">{error}</p>}
  </DialogContent></Dialog>;
}
