"use client";
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { Check, Clock3, Copy, Expand, Home, Loader2, Play, QrCode, Trophy, Users, X } from "lucide-react";
import { toast } from "sonner";
import { Progress } from "@/components/ui/progress";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { api, Brand, Loading, Notifications, Offline, useClock } from "./shared";
import { Podium, Ranking, useRoom } from "./room-shared";
import { LETTERS, RoomState } from "@/lib/quiz";

export function RoomHost({ code }: { code: string }) {
  const { state, error, refresh, apply } = useRoom(code); const [qr, setQr] = useState(""); const [link, setLink] = useState(""); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<"close" | "end_round" | null>(null);
  const seconds = useClock(state?.serverNow || 0, state?.endsAt || null); const countdown = useClock(state?.serverNow || 0, state?.startsAt || null);
  useEffect(() => { const url = `${window.location.origin}/participar/${code}`; setLink(url); QRCode.toDataURL(url, { width: 320, margin: 3, errorCorrectionLevel: "M", color: { dark: "#172554", light: "#ffffff" } }).then(setQr).catch(() => toast.error("Não foi possível gerar o QR code. Use o código da sala.")); }, [code]);
  async function action(action: string, playerId?: string) { if (!state) return; setBusy(true); try { const next = await api<RoomState>(`/api/rooms/${code}/control`, { action, index: state.index, status: state.status, playerId }); apply(next); } catch (e) { toast.error((e as Error).message); void refresh().catch(() => {}); } finally { setBusy(false); setConfirm(null); } }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); toast.success("Link copiado."); } catch { toast.error("Não foi possível copiar. Compartilhe o código da sala."); } }
  async function fullscreen() { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch { toast.info("Use o modo de tela inteira do navegador."); } }
  if (!state) return <div className="room-shell"><header className="room-topbar"><Brand dark /></header>{error ? <div className="room-error"><h1>Vamos encontrar sua sala</h1><p>{error}</p><button className="btn btn-lime" onClick={() => refresh()}>Tentar novamente</button><a href="/" className="light-link">Voltar ao início</a></div> : <Loading label="Abrindo a sala…" />}</div>;
  if (!state.isHost) return <div className="room-shell"><header className="room-topbar"><Brand dark /></header><div className="room-error"><h1>Esta é a tela do professor</h1><p>Abra esta sala no navegador em que você criou o quiz.</p><a className="btn btn-lime" href={`/participar/${code}`}>Entrar como participante</a><a className="light-link" href="/">Voltar ao início</a></div></div>;
  const lobby = state.status === "lobby"; const final = state.status === "finished"; const closed = state.status === "closed";
  return <div className={`room-shell ${final ? "final-shell" : ""}`}><header className="room-topbar"><Brand dark /><span className="room-title">{state.title}</span><div className="room-top-actions"><span className="room-code-small">SALA <b>{code}</b></span><button aria-label="Alternar tela inteira" className="room-icon-button" onClick={fullscreen}><Expand size={20} /></button>{!closed && !final && <button className="room-icon-button" aria-label="Encerrar sala" onClick={() => setConfirm("close")}><X size={21} /></button>}</div></header>
    {error && <Offline text="Conexão interrompida. Estamos tentando reconectar à sala…" />}
    {lobby && <main className="lobby-workspace"><div className="lobby-heading"><span className="badge badge-lime">SALA ABERTA</span><h1>Todo mundo pronto?</h1><p>Convide sua turma. O jogo começa quando você decidir.</p></div><div className="lobby-join-card"><div className="qr-box">{qr ? <img src={qr} width={228} height={228} alt={`QR code para entrar na sala ${code}`} /> : <Loader2 className="spin" />}<button onClick={() => copy(link)}><Copy size={16} />Copiar link da sala</button></div><div className="join-code"><p>APONTE A CÂMERA OU DIGITE O CÓDIGO</p><div className="large-room-code" aria-label={`Código ${code}`}>{code.slice(0, 3)}<span>{code.slice(3)}</span></div><span>Abra <b>{typeof window !== "undefined" ? window.location.host : "QuizEdu"}</b><br />e toque em “Entrar em uma sala”.</span></div><aside className="lobby-tutorial"><h2><QrCode size={20} />Como participar</h2><ol><li><span>1</span>Leia o QR code com o celular.</li><li><span>2</span>Escolha um nome e um avatar.</li><li><span>3</span>Toque em entrar e aguarde.</li></ol></aside></div><div className="lobby-players-heading"><h2><Users size={22} />{state.players.length} {state.players.length === 1 ? "participante" : "participantes"}<span>/ 100</span></h2><button className="btn btn-lime" disabled={!state.players.length || busy} onClick={() => action("start")}>{busy ? <Loader2 className="spin" size={19} /> : <Play size={18} fill="currentColor" />}Iniciar quiz</button></div>{state.players.length ? <div className="player-cloud">{state.players.map(p => <div key={p.id} className="lobby-player"><span>{p.avatar}</span><b>{p.name}</b><button aria-label={`Remover ${p.name} da sala`} onClick={() => action("kick", p.id)} disabled={busy}><X size={14} /></button></div>)}</div> : <div className="waiting-empty"><Users size={32} /><p>Os participantes vão aparecer aqui.</p><span>Deixe esta tela aberta enquanto a turma entra.</span></div>}<p className="room-help">A sala fica disponível por 24 horas. Cada participante precisa de conexão com a internet.</p></main>}
    {state.status === "question" && state.question && <main className="live-workspace"><div className="live-meta"><span>PERGUNTA <b>{state.index + 1}</b> DE {state.total}</span><span><Users size={19} />{state.answeredCount}/{state.players.length} responderam</span></div>{countdown > 0 ? <div className="round-countdown"><p>Prepare-se para a pergunta</p><strong key={countdown}>{countdown}</strong><span>A turma já está conectada.</span></div> : <><div className={`host-timer ${seconds <= 5 ? "timer-urgent" : ""}`}><Clock3 size={25} /><strong>{seconds}</strong><span>segundos</span></div><h1 className="host-question">{state.question.text}</h1><div className="host-options">{state.question.options.map((option, i) => <div className={`answer-option option-${i}`} key={i}><span className="letter">{LETTERS[i]}</span><span>{option}</span></div>)}</div><Progress className="time-progress" value={Math.max(0, Math.min(100, seconds / state.question.seconds * 100))} aria-label="Tempo restante da pergunta" /><div className="live-bottom"><span>{seconds ? "Leia com atenção. A rapidez também conta!" : "Tempo encerrado. Preparando o placar…"}</span><button className="btn btn-room-outline" disabled={busy || !seconds} onClick={() => setConfirm("end_round")}>Encerrar rodada</button></div></>}</main>}
    {state.status === "results" && state.question && <main className="results-workspace"><div className="results-heading"><div><span className="badge badge-lime">RODADA {state.index + 1} CONCLUÍDA</span><h1>Olha o placar!</h1><p>A pontuação continua na próxima rodada.</p></div><button className="btn btn-lime" onClick={() => action("next")} disabled={busy}>{busy ? <Loader2 size={18} className="spin" /> : state.index + 1 === state.total ? <Trophy size={19} /> : <Play size={18} fill="currentColor" />}{state.index + 1 === state.total ? "Ver resultado final" : "Próxima pergunta"}</button></div><div className="results-grid"><section><Ranking players={state.players} /></section><aside className="answer-reveal"><span className="eyebrow">RESPOSTA CORRETA</span><span className="reveal-check"><Check size={26} /></span><h2>{state.question.options[state.correct!]}</h2><p className="reveal-question">{state.question.text}</p>{state.explanation && <p className="reveal-explanation">{state.explanation}</p>}<div className="reveal-stats"><b>{state.players.filter(p => p.roundCorrect).length}<span>acertaram</span></b><b>{state.players.length - state.answeredCount}<span>sem resposta</span></b></div><p className="ranking-rule">Acerto + rapidez. Em empate de pontos, mais acertos e menor tempo total de respostas corretas.</p></aside></div></main>}
    {final && <main className="final-workspace"><div className="final-heading"><span className="badge badge-lime">QUIZ CONCLUÍDO</span><h1>Uma turma de campeões<span>!</span></h1><p>{state.title} · {state.total} {state.total === 1 ? "pergunta" : "perguntas"} · {state.players.length} participantes</p></div><Podium players={state.players} />{state.players.length > 2 && <section className="final-rest"><h2>Todo mundo fez parte</h2><Ranking players={state.players.slice(2)} final /></section>}<a className="btn btn-lime" href="/"><Home size={18} />Voltar aos meus quizzes</a></main>}
    {closed && <main className="room-error"><h1>Sala encerrada</h1><p>Você pode abrir uma nova sala usando o mesmo quiz.</p><a className="btn btn-lime" href="/">Voltar aos meus quizzes</a></main>}
    <AlertDialog open={!!confirm} onOpenChange={v => { if (!v) setConfirm(null); }}><AlertDialogContent className="q-dialog"><AlertDialogTitle>{confirm === "close" ? "Encerrar esta sala?" : "Encerrar a rodada agora?"}</AlertDialogTitle><AlertDialogDescription>{confirm === "close" ? "Os participantes não poderão continuar respondendo. Seu quiz fica salvo para jogar de novo." : "As respostas já enviadas serão contabilizadas. Quem ainda não respondeu ficará sem pontos nesta pergunta."}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => action(confirm!)}>Sim, encerrar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Notifications />
  </div>;
}
