"use client";
import { useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { Check, Clock3, Copy, Expand, FileText, Home, Loader2, Play, QrCode, Trophy, Users, X } from "lucide-react";
import { toast } from "sonner";
import { Progress } from "@/components/ui/progress";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { api, Brand, Loading, Notifications, Offline, useClock } from "./shared";
import { Podium, Ranking, useRoom } from "./room-shared";
import { ConnectionCheck, useGamePreferences } from "./learning-tools";
import { AnswerOptions, QuestionHeading } from "./question-view";
import { PresentationLive } from "./presentation-live";
import { LETTERS, RoomState } from "@/lib/quiz";

export function RoomHost({code,projection=false}:{code:string;projection?:boolean}) {
  const {state,error,refresh,apply}=useRoom(code);const [qr,setQr]=useState("");const [link,setLink]=useState("");const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState<"close"|"end_round"|null>(null);const preferences=useGamePreferences();const phase=useRef("");
  const seconds=useClock(state?.serverNow||0,state?.endsAt||null,state?.clock);const countdown=useClock(state?.serverNow||0,state?.startsAt||null,state?.clock);
  useEffect(()=>{const url=`${window.location.origin}/participar/${code}`;setLink(url);QRCode.toDataURL(url,{width:320,margin:3,errorCorrectionLevel:"M",color:{dark:"#172554",light:"#ffffff"}}).then(setQr).catch(()=>toast.error("Não foi possível gerar o QR code. Use o código da sala."));},[code]);
  useEffect(()=>{if(!state)return;const key=`${state.status}:${state.index}`;if(phase.current&&phase.current!==key&&["question","results","finished"].includes(state.status))preferences.tone(state.status==="finished");phase.current=key;},[state?.status,state?.index]);
  async function action(action:string,playerId?:string){if(!state)return;setBusy(true);try{const next=await api<RoomState>(`/api/rooms/${code}/control`,{action,index:state.index,status:state.status,playerId,...(state.presentation?{slideIndex:state.presentation.index,step:state.presentation.step}:{})});apply(next);}catch(e){toast.error((e as Error).message);void refresh().catch(()=>{});}finally{setBusy(false);setConfirm(null);}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success("Link copiado.");}catch{toast.info("Compartilhe o código de seis números.");}}
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast.info("Use o modo de tela inteira do navegador.");}}
  if(!state)return <div className="room-shell"><header className="room-topbar"><Brand dark/></header>{error?<div className="room-error"><h1>Vamos encontrar sua sala</h1><p>{error}</p><button className="btn btn-lime" onClick={()=>refresh()}>Tentar novamente</button><a href="/" className="light-link">Voltar ao início</a></div>:<Loading label="Abrindo a sala…"/>}</div>;
  if(!state.isHost)return <div className="room-shell"><header className="room-topbar"><Brand dark/></header><div className="room-error"><h1>Esta é a tela do professor</h1><p>Entre no seu acesso de educador para conduzir esta sala.</p><a className="btn btn-lime" href="/">Acessar meus quizzes</a><a className="light-link" href={`/participar/${code}`}>Entrar como participante</a></div></div>;
  if(state.presentation&&!["lobby","finished","closed"].includes(state.status))return <PresentationLive state={state} error={error} apply={apply} refresh={refresh} projection={projection}/>;
  const lobby=state.status==="lobby",final=state.status==="finished",closed=state.status==="closed";const noContact=state.players.filter(p=>state.serverNow-(state.presence?.[p.id]||p.lastSeen||0)>40000);
  return <div className={`room-shell ${final?"final-shell":""}`} style={{"--read-scale":preferences.scale} as React.CSSProperties}><header className="room-topbar"><Brand dark/><span className="room-title">{state.title}</span><div className="room-top-actions"><span className="room-code-small">SALA <b>{code}</b></span><button aria-label="Alternar tela inteira" className="room-icon-button" onClick={fullscreen}><Expand size={20}/></button>{!closed&&!final&&<button className="room-icon-button" aria-label="Encerrar sala" onClick={()=>setConfirm("close")}><X size={21}/></button>}</div></header>
    {error&&<Offline text="Conexão interrompida. Estamos tentando reconectar à sala…"/>}
    {!final&&!closed&&<div className="room-preferences"><span className="room-mode-label">{state.mode==="accuracy"?"Aprendizagem · acertos valem 1.000 pontos":"Competição · 1º acerto: 1.000 · demais: até 700"}{state.untimed&&" · tempo livre"}</span>{preferences.controls}</div>}
    {lobby&&<main className="lobby-workspace"><div className="lobby-heading"><span className="badge badge-lime">SALA ABERTA</span><h1>Todo mundo pronto?</h1><p>Convide sua turma. O jogo começa quando você decidir.</p></div><div className="lobby-join-card"><div className="qr-box">{qr?<img src={qr} width={228} height={228} alt={`QR code para entrar na sala ${code}`}/>:<Loader2 className="spin"/>}<button onClick={()=>copy(link)}><Copy size={16}/>Copiar link da sala</button></div><div className="join-code"><p>APONTE A CÂMERA OU DIGITE O CÓDIGO</p><div className="large-room-code" aria-label={`Código ${code}`}>{code.slice(0,3)}<span>{code.slice(3)}</span></div><span>Abra <b>{typeof window!=="undefined"?window.location.host:"QuizEdu"}</b><br/>e toque em “Entrar em uma sala”.</span></div><aside className="lobby-tutorial"><h2><QrCode size={20}/>Como participar</h2><ol><li><span>1</span>Leia o QR code com o celular.</li><li><span>2</span>Escolha um nome e um avatar.</li><li><span>3</span>Toque em entrar e aguarde.</li></ol></aside></div>
      <div className="lobby-support"><ConnectionCheck/><p>{noContact.length?`${noContact.length} participante(s) sem contato recente. Peça para manterem a página aberta.`:"Os participantes enviam sinais de presença enquanto a página está aberta."}</p></div>
      <div className="lobby-players-heading"><h2><Users size={22}/>{state.players.length} {state.players.length===1?"participante":"participantes"}<span>/ 100</span></h2><button className="btn btn-lime" disabled={(!state.players.length&&!state.presentation)||busy||!!error} onClick={()=>action("start")}>{busy?<Loader2 className="spin" size={19}/>:<Play size={18} fill="currentColor"/>}{state.presentation?"Iniciar aula":"Iniciar quiz"}</button></div>
      {state.players.length?<div className="player-cloud">{state.players.map(p=>{const recent=state.serverNow-(state.presence?.[p.id]||p.lastSeen||0)<=40000;return <div key={p.id} className="lobby-player"><span>{p.avatar}</span><div><b>{p.name}</b><small className={recent?"presence-recent":"presence-stale"}>{recent?"Contato recente":"Sem contato recente"}</small></div><button aria-label={`Remover ${p.name} da sala`} onClick={()=>action("kick",p.id)} disabled={busy}><X size={14}/></button></div>;})}</div>:<div className="waiting-empty"><Users size={32}/><p>Os participantes vão aparecer aqui.</p><span>Deixe esta tela aberta enquanto a turma entra.</span></div>}<p className="room-help">A sala dura 24 horas. O relatório continua no histórico do seu acesso.</p></main>}
    {state.status==="question"&&state.question&&<main className="live-workspace"><div className="live-meta"><span>PERGUNTA <b>{state.index+1}</b> DE {state.total}</span><span><Users size={19}/>{state.answeredCount}/{state.players.length} responderam</span></div>{countdown>0?<div className="round-countdown"><p>Prepare-se para a pergunta</p><strong key={countdown}>{countdown}</strong><span>Leia e escolha sua resposta.</span></div>:<><div className={`host-timer ${!state.untimed&&seconds<=5?"timer-urgent":""}`}><Clock3 size={25}/>{state.untimed?<strong className="free-time-label">Tempo livre</strong>:<><strong>{seconds}</strong><span>segundos</span></>}</div><QuestionHeading question={state.question} host/><AnswerOptions question={state.question}/><Progress className="time-progress" value={state.untimed?state.answeredCount/Math.max(1,state.players.length)*100:Math.max(0,Math.min(100,seconds/state.question.seconds*100))} aria-label={state.untimed?"Participantes que responderam":"Tempo restante da pergunta"}/><div className="live-bottom"><span>{state.untimed?"Aguarde as respostas ou encerre a rodada quando desejar.":seconds?(state.mode==="accuracy"?"Leia com atenção. Cada acerto vale os mesmos pontos.":"Leia com atenção. A rapidez também conta!"):"Tempo encerrado. Preparando o placar…"}</span><button className="btn btn-room-outline" disabled={busy||(!state.untimed&&!seconds)||!!error} onClick={()=>setConfirm("end_round")}>Encerrar rodada</button></div>{noContact.length>0&&<p className="live-contact-note">Sem contato recente: {noContact.map(p=>p.name).join(", ")}</p>}</>}</main>}
    {state.status==="results"&&state.question&&<main className="results-workspace"><div className="results-heading"><div><span className="badge badge-lime">RODADA {state.index+1} CONCLUÍDA</span><h1>Olha o placar!</h1><p>A pontuação continua na próxima rodada.</p></div><button className="btn btn-lime" onClick={()=>action("next")} disabled={busy||!!error}>{busy?<Loader2 size={18} className="spin"/>:state.index+1===state.total?<Trophy size={19}/>:<Play size={18} fill="currentColor"/>}{state.index+1===state.total?"Ver resultado final":"Próxima pergunta"}</button></div><div className="results-grid"><section><Ranking players={state.players}/></section><aside className="answer-reveal"><span className="eyebrow">RESPOSTA CORRETA</span><span className="reveal-check"><Check size={26}/></span><h2>{state.question.options[state.correct!]}</h2>{state.question.optionImages?.[state.correct!]&&<img className="reveal-image" src={state.question.optionImages[state.correct!]} alt={state.question.options[state.correct!]}/>}<p className="reveal-question">{state.question.text}</p>{state.explanation&&<p className="reveal-explanation">{state.explanation}</p>}<div className="reveal-stats"><b>{state.players.filter(p=>p.roundCorrect).length}<span>acertaram</span></b><b>{state.players.length-state.answeredCount}<span>sem resposta</span></b></div><p className="ranking-rule">{state.mode==="accuracy"?"1.000 pontos por acerto. A rapidez não muda os pontos; empates mantêm a ordem de entrada.":"O primeiro acerto vale 1.000 pontos. Os demais valem 700 menos a redução pelo tempo. Empates usam mais acertos, menor tempo nos acertos e ordem de entrada."}</p></aside></div></main>}
    {final&&<main className="final-workspace"><div className="final-heading"><span className="badge badge-lime">{state.presentation?"AULA CONCLUÍDA":"QUIZ CONCLUÍDO"}</span><h1>Uma turma de campeões<span>!</span></h1><p>{state.title} · {state.total} perguntas · {state.players.length} participantes</p></div><Podium players={state.players}/>{state.players.length>2&&<section className="final-rest"><h2>Todo mundo fez parte</h2><Ranking players={state.players.slice(2)} final/></section>}<div className="final-actions"><a className="btn btn-lime" href={`/relatorio/${code}`}><FileText size={18}/>Ver relatório da aula</a><a className="btn btn-room-outline" href="/"><Home size={18}/>Meus quizzes</a></div></main>}
    {closed&&<main className="room-error"><h1>Sala encerrada</h1><p>Você pode abrir outra sala com o mesmo quiz e consultar as respostas desta aula.</p><a className="btn btn-lime" href={`/relatorio/${code}`}><FileText size={18}/>Ver relatório</a><a className="light-link" href="/">Voltar aos meus quizzes</a></main>}
    <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null);}}><AlertDialogContent className="q-dialog"><AlertDialogTitle>{confirm==="close"?"Encerrar esta sala?":"Encerrar a rodada agora?"}</AlertDialogTitle><AlertDialogDescription>{confirm==="close"?"Os participantes não poderão continuar respondendo. O quiz e o relatório ficam no seu acesso.":"As respostas enviadas serão contabilizadas. Quem não respondeu ficará sem pontos nesta pergunta."}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>action(confirm!)}>Sim, encerrar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Notifications/>
  </div>;
}
