"use client";
import { useEffect, useState } from "react";
import { Check, Copy, GraduationCap, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { LETTERS, Profile, Quiz } from "@/lib/quiz";
import { api, Brand, Loading, Notifications } from "./shared";
import { QuestionImage } from "./learning-tools";
import { moveLocalDrafts } from "./draft-storage";
export function SharedQuizView({token,signInHref}:{token:string;signInHref:string}) {
  const [quiz,setQuiz]=useState<Quiz|null>(null);const [error,setError]=useState("");const [profileOpen,setProfileOpen]=useState(false);const [name,setName]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<{quiz:Quiz}>(`/api/shares/${token}`).then(data=>setQuiz(data.quiz)).catch(e=>setError(e.message));},[token]);
  async function copy(){setBusy(true);try{const data=await api<{profile:Profile|null;identity:{name:string}|null}>("/api/dashboard");if(data.identity&&!data.profile?.permanent){const linked=await api<{profile:Profile}>("/api/account/link",{name:data.profile?.name||data.identity.name});if(data.profile)moveLocalDrafts(data.profile.id,linked.profile.id);}else if(!data.profile){setProfileOpen(true);setBusy(false);return;}await api(`/api/shares/${token}/copy`,{});window.location.assign("/");}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function register(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api("/api/profile",{name});setProfileOpen(false);await copy();}catch(e){toast.error((e as Error).message);setBusy(false);}}
  return <div className="app-shell"><header className="topbar"><Brand/><a className="btn btn-outline" href="/">Meus quizzes</a></header><main className="workspace share-workspace">{error?<div className="empty-panel"><h1>Compartilhamento indisponível</h1><p>{error}</p><a className="btn btn-primary" href="/">Voltar ao início</a></div>:!quiz?<Loading label="Abrindo o quiz compartilhado…"/>:<><div className="page-heading"><div><p className="eyebrow">CÓPIA COMPARTILHADA ENTRE EDUCADORES</p><h1>{quiz.title}</h1><p className="muted">{quiz.questions.length} perguntas · {quiz.mode==="accuracy"?"Aprendizagem":"Competição"}{quiz.untimed?" · tempo livre":""}</p></div><button className="btn btn-primary" disabled={busy} onClick={copy}>{busy?<Loader2 size={18} className="spin"/>:<Copy size={18}/>}Copiar para meus quizzes</button></div><p className="share-intro">A cópia será sua: você poderá editar as perguntas e abrir suas próprias salas.</p><div className="shared-question-list">{quiz.questions.map((q,i)=><article className="report-question" key={q.id}><span className="eyebrow">PERGUNTA {i+1}</span><h2>{q.text}</h2><QuestionImage url={q.image} alt={q.imageAlt}/><ol className="shared-alternatives">{q.options.map((o,at)=><li key={at} className={at===q.correct?"shared-correct":""}><span>{LETTERS[at]}</span>{q.optionImages?.[at]&&<img src={q.optionImages[at]} alt={o} className="option-image"/>}<b>{o}</b>{at===q.correct&&<Check size={17}/>}</li>)}</ol>{q.explanation&&<p className="report-explanation">{q.explanation}</p>}</article>)}</div></>}
  </main><Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="q-dialog"><DialogTitle>Guardar esta cópia</DialogTitle><DialogDescription>Entre com sua conta permanente ou escolha um nome para experimentar.</DialogDescription><a className="btn btn-primary" href={signInHref} target="_top">Continuar com ChatGPT</a><form className="form-stack" onSubmit={register}><label htmlFor="copy-name">Seu nome<input id="copy-name" required minLength={2} maxLength={30} value={name} onChange={e=>setName(e.target.value)} placeholder="Professor Emanuel"/></label><button className="btn btn-outline" disabled={busy}><GraduationCap size={17}/>Experimentar e copiar</button></form></DialogContent></Dialog><Notifications/></div>;
}
