"use client";
import {useEffect,useRef,useState} from "react";
import {Image as ImageIcon,Play} from "lucide-react";
import {color,LessonSlide,PublicSlide,RichNode,safeLink,SlideElement,SLIDE_HEIGHT,SLIDE_WIDTH,themeFor} from "@/lib/presentation";
import type {Question} from "@/lib/quiz";

export function RichContent({node,interactive=false}:{node:RichNode;interactive?:boolean}) {
  if(node.type==="text"){let content:React.ReactNode=node.text||"";for(const mark of node.marks||[]){if(mark.type==="bold")content=<strong>{content}</strong>;else if(mark.type==="italic")content=<em>{content}</em>;else if(mark.type==="underline")content=<u>{content}</u>;else if(mark.type==="strike")content=<s>{content}</s>;else if(mark.type==="code")content=<code>{content}</code>;else if(mark.type==="link"){const href=safeLink(mark.attrs?.href);if(href)content=interactive?<a href={href} target="_blank" rel="noopener noreferrer">{content}</a>:<span style={{textDecoration:"underline"}}>{content}</span>;}else if(mark.type==="textStyle"){const a=mark.attrs||{};content=<span style={{color:color(a.color)?a.color:undefined,backgroundColor:color(a.backgroundColor)?a.backgroundColor:undefined,fontFamily:typeof a.fontFamily==="string"?a.fontFamily:undefined,fontSize:typeof a.fontSize==="string"?a.fontSize:undefined,lineHeight:typeof a.lineHeight==="string"?a.lineHeight:undefined}}>{content}</span>;}}return <>{content}</>;}
  const children=(node.content||[]).map((c,i)=><RichContent node={c} interactive={interactive} key={i}/>);const style={textAlign:node.attrs?.textAlign as React.CSSProperties["textAlign"]};
  if(node.type==="paragraph")return <p style={style}>{children.length?children:<br/>}</p>;
  if(node.type==="heading"){const Tag=`h${Math.min(6,Math.max(1,Number(node.attrs?.level)||1))}` as "h1";return <Tag style={style}>{children}</Tag>;}
  if(node.type==="bulletList")return <ul>{children}</ul>;if(node.type==="orderedList")return <ol start={Number(node.attrs?.start)||1}>{children}</ol>;if(node.type==="listItem")return <li>{children}</li>;if(node.type==="hardBreak")return <br/>;if(node.type==="blockquote")return <blockquote>{children}</blockquote>;if(node.type==="horizontalRule")return <hr/>;return <>{children}</>;
}
const chartColors=["#3155ed","#168653","#d77b08","#863de5","#d33658","#087eaa","#65708a","#2e5376"];
export function SlideChart({element:e}:{element:SlideElement}) {
  const values=e.values||[],labels=e.labels||[],max=Math.max(1,...values),sum=values.reduce((s,v)=>s+v,0);const accent=e.fill||chartColors[0];
  if(e.chart==="pie"){let angle=-Math.PI/2;return <div className="slide-pie-layout"><svg viewBox="0 0 300 300" role="img" aria-label={labels.map((l,i)=>`${l}: ${values[i]}`).join(", ")}>{values.map((v,i)=>{if(v<=0||sum<=0)return null;const end=angle+v/sum*Math.PI*2;const x=150+130*Math.cos(angle),y=150+130*Math.sin(angle),ex=150+130*Math.cos(end),ey=150+130*Math.sin(end);const d=v===sum?"M150 20 A130 130 0 1 1 149.99 20Z":`M150 150 L${x} ${y} A130 130 0 ${end-angle>Math.PI?1:0} 1 ${ex} ${ey}Z`;angle=end;return <path d={d} key={i} fill={i===0?accent:chartColors[i%chartColors.length]} stroke="#fff" strokeWidth={3}/>;})}</svg><ul style={{fontSize:e.fontSize}}>{labels.map((l,i)=><li key={i}><i style={{background:i===0?accent:chartColors[i%chartColors.length]}}/>{l}<b>{values[i]}</b></li>)}</ul></div>;}
  const pad=42,width=e.w-pad*2,height=e.h-72;const xs=values.map((_,i)=>pad+(i+.5)*width/Math.max(1,values.length));const ys=values.map(v=>20+height*(1-v/max));return <svg viewBox={`0 0 ${e.w} ${e.h}`} className="slide-chart" role="img" aria-label={labels.map((l,i)=>`${l}: ${values[i]}`).join(", ")}>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={pad} x2={e.w-pad} y1={20+height*f} y2={20+height*f} stroke="#a3b0c155" strokeWidth={1}/><text x={pad-8} y={25+height*f} textAnchor="end" fontSize={14} fill={e.color}>{Math.round(max*(1-f)*100)/100}</text></g>)}{e.chart==="line"&&<polyline points={xs.map((x,i)=>`${x},${ys[i]}`).join(" ")} stroke={accent} strokeWidth={5} fill="none"/>}{values.map((v,i)=><g key={i}>{e.chart==="line"?<circle cx={xs[i]} cy={ys[i]} r={6} fill={accent}/>:<rect x={xs[i]-width/values.length*.3} y={ys[i]} width={width/values.length*.6} height={Math.max(0,height*(v/max))} rx={5} fill={accent}/>}<text x={xs[i]} y={Math.max(14,ys[i]-9)} textAnchor="middle" fontSize={e.fontSize||20} fill={e.color}>{v}</text><text x={xs[i]} y={e.h-18} textAnchor="middle" fontSize={Math.min(e.fontSize||20,Math.max(10,110/values.length))} fill={e.color}>{labels[i].slice(0,20)}</text></g>)}</svg>;
}
export function ElementContent({element:e,interactive=false,eagerImages=false}:{element:SlideElement;interactive?:boolean;eagerImages?:boolean}) {
  const [playing,setPlaying]=useState(false);useEffect(()=>setPlaying(false),[e.videoId]);
  if(e.type==="text")return <div className="slide-rich-content" style={{fontFamily:e.font,fontSize:e.fontSize,color:e.color,textAlign:e.align}}>{e.doc&&<RichContent node={e.doc} interactive={interactive}/>}</div>;
  if(e.type==="image")return e.src?<img className="slide-image" src={e.src} alt={e.alt||"Imagem do slide"} draggable={false} loading={interactive||eagerImages?"eager":"lazy"} decoding="async" style={{objectFit:e.fit,objectPosition:`${e.positionX}% ${e.positionY}%`,borderRadius:e.radius}}/>:<div className="slide-image-placeholder"><ImageIcon size={48}/><span>Adicione sua imagem</span></div>;
  if(e.type==="shape"){const common={fill:e.fill||"none",stroke:e.stroke||"none",strokeWidth:e.strokeWidth||0};return <svg viewBox={`0 0 ${e.w} ${e.h}`} preserveAspectRatio="none" aria-hidden="true">{e.shape==="ellipse"?<ellipse cx={e.w/2} cy={e.h/2} rx={Math.max(1,(e.w-(e.strokeWidth||0))/2)} ry={Math.max(1,(e.h-(e.strokeWidth||0))/2)} {...common}/>:e.shape==="triangle"?<polygon points={`${e.w/2},3 ${e.w-3},${e.h-3} 3,${e.h-3}`} {...common}/>:e.shape==="line"?<line x1={2} y1={e.h/2} x2={e.w-2} y2={e.h/2} {...common}/>:e.shape==="arrow"?<polygon points={`1,${e.h*.3} ${e.w*.7},${e.h*.3} ${e.w*.7},2 ${e.w-2},${e.h/2} ${e.w*.7},${e.h-2} ${e.w*.7},${e.h*.7} 1,${e.h*.7}`} {...common}/>:<rect x={(e.strokeWidth||0)/2} y={(e.strokeWidth||0)/2} width={e.w-(e.strokeWidth||0)} height={e.h-(e.strokeWidth||0)} rx={e.radius||0} {...common}/>}</svg>;}
  if(e.type==="table")return <table className="slide-table" style={{fontSize:e.fontSize,color:e.color}}><tbody>{e.cells?.map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0&&e.header?<th style={{background:e.fill,color:"#ffffff"}} key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table>;
  if(e.type==="chart")return <SlideChart element={e}/>;
  if(e.type==="video"&&!interactive)return <div className="slide-video-placeholder"><Play size={48}/><span>{e.videoId?"Vídeo do YouTube":"Adicione um link do YouTube"}</span></div>;
  if(e.type==="video")return interactive&&playing&&e.videoId?<iframe title="Vídeo da aula" src={`https://www.youtube-nocookie.com/embed/${e.videoId}?start=${e.videoStart||0}&autoplay=1`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<button className="slide-video-placeholder" type="button" disabled={!interactive||!e.videoId} onClick={()=>setPlaying(true)}><Play size={48}/><span>{e.videoId?"Reproduzir vídeo":"Adicione um link do YouTube"}</span></button>;
  return null;
}
export function QuizSlideContent({question:q,correct=null,explanation="",countdown=0,seconds,untimed=false,draft=false}:{question?:Omit<Question,"correct"|"explanation">;correct?:number|null;explanation?:string;countdown?:number;seconds?:number;untimed?:boolean;draft?:boolean}) {
  if(countdown>0)return <div className="slide-question-countdown"><span>Prepare-se para responder</span><b>{countdown}</b></div>;
  const compact=!!q&&(q.text.length>230||q.options.some(option=>option.length>100));
  const headingSize=q?.image?(q.text.length>260?20:q.text.length>110?24:30):q&&q.text.length>230?24:q&&q.text.length>160?28:q&&q.text.length>110?35:44;
  return <div className={`slide-question-content ${compact?"slide-question-compact":""}`}><div className="slide-question-meta"><span>É A VEZ DA TURMA</span>{seconds!==undefined&&<b>{untimed?"Tempo livre":`${seconds}s`}</b>}{draft&&<small>Prévia · responda pelo celular durante a aula</small>}</div>{q?.image&&<img className="slide-question-image" src={q.image} alt={q.imageAlt||"Imagem da pergunta"}/>}<h2 style={{fontSize:headingSize}}>{q?.text||"Escreva a pergunta para a turma"}</h2><div className="slide-question-options">{(q?.options||["Alternativa A","Alternativa B","Alternativa C","Alternativa D"]).map((option,i)=><div className={`slide-question-option option-${i} ${correct!==null&&correct===i?"slide-option-correct":""} ${correct!==null&&correct!==i?"slide-option-muted":""}`} key={i}><b>{String.fromCharCode(65+i)}</b>{q?.optionImages?.[i]&&<img src={q.optionImages[i]} alt={option}/>}<span style={{fontSize:compact?15:option.length>70?19:23}}>{option||`Alternativa ${String.fromCharCode(65+i)}`}</span>{correct===i&&<strong>✓</strong>}</div>)}</div>{correct!==null&&<p className="slide-question-explanation">{explanation?explanation.length>180?explanation.slice(0,177)+"…":explanation:"Converse com a turma sobre a resposta correta."}</p>}</div>;
}
export function SlideCanvas({slide,theme="azul",step=20,number,showNumber=false,interactive=false,eagerImages=false,editor=false,selected=[],onSelect,onDoubleClick,onHandle,question,correct=null,explanation="",countdown=0,seconds,untimed,draft=false}:{slide:LessonSlide|PublicSlide;theme?:string;step?:number;number?:number;showNumber?:boolean;interactive?:boolean;eagerImages?:boolean;editor?:boolean;selected?:string[];onSelect?:(id:string,event:React.PointerEvent)=>void;onDoubleClick?:(id:string)=>void;onHandle?:(id:string,handle:string,event:React.PointerEvent)=>void;question?:Omit<Question,"correct"|"explanation">;correct?:number|null;explanation?:string;countdown?:number;seconds?:number;untimed?:boolean;draft?:boolean}) {
  const ref=useRef<HTMLDivElement>(null);const [scale,setScale]=useState(1);useEffect(()=>{const element=ref.current;if(!element)return;const observer=new ResizeObserver(()=>setScale(element.clientWidth/SLIDE_WIDTH));observer.observe(element);setScale(element.clientWidth/SLIDE_WIDTH);return()=>observer.disconnect();},[]);
  const t=themeFor(theme),bg=slide.background;const q=question||("question" in slide?slide.question:undefined);
  return <div ref={ref} className={`slide-frame ${editor?"slide-frame-editable":""}`} aria-label={`Slide ${number===undefined?"":number+1}: ${slide.title}`}><div className="slide-surface" style={{width:SLIDE_WIDTH,height:SLIDE_HEIGHT,transform:`scale(${scale})`,background:bg.color2?`linear-gradient(${bg.angle||135}deg,${bg.color},${bg.color2})`:bg.color,color:t.text,fontFamily:t.font}}>
    {bg.image&&<><img className="slide-background-image" src={bg.image} alt=""/><div className="slide-background-overlay" style={{background:"#000",opacity:(bg.overlay||0)/100}}/></>}
    {slide.kind==="question"&&<QuizSlideContent question={q} correct={correct} explanation={explanation} countdown={countdown} seconds={seconds} untimed={untimed} draft={draft}/>}
    {slide.elements.filter(e=>editor||(!e.hidden&&e.build<=step)).map(e=><div key={e.id} className={`slide-element ${editor?"slide-element-editor":""} ${selected.includes(e.id)?"slide-element-selected":""} ${e.locked?"slide-element-locked":""}`} style={{left:e.x,top:e.y,width:e.w,height:e.h,transform:`rotate(${e.rotation}deg)`,opacity:(e.opacity/100)*(editor&&e.hidden ? .35 : 1),outlineWidth:2/Math.max(.1,scale)}} onPointerDown={editor?event=>onSelect?.(e.id,event):undefined} onDoubleClick={editor?()=>onDoubleClick?.(e.id):undefined}><ElementContent element={e} interactive={interactive&&!editor} eagerImages={eagerImages||editor}/>{editor&&selected.includes(e.id)&&!e.locked&&["nw","n","ne","e","se","s","sw","w"].map(handle=><span key={handle} className={`slide-resize-handle handle-${handle}`} style={{width:9/Math.max(.1,scale),height:9/Math.max(.1,scale)}} onPointerDown={event=>{event.stopPropagation();onHandle?.(e.id,handle,event);}}/>)}</div>)}
    {showNumber&&number!==undefined&&<span className="slide-page-number" style={{color:t.muted}}>{String(number+1).padStart(2,"0")}</span>}
  </div></div>;
}
