import { integer, text, sqliteTable, index, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";
export const educators = sqliteTable("educators", { id: text("id").primaryKey(), secretHash: text("secret_hash").notNull(), name: text("name").notNull(), createdAt: integer("created_at").notNull(), expiresAt: integer("expires_at").notNull(), authId: text("auth_id") }, t => [uniqueIndex("idx_educators_secret").on(t.secretHash), uniqueIndex("idx_educators_auth").on(t.authId)]);
export const quizzes = sqliteTable("quizzes", { id: text("id").primaryKey(), owner: text("owner").notNull().references(() => educators.id), title: text("title").notNull(), questions: text("questions").notNull(), updatedAt: integer("updated_at").notNull(), mode: text("mode").notNull().default("speed"), untimed: integer("untimed").notNull().default(0), subject: text("subject").notNull().default(""), topic: text("topic").notNull().default("") }, t => [index("idx_quizzes_owner").on(t.owner, t.updatedAt)]);
export const rooms = sqliteTable("rooms", { code: text("code").primaryKey(), owner: text("owner").notNull().references(() => educators.id), title: text("title").notNull(), teacher: text("teacher").notNull(), questions: text("questions").notNull(), status: text("status").notNull().default("lobby"), questionIndex: integer("question_index").notNull().default(-1), startsAt: integer("starts_at"), endsAt: integer("ends_at"), playerCount: integer("player_count").notNull().default(0), answeredCount: integer("answered_count").notNull().default(0), rosterVersion: integer("roster_version").notNull().default(0), createdAt: integer("created_at").notNull(), expiresAt: integer("expires_at").notNull(), mode: text("mode").notNull().default("speed"), untimed: integer("untimed").notNull().default(0), presentation: text("presentation"), presentationId: text("presentation_id"), slideIndex: integer("slide_index").notNull().default(-1), buildStep: integer("build_step").notNull().default(0), blackout: integer("blackout").notNull().default(0) }, t => [index("idx_rooms_owner_status").on(t.owner, t.status, t.expiresAt), index("idx_rooms_owner_created").on(t.owner, t.createdAt)]);
export const players = sqliteTable("players", { id: text("id").primaryKey(), room: text("room").notNull().references(() => rooms.code, { onDelete: "cascade" }), secretHash: text("secret_hash").notNull(), name: text("name").notNull(), nameKey: text("name_key").notNull(), avatar: text("avatar").notNull(), joinedAt: integer("joined_at").notNull(), lastSeen: integer("last_seen").notNull().default(0) }, t => [uniqueIndex("idx_players_room_name").on(t.room, t.nameKey), uniqueIndex("idx_players_room_secret").on(t.room, t.secretHash)]);
export const answers = sqliteTable("answers", { room: text("room").notNull().references(() => rooms.code, { onDelete: "cascade" }), player: text("player").notNull().references(() => players.id, { onDelete: "cascade" }), questionIndex: integer("question_index").notNull(), option: integer("option").notNull(), correct: integer("correct").notNull(), points: integer("points").notNull(), elapsedMs: integer("elapsed_ms").notNull(), receivedAt: integer("received_at").notNull() }, t => [primaryKey({ columns: [t.room, t.player, t.questionIndex] }), index("idx_answers_round").on(t.room, t.questionIndex)]);

export const drafts = sqliteTable("drafts", { owner: text("owner").notNull().references(() => educators.id), id: text("id").notNull(), quiz: text("quiz").notNull(), updatedAt: integer("updated_at").notNull(), revision: integer("revision").notNull().default(1), writeId: text("write_id").notNull() }, t => [primaryKey({ columns: [t.owner, t.id] }), index("idx_drafts_owner_updated").on(t.owner, t.updatedAt)]);
export const questionBank = sqliteTable("question_bank", { id: text("id").primaryKey(), owner: text("owner").notNull().references(() => educators.id), question: text("question").notNull(), subject: text("subject").notNull().default(""), topic: text("topic").notNull().default(""), updatedAt: integer("updated_at").notNull() }, t => [index("idx_bank_owner_updated").on(t.owner, t.updatedAt)]);
export const uploads = sqliteTable("uploads", { id: text("id").primaryKey(), owner: text("owner").notNull().references(() => educators.id), contentType: text("content_type").notNull(), bytes: integer("bytes").notNull(), createdAt: integer("created_at").notNull() }, t => [index("idx_uploads_owner").on(t.owner)]);
export const shares = sqliteTable("shares", { token: text("token").primaryKey(), quizId: text("quiz_id").notNull(), owner: text("owner").notNull().references(() => educators.id), quiz: text("quiz").notNull(), createdAt: integer("created_at").notNull() }, t => [uniqueIndex("idx_shares_quiz").on(t.quizId), index("idx_shares_owner").on(t.owner)]);
export const presentations = sqliteTable("presentations", {id:text("id").primaryKey(),owner:text("owner").notNull().references(()=>educators.id),title:text("title").notNull(),document:text("document").notNull(),revision:integer("revision").notNull().default(1),writeId:text("write_id").notNull(),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_presentations_owner_updated").on(t.owner,t.updatedAt)]);
export const nativeSessions = sqliteTable("native_sessions", {
 id:text("id").primaryKey(), secretHash:text("secret_hash").notNull(), deviceName:text("device_name").notNull(),
 owner:text("owner").references(()=>educators.id), sourceOwner:text("source_owner").references(()=>educators.id),
 ipHash:text("ip_hash").notNull(), createdAt:integer("created_at").notNull(), expiresAt:integer("expires_at").notNull(), approvedAt:integer("approved_at")
},t=>[uniqueIndex("idx_native_secret").on(t.secretHash),index("idx_native_owner").on(t.owner),index("idx_native_ip_created").on(t.ipHash,t.createdAt)]);
